### ISSUE TITLE
undefined symbol: ffi_prep_cif_machdep running bundle on Raspbian 11

### ISSUE THREAD

**Issue by rgaufman** [ffi/ffi#1016]
When I run bundle install, I get:

```
    current directory: /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/libusb-0.6.4/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20230322-9830-avczdx.rb extconf.rb
/usr/local/bin/ruby: symbol lookup error: /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so: undefined symbol: ffi_prep_cif_machdep

extconf failed, exit code 127

Gem files will remain installed in /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/libusb-0.6.4 for inspection.
Results logged to /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/extensions/armv7l-linux-eabihf/3.1.0-static/libusb-0.6.4/gem_make.out

  /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  /usr/local/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in build_extensions'
  /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  /usr/local/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/rubygems_gem_installer.rb:72:in `build_extensions'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/source/rubygems.rb:200:in `install'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/gem_installer.rb:54:in `install'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:62:in `apply_func'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:57:in `block in process_queue'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:54:in `loop'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:54:in `process_queue'
  /data/deployer/timeagent/vendor/bundle/ruby/3.1.0/gems/bundler-2.4.5/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
```

This used to work fine previously, but I loaded a few units now with the latest image of Raspbian OS 11 and I am suddenly getting this error and tearing my hair out trying to figure it out.

Any ideas?

**Comment by larskanis** [comment]
`undefined symbol: ffi_prep_cif_machdep` looks like the file `/usr/local/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so` was compiled on Macos, where you bundled your package. I can not say why this happens, but I know from experience that cross platform usage of `bundle package` often fails.

You should run the `bundle package` on the target platform; the Raspberry Pi.

**Comment by rgaufman** [comment]
I've been using bundle package for years now with so far good success, I wonder what changed for this to suddenly cause problems. Do you have any rough idea what this could be to point me in the right direction?

**Comment by rgaufman** [comment]
I now have another Raspberry Pi where re-installing ffi does not help:

```
$ rm -R /usr/local/lib/ruby/gems/3.1.0/gems/ffi-1.15.5
$ gem install libusb
Fetching ffi-1.15.5.gem
Building native extensions. This could take a while...
Successfully installed ffi-1.15.5
Building native extensions. This could take a while...
ERROR:  Error installing libusb:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/3.1.0/gems/libusb-0.6.4/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20230327-26079-gt026i.rb extconf.rb
/usr/local/bin/ruby: symbol lookup error: /usr/local/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.so: undefined symbol: ffi_prep_cif_machdep

extconf failed, exit code 127

Gem files will remain installed in /usr/local/lib/ruby/gems/3.1.0/gems/libusb-0.6.4 for inspection.
Results logged to /usr/local/lib/ruby/gems/3.1.0/extensions/armv7l-linux-eabihf/3.1.0-static/libusb-0.6.4/gem_make.out
```

```
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [armv7l-linux-eabihf]
$ gem -v
3.3.7
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

Any ideas?
