### ISSUE TITLE
Can't Execute After install on Ubuntu 20

### ISSUE THREAD

**Issue by coneybeare** [ffi/ffi#1060]
I can get an installation working, but usage fails with no messaging:

```
[REDACTED]$ ruby --version
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-linux]
```

```
root@REDACTED:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

```
root@REDACTED:~# apt install clang make ruby-dev libffi-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
clang is already the newest version (1:10.0-50~exp1).
make is already the newest version (4.2.1-1.2).
ruby-dev is already the newest version (1:2.7+1).
libffi-dev is already the newest version (3.4.2-4).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

```
[REDACTED]$ bundle info ffi
  * ffi (1.15.5)
	Summary: Ruby FFI
	Homepage: https://github.com/ffi/ffi/wiki
	Path: /home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/ffi-1.15.5
```

I have tried installing latest ffi, also older versions (1.15.5), and always get the error below:

```
~/.rvm/bin/rvm ruby-2.7.8@REDACTED do bundle exec rake assets:precompile
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'sassc-rails'.
Gem Load Error is:
Backtrace for gem load error is:
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi/library.rb:275:in `attach'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi/library.rb:275:in `attach_function'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:40:in `attach_function'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native/native_context_api.rb:5:in `<module:Native>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native/native_context_api.rb:4:in `<module:SassC>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native/native_context_api.rb:3:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:60:in `require_relative'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:60:in `<module:Native>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:6:in `<module:SassC>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:5:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `require'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `require_relative'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `<top (required)>'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/runtime.rb:74:in `require'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler.rb:174:in `require'
/home/REDACTED/REDACTED.com/releases/20231111171421/config/application.rb:7:in `<top (required)>'
/home/REDACTED/REDACTED.com/releases/20231111171421/Rakefile:5:in `require'
/home/REDACTED/REDACTED.com/releases/20231111171421/Rakefile:5:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/application.rb:734:in `raw_load_rakefile'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/application.rb:126:in `block in load_rakefile'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/application.rb:125:in `load_rakefile'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/application.rb:82:in `block in run'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/bin/rake:23:in `load'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/bin/rake:23:in `<top (required)>'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/bin/bundle:30:in `load'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/bin/bundle:30:in `<main>'
/home/REDACTED/.rvm/gems/ruby-2.7.8@REDACTED/bin/ruby_executable_hooks:22:in `eval'
/home/REDACTED/.rvm/gems/ruby-2.7.8@REDACTED/bin/ruby_executable_hooks:22:in `<main>'
Bundler Error Backtrace:
/home/REDACTED/REDACTED.com/releases/20231111171421/config/application.rb:7:in `<top (required)>'
/home/REDACTED/REDACTED.com/releases/20231111171421/Rakefile:5:in `require'
/home/REDACTED/REDACTED.com/releases/20231111171421/Rakefile:5:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/bin/bundle:30:in `load'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/bin/bundle:30:in `<main>'
/home/REDACTED/.rvm/gems/ruby-2.7.8@REDACTED/bin/ruby_executable_hooks:22:in `eval'
/home/REDACTED/.rvm/gems/ruby-2.7.8@REDACTED/bin/ruby_executable_hooks:22:in `<main>'
      02
Caused by:
      02
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi/library.rb:275:in `attach'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/ffi-1.15.5/lib/ffi/library.rb:275:in `attach_function'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:40:in `attach_function'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native/native_context_api.rb:5:in `<module:Native>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native/native_context_api.rb:4:in `<module:SassC>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native/native_context_api.rb:3:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:60:in `require_relative'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:60:in `<module:Native>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:6:in `<module:SassC>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:5:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `require'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `require_relative'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/sassc-rails-2.1.2/lib/sassc-rails.rb:3:in `<top (required)>'
/home/REDACTED/REDACTED.com/releases/20231111171421/config/application.rb:7:in `<top (required)>'
/home/REDACTED/REDACTED.com/releases/20231111171421/Rakefile:5:in `require'
/home/REDACTED/REDACTED.com/releases/20231111171421/Rakefile:5:in `<top (required)>'
/home/REDACTED/REDACTED.com/shared/bundle/ruby/2.7.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/bin/bundle:30:in `load'
/home/REDACTED/.rvm/rubies/ruby-2.7.8/bin/bundle:30:in `<main>'
/home/REDACTED/.rvm/gems/ruby-2.7.8@REDACTED/bin/ruby_executable_hooks:22:in `eval'
/home/REDACTED/.rvm/gems/ruby-2.7.8@REDACTED/bin/ruby_executable_hooks:22:in `<main>'
(See full trace by running task with --trace)
```

I placed some STDOUT logging on the affected line by rescuing the error:

```
mname.to_s: version | e:
mname.to_s: make_options | e: P$��
mname.to_s: make_file_context | e: P$��
mname.to_s: _make_data_context | e: P$��
mname.to_s: compile_file_context | e: P$��
mname.to_s: compile_data_context | e: P$��
mname.to_s: delete_file_context | e: P$��
mname.to_s: delete_data_context | e: P$��
mname.to_s: file_context_get_context | e: P$��
mname.to_s: data_context_get_context | e: P$��
mname.to_s: context_get_options | e: P$��
mname.to_s: file_context_get_options | e: P$��
mname.to_s: data_context_get_options | e: P$��
mname.to_s: file_context_set_options | e: P$��
mname.to_s: data_context_set_options | e: P$��
mname.to_s: option_get_precision | e: P$��
mname.to_s: option_get_output_style | e: �Лn
mname.to_s: option_get_source_comments | e: P$��
mname.to_s: option_get_source_map_embed | e: P$��
mname.to_s: option_get_source_map_contents | e: P$��
mname.to_s: option_get_omit_source_map_url | e: P$��
mname.to_s: option_get_is_indented_syntax_src | e: P$��
mname.to_s: option_get_input_path | e: P$��
mname.to_s: option_get_output_path | e: P$��
mname.to_s: option_get_include_path | e: P$��
mname.to_s: option_get_source_map_file | e: P$��
mname.to_s: option_get_c_functions | e: P$��
mname.to_s: option_set_precision | e: P$��
mname.to_s: option_set_output_style | e: P$��
mname.to_s: option_set_source_comments | e: P$��
mname.to_s: option_set_source_map_embed | e: P$��
mname.to_s: option_set_source_map_contents | e: P$��
mname.to_s: option_set_omit_source_map_url | e: P$��
mname.to_s: option_set_is_indented_syntax_src | e: P$��
mname.to_s: option_set_input_path | e: P$��
mname.to_s: option_set_output_path | e: P$��
mname.to_s: option_set_include_path | e: P$��
mname.to_s: option_set_source_map_file | e: P$��
mname.to_s: option_set_c_functions | e: P$��
mname.to_s: option_set_c_importers | e: P$��
mname.to_s: context_get_output_string | e: P$��
mname.to_s: context_get_error_status | e: P$��
mname.to_s: context_get_error_json | e: P$��
mname.to_s: context_get_error_message | e: P$��
mname.to_s: context_get_error_file | e: P$��
mname.to_s: context_get_error_line | e: P$��
mname.to_s: context_get_error_column | e: P$��
mname.to_s: context_get_source_map_string | e: P$��
mname.to_s: _context_get_included_files | e: P$��
mname.to_s: compiler_get_last_import | e: P$��
mname.to_s: make_function_list | e: P$��
mname.to_s: make_function | e: P$��
mname.to_s: function_get_list_entry | e: P$��
mname.to_s: function_set_list_entry | e: P$��
mname.to_s: make_number | e: P$��
mname.to_s: make_string | e: P$��
mname.to_s: make_qstring | e: P$��
mname.to_s: make_color | e: P$��
mname.to_s: make_map | e: P$��
mname.to_s: make_list | e: P$��
mname.to_s: make_boolean | e: P$��
mname.to_s: map_set_key | e: P$��
mname.to_s: map_get_key | e: P$��
mname.to_s: map_set_value | e: P$��
mname.to_s: map_get_value | e: P$��
mname.to_s: map_get_length | e: P$��
mname.to_s: list_get_value | e: P$��
mname.to_s: list_set_value | e: P$��
mname.to_s: list_get_length | e: P$��
mname.to_s: make_error | e: P$��
mname.to_s: value_get_tag | e:
mname.to_s: value_is_null | e: P$��
mname.to_s: string_get_value | e: P$��
mname.to_s: string_is_quoted | e: P$��
mname.to_s: number_get_value | e: P$��
mname.to_s: number_get_unit | e: P$��
mname.to_s: boolean_get_value | e: P$��
mname.to_s: color_get_r | e: P$��
mname.to_s: color_set_r | e: P$��
mname.to_s: color_get_g | e: P$��
mname.to_s: color_set_g | e: P$��
mname.to_s: color_get_b | e: P$��
mname.to_s: color_set_b | e: P$��
mname.to_s: color_get_a | e: P$��
mname.to_s: color_set_a | e: P$��
mname.to_s: error_get_message | e: P$��
mname.to_s: error_set_message | e: P$��
mname.to_s: function_get_signature | e: P$��
mname.to_s: function_get_function | e: P$��
mname.to_s: function_get_cookie | e: P$��
mname.to_s: make_importer | e: P$��
mname.to_s: make_import_list | e: P$��
mname.to_s: make_import_entry | e: P$��
mname.to_s: import_set_list_entry | e: P$��
mname.to_s: import_get_imp_path | e: P$��
mname.to_s: import_get_abs_path | e: P$��
mname.to_s: import_get_source | e: P$��
mname.to_s: sass2scss | e: P$��
``` 

Similar logs were placed on the 1.16 latest version with similar results. Seems that the library cannot attach to the lower level methods. How can I resolve this?

**Comment by coneybeare** [comment]
```
[ds14293]$ ldd /home/urbanapps/giantuser.com/shared/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.16.3/ffi_c.so
	linux-vdso.so.1 (0x0000700d721db000)
	libruby.so.2.7 => /home/urbanapps/.rvm/rubies/ruby-2.7.8/lib/libruby.so.2.7 (0x0000700d71e53000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x0000700d71e34000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x0000700d71c42000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x0000700d71c1f000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x0000700d71c03000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x0000700d71bf9000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x0000700d71bf1000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x0000700d71bb6000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x0000700d71a67000)
	/lib64/ld-linux-x86-64.so.2 (0x0000700d721dd000)
```

☝️  Does this look right?
