### ISSUE TITLE
Unable to resolve type 'intptr_t' (TypeError) - Raspberry Pi 4 with Ubuntu 22.04 (aarch64) - ffi-1.16.3

### ISSUE THREAD

**Issue by rgaufman** [ffi/ffi#1100]
```
deployer@server:~/$ cat /usr/local/lib/ruby/gems/3.3.0/gems/ffi-1.16.3/lib/ffi/types.rb | grep intptr_t
deployer@server:~/$ uname -a
Linux TetherBox-1dea6d5b1b68c64fbb0e 5.15.0-1045-raspi #48-Ubuntu SMP PREEMPT Tue Jan 16 13:24:44 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
deployer@server:~/$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
deployer@server:~/$ dpkg --print-architecture
arm64
deployer@server:~/$ bin/rails c
$ bin/rails c
/data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi/types.rb:93:in `find_type': unable to resolve type 'intptr_t' (TypeError)

      raise TypeError, "unable to resolve type '#{name}'"
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi/library.rb:535:in `find_type'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi/library.rb:182:in `block in attach_function'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi/library.rb:182:in `map'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/ffi-1.16.3/lib/ffi/library.rb:182:in `attach_function'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/libusb-0.7.1/lib/libusb/call.rb:413:in `try_attach_function'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/libusb-0.7.1/lib/libusb/call.rb:468:in `<module:Call>'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/libusb-0.7.1/lib/libusb/call.rb:23:in `<module:LIBUSB>'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/libusb-0.7.1/lib/libusb/call.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.14/lib/zeitwerk/kernel.rb:34:in `require'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/libusb-0.7.1/lib/libusb.rb:17:in `<module:LIBUSB>'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/libusb-0.7.1/lib/libusb.rb:16:in `<top (required)>'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.6.14/lib/zeitwerk/kernel.rb:34:in `require'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/runtime.rb:55:in `each'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/runtime.rb:55:in `block in require'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/runtime.rb:44:in `each'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler/runtime.rb:44:in `require'
	from /usr/local/lib/ruby/gems/3.3.0/gems/bundler-2.5.10/lib/bundler.rb:207:in `require'
	from /data/deployer/tetherbox/config/application.rb:30:in `<top (required)>'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command/actions.rb:15:in `require_application!'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command/environment_argument.rb:31:in `require_application!'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command/actions.rb:19:in `boot_application!'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/commands/console/console_command.rb:105:in `perform'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command/base.rb:178:in `invoke_command'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command/base.rb:73:in `perform'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:71:in `block in invoke'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:149:in `with_argv'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/command.rb:69:in `invoke'
	from /data/deployer/tetherbox/vendor/bundle/ruby/3.3.0/gems/railties-7.1.3.3/lib/rails/commands.rb:18:in `<top (required)>'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
	from bin/rails:4:in `<main>'
```

I tried the usual stuff of rm -R vendor/bundle; bundle install; bundle pristine; gem pristine --all, etc. Tearing my hair out as this exact same config is working on other systems that are running Debian 12 instead of Ubuntu on the same Raspberry Pi 4.

Any ideas?

**Comment by larskanis** [comment]
This was a bug in ffi-1.16 on aarch64, which is fixed in the just released ffi-1.17.0.
