### ISSUE TITLE
FFI 1.7.0 gem fails to import

### ISSUE THREAD

**Issue by cisco-abrandel** [ffi/ffi#1104]
Running into this issue on multiple boxes. Reverting to 1.6.2 and things are fine. 

Ruby version 3.1.2
Rocky Linux 9.4 x86_64

```
irb(main):001:0> require 'ffi'
<internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require': cannot load such file -- ffi_c (LoadError)
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/ffi.rb:5:in `rescue in <top (required)>'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/ffi.rb:2:in `<top (required)>'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from (irb):1:in `<main>'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `<main>'
<internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ffi_c (LoadError)
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/ffi.rb:5:in `rescue in <top (required)>'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/ffi.rb:2:in `<top (required)>'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from (irb):1:in `<main>'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `<main>'
<internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': /lib64/libc.so: invalid ELF header - /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/3.1/ffi_c.so (LoadError)
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/ffi.rb:3:in `<top (required)>'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
	from (irb):1:in `<main>'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `<main>'
<internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ffi (LoadError)
	from <internal:/usr/local/rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):1:in `<main>'
	from /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `load'
	from /usr/local/rbenv/versions/3.1.2/bin/irb:25:in `<main>'
```

The "invalid ELF header" doesn't make a lot of sense to me, since the magic on the file is an ELF:

```
$ file /usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/3.1/ffi_c.so
/usr/local/rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/ffi-1.17.0-x86_64-linux-musl/lib/3.1/ffi_c.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped
```

**Comment by cisco-abrandel** [comment]
Closing this, seems to be the fact that we're getting the musl flavour on a non-musl distro from rubygems. Not clear why this is happening when the right arch appears to be in rbconfig.rb for the ruby version. The issue isn't reproducible in ruby 3.3.2, so this doesn't seem to ben an ffi problem.

**Comment by larskanis** [comment]
Thanks for your investigation and feedback!
