### ISSUE TITLE
Bundle update fails to download ffi 1.17.0

### ISSUE THREAD

**Issue by agrare** [ffi/ffi#1105]
When I run a `bundle update` I get a failure to download `https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem`.  It looks like what it should be trying to download is `https://rubygems.org/gems/ffi-1.17.0-x86_64-linux-gnu.gem`

```
Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)

Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to underlying error <bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)>
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:459:in `rescue in download_gem'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/rubygems_integration.rb:434:in `download_gem'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:476:in `download_gem'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:437:in `fetch_gem'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:421:in `fetch_gem_if_possible'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/source/rubygems.rb:163:in `install'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/worker.rb:62:in `apply_func'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/worker.rb:57:in `block in process_queue'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/worker.rb:54:in `loop'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/worker.rb:54:in `process_queue'
  /home/grare/adam/.gem/ruby/3.1.0/gems/bundler-2.5.11/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing ffi (1.17.0), and Bundler cannot continue.

In Gemfile:
  amazon_ssa_support was resolved to 0.1.0, which depends on
    manageiq-gems-pending was resolved to 0.1.0, which depends on
      sys-proctable was resolved to 1.2.7, which depends on
        ffi

```
Ruby version:
```
$ ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]
```

Bundler version:
```
$ bundler --version
Bundler version 2.5.11
```

Rubygems version:
```
$ gem --version
3.4.20
```

**Comment by larskanis** [comment]
Could you please update rubygems by `gem update --system` ? This should fix the issue.
FFI has now different gems for different platforms, similar to Nokogiri. Therefore there are many recommendations which can now be applied here: https://nokogiri.org/tutorials/installing_nokogiri.html

**Comment by agrare** [comment]
Thanks @larskanis, what is the minimum version of rubygems required to work with ffi 1.17?

**Comment by enescakir** [comment]
The dependabot upgraded `ffi` from `1.16.3` to `1.17.0` in our repository yesterday.
https://github.com/ubicloud/ubicloud/pull/1663

Our docker builds started to fail with the following error. `gem update --system` doesn't help.
https://github.com/ubicloud/ubicloud/actions/runs/9371732248/job/25801636965

```
#21 [bundler 6/6] RUN bundle install
#21 0.278 Bundler 2.4.19 is running, but your lockfile was generated with 2.5.10. Installing Bundler 2.5.10 and restarting using that version.
#21 1.288 Fetching gem metadata from [https://rubygems.org/.](https://rubygems.org/)
#21 1.325 Fetching bundler 2.5.10
#21 1.488 Installing bundler 2.5.10
#21 2.894 Fetching gem metadata from https://rubygems.org/.........
#21 6.498 Fetching https://github.com/***/erb-formatter.git
#21 8.495 Resolving dependencies...
#21 8.957 Resolving dependencies...
#21 9.313 Could not find gems matching 'ffi (= 1.17.0)' valid for all resolution platforms
#21 9.313 (aarch64-linux, arm64-darwin-22, arm64-darwin-23, x86_64-darwin-20,
#21 9.313 x86_64-linux) in rubygems repository https://rubygems.org/, cached gems or
#21 9.313 installed locally.
#21 9.313 
#21 9.313 The source contains the following gems matching 'ffi (= 1.17.0)':
#21 9.313   * ffi-1.17.0-aarch64-linux-gnu
#21 9.313   * ffi-1.17.0-aarch64-linux-musl
#21 9.313   * ffi-1.17.0-arm-linux-gnu
#21 9.313   * ffi-1.17.0-arm-linux-musl
#21 9.313   * ffi-1.17.0-arm64-darwin
#21 9.313   * ffi-1.17.0-java
#21 9.313   * ffi-1.17.0
#21 9.313   * ffi-1.17.0-x64-mingw-ucrt
#21 9.313   * ffi-1.17.0-x64-mingw32
#21 9.313   * ffi-1.17.0-x86-linux-gnu
#21 9.313   * ffi-1.17.0-x86-linux-musl
#21 9.313   * ffi-1.17.0-x86-mingw32
#21 9.313   * ffi-1.17.0-x86_64-darwin
#21 9.313   * ffi-1.17.0-x86_64-linux-gnu
#21 9.313   * ffi-1.17.0-x86_64-linux-musl
#21 ERROR: process "/bin/sh -c bundle install" did not complete successfully: exit code: 7
```

**Comment by bugthing** [comment]
> #21 9.313 Could not find gems matching 'ffi (= 1.17.0)' valid for all resolution platforms

I ran into the same issue, resolved it by adding a platform

`bundle lock --add-platform x86_64-linux-musl`

I think this was due to developing on a GNU based linux but my container image is musl based (alpine linux), so now the bundle references both

**Comment by enescakir** [comment]
> bundle lock --add-platform x86_64-linux-musl

Thanks, this helped us build the Docker image. Interestingly, with version `1.16.3`, we could build Alpine images without adding a new `musl` platform

**Comment by bugthing** [comment]
> with version `1.16.3`, we could build Alpine images without adding a new `musl` platform

I believe that is due to that fact that from v 1.17 

> FFI has now different gems for different platforms, similar to Nokogiri

**Comment by jcoyne** [comment]
I've found that the rubygems that ships with Ruby 3.1 causes this problem. The default version of rubygems in Ruby 3.3 does not have this issue.

**Comment by jeffmeyers** [comment]
We ran into this as well, and worked around it by appending `force_ruby_platform: true` ([docs](https://bundler.io/v2.5/man/gemfile.5.html#FORCE_RUBY_PLATFORM)) to our Gemfile.

Our symptom, which I haven't entirely found the root cause of yet, was a CI build failing with `Bundler::GemNotFound: Could not find ffi-1.17.0-x86_64-linux.gem for installation`, while `ffi-1.17.0-aarch64-linux-gnu.gem` was in both the cache and lockfile.

**Comment by jeffmeyers** [comment]
As a follow-up, I believe this is because the Linux platform name is normalized to strip out `gnu`, leading to searching for `linux.gem` rather than `linux-gnu.gem`: https://github.com/rubygems/rubygems/blob/a15e2cb599e1415d0e9577eb7ca2d0df985a4c38/lib/rubygems/platform.rb#L219

**Comment by agrare** [comment]
> I believe this is because the Linux platform name is normalized to strip out gnu, leading to searching for linux.gem rather than linux-gnu.gem

Yes I believe this is the issue as well (see the original description).  I think the target platform should be `x86_64-linux`, @larskanis mentions nokogiri and they build for this platform not -gnu (ref: https://rubygems.org/gems/nokogiri/versions/1.16.5-x86_64-linux)

If there is a reason why the target platform is `x86_64-linux-gnu` rather than `x86_64-linux` and a newer rubygems is required I think that minimum version should be documented.

**Comment by jeffmeyers** [comment]
I set up two tests today with a simple Gemfile:

```
source "https://rubygems.org"

gem "ffi", "~> 1"
```

I then bundled that and ran `bundle cache --all-platforms` with both Ruby 3.1.2 (which our GitHub Action used) and 3.1.6 (which our development and production environments use).

With 3.1.2, `ls vendor/cache`:
```
ffi-1.17.0-arm64-darwin.gem  ffi-1.17.0-x86_64-darwin.gem  ffi-1.17.0.gem
```

With 3.1.6, `ls vendor/cache`:
```
ffi-1.17.0-x86_64-linux-gnu.gem
```

Any ideas on why these outcomes would be so different?

**Comment by 12joan** [comment]
I encountered this issue a week ago when @depfu batch updated my Bundler dependencies ([commit](https://github.com/12joan/untitled-note/pull/478/commits/16acf8a49d7e0429f59e69b2640b7c50121088a5#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL128), [error](https://github.com/12joan/untitled-note/actions/runs/9443549793/job/26007484101#step:3:440)).

```diff
-    ffi (1.16.3)
+    ffi (1.17.0-aarch64-linux-musl)
+    ffi (1.17.0-arm64-darwin)
+    ffi (1.17.0-x86_64-linux-gnu)
```

I fixed it manually ([commit](https://github.com/12joan/untitled-note/pull/478/commits/f376383d1ec3221135ccef7e16d4ec995a5b761e#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fR128)):
```diff
-    ffi (1.17.0-aarch64-linux-musl)
-    ffi (1.17.0-arm64-darwin)
-    ffi (1.17.0-x86_64-linux-gnu)
+    ffi (1.17.0)
```

But in this week's batch update, Depfu reintroduced the error ([commit](https://github.com/12joan/untitled-note/pull/492/files#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL128)):
```diff
-    ffi (1.17.0)
+    ffi (1.17.0-aarch64-linux-musl)
+    ffi (1.17.0-arm64-darwin)
+    ffi (1.17.0-x86_64-linux-gnu)
```

If this is going to happen every week when Depfu updates my dependencies, I'll leave Depfu's PR unmerged until the issue with `ffi` gets resolved.

**Comment by maxrosecollins** [comment]
I’m having issues with this too

**Comment by chrisarcand** [comment]
We're also having issues that I believe are due to this same problem. I've avoided the problem altogether by downgrading to 0.15.5, as it's a transitive dependency anyway. 

[I agree with @agrare's assessment of the situation.](https://github.com/ffi/ffi/issues/1105#issuecomment-2168554436)

**Comment by MattKitmanLabs** [comment]
> > bundle lock --add-platform x86_64-linux-musl
> 
> Thanks, this helped us build the Docker image. Interestingly, with version `1.16.3`, we could build Alpine images without adding a new `musl` platform

Most gems do, it's just this one that craps out, they keep referencing Nokogiri, but that doesn't have this issue.

**Comment by agrare** [comment]
@larskanis any update here with respect to the difference between the behavior of this gem and others that follow this approach e.g. nokogiri which don't have this issue?

**Comment by jayaddison** [comment]
Adding a `bundler` config option -- possibly a workaround -- allowed me to proceed past this same issue:

Because the platform named in the attempted, HTTP-403'd download, had the suffix `x86_64-linux.gem`, instead of the _expected_ suffix of `x86_64-linux-gnu.gem` -- note the `gnu` (based on `ruby --version` including `x86_64-linux-gnu` in the output), and since the project I'm attempting to use uses `bundler`, I followed some [documentation in `nokogiri`](https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem) and ran:

```sh
$ bundle config set force_ruby_platform true
```

That allowed me to build the project; FWIW, the relevant config was persisted locally into a `.bundle/config` file in the project directory.

**Comment by MattKitmanLabs** [comment]
> Adding a `bundler` config option -- possibly a workaround -- allowed me to proceed past this same issue:
> 
> Because the platform named in the attempted, HTTP-403'd download, had the suffix `x86_64-linux.gem`, instead of the _expected_ suffix of `x86_64-linux-gnu.gem` -- note the `gnu` (based on `ruby --version` including `x86_64-linux-gnu` in the output), and since the project I'm attempting to use uses `bundler`, I followed some [documentation in `nokogiri`](https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem) and ran:
> 
> ```shell
> $ bundle config set force_ruby_platform true
> ```
> 
> That allowed me to build the project; FWIW, the relevant config was persisted locally into a `.bundle/config` file in the project directory.

You want to avoid that if at all possible and use the precompiled gems: https://github.com/ffi/ffi/issues/1105#issuecomment-2447971512

**Comment by msatdt** [comment]
I also got this error message:

`Bundler::InstallError: Bundler::HTTPError: Could not download gem from https://rubygems.org/ due to underlying error <bad response Forbidden 403 (https://rubygems.org/gems/ffi-1.17.0-x86_64-linux.gem)>`

It indicates, that the server is not happy to serve you that file.

I could solve the issue by downloading it from here: https://rubygems.org/gems/ffi-1.17.0-x86_64-linux-gnu.gem (notice the `-gnu` in the filename.

Then install this gem file via  `sudo gem install --local /home/user/Downloads/ffi-1.17.0-x86_64-linux-gnu.gem`

**Comment by zhipengwu90** [comment]
I have the same issue, it is end up there is space on the folder name, 
I /Users/user/Desktop/Project List/ORCproject, there is a space on Project List, which could be causing problems during the installation process.

**Comment by larskanis** [comment]
The reason ffi-1.17.0 is using distinct gem versions for musl and glibc (alias `*-linux-gnu.gem`) is that the binaries aren't compatible. The glibc version crashes on musl. In nokogiri we managed to make the glibc binaries compatible to musl by patches [like](https://github.com/sparklemotion/nokogiri/commit/a3d9438b2f86b214b7e65d8d63a48966bc321332) [these](https://github.com/sparklemotion/nokogiri/commit/004e6a6ee1561bbe861cba2446909a41f07e5cb6). This wasn't possible for ffi.

So adding the relevant platforms like:
```sh
bundle lock --add-platform x86_64-linux-gnu
bundle lock --add-platform x86_64-linux-musl
bundle lock --add-platform ruby
```
to the `Gemfile.lock` and using a recent bundler version should do the trick.

Or if this doesn't work for some reason, forcing the usage of the source gem in the `Gemfile`:
```ruby
gem "ffi", force_ruby_platform: true
```

**Comment by kynan** [comment]
I was able to resolve my `bundle update` failure with @jayaddison's [comment](https://github.com/ffi/ffi/issues/1105#issuecomment-2447971512) - thanks!

**Comment by ayushman-parasar** [comment]
I was able to resolve this using [this](https://github.com/ffi/ffi/issues/608#issuecomment-363698071)

**Comment by djpremier** [comment]
Same problem with platform name, need a gem version like `ffi (1.17.0-x86_64-linux)`.

I'm using the Rails official docker image: `ghcr.io/rails/devcontainer/images/ruby:3.2.6`

```sh
$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```sh
$ ruby --version
ruby 3.2.6 (2024-10-30 revision 63aeb018eb) [x86_64-linux]
```

```sh
$ bundle platform
Your platform is: x86_64-linux

Your app has gems that work on these platforms:
* x86_64-linux
* x86_64-linux-musl

Your Gemfile specifies a Ruby version requirement:
* ruby 3.2.6

Your current platform satisfies the Ruby version requirement.
```

**Comment by djpremier** [comment]
> Same problem with platform name, need a gem version like `ffi (1.17.0-x86_64-linux)`.
> 
> I'm using the Rails official docker image: `ghcr.io/rails/devcontainer/images/ruby:3.2.6`
> 
> ```shell
> $ cat /etc/*-release
> PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
> NAME="Debian GNU/Linux"
> VERSION_ID="12"
> VERSION="12 (bookworm)"
> VERSION_CODENAME=bookworm
> ID=debian
> HOME_URL="https://www.debian.org/"
> SUPPORT_URL="https://www.debian.org/support"
> BUG_REPORT_URL="https://bugs.debian.org/"
> ```
> 
> ```shell
> $ ruby --version
> ruby 3.2.6 (2024-10-30 revision 63aeb018eb) [x86_64-linux]
> ```
> 
> ```shell
> $ bundle platform
> Your platform is: x86_64-linux
> 
> Your app has gems that work on these platforms:
> * x86_64-linux
> * x86_64-linux-musl
> 
> Your Gemfile specifies a Ruby version requirement:
> * ruby 3.2.6
> 
> Your current platform satisfies the Ruby version requirement.
> ```

It seems like it's really just a Debian issue, I forced the Bundler version update and it worked fine.

Reference: https://github.com/sass-contrib/sass-embedded-host-ruby/issues/269#issuecomment-2519075802

**Comment by principlebrothers** [comment]
> > #21 9.313 Could not find gems matching 'ffi (= 1.17.0)' valid for all resolution platforms
> 
> I ran into the same issue, resolved it by adding a platform
> 
> `bundle lock --add-platform x86_64-linux-musl`
> 
> I think this was due to developing on a GNU based linux but my container image is musl based (alpine linux), so now the bundle references both

It worked for me as well

**Comment by Engabdozero125** [comment]
> > Adding a `bundler` config option -- possibly a workaround -- allowed me to proceed past this same issue:
> > Because the platform named in the attempted, HTTP-403'd download, had the suffix `x86_64-linux.gem`, instead of the _expected_ suffix of `x86_64-linux-gnu.gem` -- note the `gnu` (based on `ruby --version` including `x86_64-linux-gnu` in the output), and since the project I'm attempting to use uses `bundler`, I followed some [documentation in `nokogiri`](https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem) and ran:
> > ```shell
> > $ bundle config set force_ruby_platform true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That allowed me to build the project; FWIW, the relevant config was persisted locally into a `.bundle/config` file in the project directory.
> 
> You want to avoid that if at all possible and use the pre-compiled native gems, else you end up package managing a load of linux libs on your docker images: https://nokogiri.org/tutorials/installing_nokogiri.html#installing-native-gems
> 
> We managed to get around it with:
> 
> ```
> PLATFORMS
>   x86_64-linux
>   x86_64-linux-musl
> ```
this worked thanks alot

**Comment by Engabdozero125** [comment]
> > > Adding a `bundler` config option -- possibly a workaround -- allowed me to proceed past this same issue:
> > > Because the platform named in the attempted, HTTP-403'd download, had the suffix `x86_64-linux.gem`, instead of the _expected_ suffix of `x86_64-linux-gnu.gem` -- note the `gnu` (based on `ruby --version` including `x86_64-linux-gnu` in the output), and since the project I'm attempting to use uses `bundler`, I followed some [documentation in `nokogiri`](https://nokogiri.org/tutorials/installing_nokogiri.html#how-can-i-avoid-using-a-precompiled-native-gem) and ran:
> > > ```shell
> > > $ bundle config set force_ruby_platform true
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > That allowed me to build the project; FWIW, the relevant config was persisted locally into a `.bundle/config` file in the project directory.
> > 
> > 
> > You want to avoid that if at all possible and use the pre-compiled native gems, else you end up package managing a load of linux libs on your docker images: https://nokogiri.org/tutorials/installing_nokogiri.html#installing-native-gems
> > We managed to get around it with:
> > ```
> > PLATFORMS
> >   x86_64-linux
> >   x86_64-linux-musl
> > ```
> 
> this worked thanks alot

but after i got "An error occurred while installing libv8-node (18.19.0.0), and Bundler cannot continue.
"

**Comment by george-gca** [comment]
I am using `ruby:latest` docker image as [basis](https://github.com/alshedivat/al-folio/blob/main/Dockerfile), have these platforms set on my [Gemfile.lock](https://github.com/alshedivat/al-folio/blob/main/Gemfile.lock)

```
PLATFORMS
  aarch64-linux
  aarch64-linux-gnu
  aarch64-linux-musl
  arm-linux
  arm-linux-gnu
  arm-linux-gnueabihf
  arm-linux-musl
  arm-linux-musleabihf
  arm64-darwin
  x86-linux
  x86-linux-gnu
  x86-linux-musl
  x86_64-darwin
  x86_64-linux
  x86_64-linux-gnu
  x86_64-linux-musl
```

and while the image is created successfully, it is currently failing to run the docker container with

```
/usr/local/bundle/gems/bundler-2.6.2/lib/bundler/definition.rb:676:in 'Bundler::Definition#materialize': Could not find ffi-1.17.0-x86_64-linux-gnu in locally installed gems (Bundler::GemNotFound)
```

Adding `apt-get install libffi-dev` to the `Dockerfile` didn't solve the issue.

Adding `gem "ffi", force_ruby_platform: true` to `Gemfile` throwed a completely different error.

**Comment by Jaleelahmed94** [comment]
I ran into this issue again when consuming 1.17.1 version as well. Looks like the fix was not released in the patched version.

**Comment by cloudsbird** [comment]
Hi we also got this issues and solved by:
`gem "ffi", force_ruby_platform: true`

**Comment by jintajinta** [comment]
> Ruby 3.1 に同梱されている ruby​​gems がこの問題の原因であることがわかりました。Ruby 3.3 の ruby​​gems のデフォルト バージョンではこの問題は発生しません。
This worked for me.
