### ISSUE TITLE
FFI:AutoPointer tries to release subclassed reference after it is already freed

### ISSUE THREAD

**Issue by itspomf** [ffi/ffi#1126]
FFI attempts to automatically call the releaser of an `FFI::AutoPointer` which has already been freed, causing a segmentation fault due to disparate state.

Logging output follows:

```
Starting renderer ...
Boot time: 0.0949 seconds
[!] DEBUG: malloc( #<Vulkan::VkCommandBuffer address=0x00007f4478001f60> )
           at: /lib/context/pipeline.rb:319:in `render'
------[ TERMINATING ]---------------------------------------
[!] DEBUG: free( #<Vulkan::VkCommandBuffer address=0x00007f4478001f60> )
[!] DEBUG: called release() on #<Vulkan::VkCommandPool address=0x00000a000000000a> with: #<Vulkan::VkCommandBuffer address=0x00007f4478001f60>
           from /lib/context/pipeline.rb:373:in `render'
[!] DEBUG: removing #<Vulkan::VkCommandBuffer address=0x00007f4478001f60> (true)

 . . . . . .

[!] DEBUG: free( #<Vulkan::VkCommandBuffer address=0x00007f4478001f60> )
[!] DEBUG: called release() on #<Vulkan::VkCommandPool address=0x00000a000000000a> with: #<Vulkan::VkCommandBuffer address=0x00007f4478001f60>
           from /var/lib/gems/3.1.0/gems/ffi-1.17.0/lib/ffi/autopointer.rb:152:in `release'
[!] DEBUG: removing #<Vulkan::VkCommandBuffer address=0x00007f4478001f60> (false)
/lib/vulkan/commandBuffer.rb:24: [BUG] Segmentation fault at 0x00007f448db2c800
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0007 p:---- s:0037 e:000036 CFUNC  :vkFreeCommandBuffers
```

**Diagnosis:**

As you can see, the `VkCommandBuffer` is allocated once the render operation starts, and deallocated immediately upon termination, calling the refinement's `release()` method (NOT the same as `FFI::AutoPointer.release()`) on the owning `VkCommandPool` from the point that `free()` is **explicitly** called.

It then initiates removal of the dependency (in this case the command buffer instance), and indicates that it was present in the holder of that dependency.

Afterward, once the dependency tree has finished resolving, `free()` is called again on the exact same instance, but from FFI itself.  Observing the output, it correctly attempts to signal its holder to remove itself as a dependency (as it is being cleaned up), but the command pool indicates that it *is not* present.

However, FFI then attempts to proceed in calling the method `vkFreeCommandBuffers`, per the releaser, using a device, pool, and pointer which are no longer valid, causing the segmentation fault.

**Resolution:**

Do not attempt to automatically free a pointer which has already been freed.

**Notes on Implementation Differences:**

This code was made to work on JRuby and TruffleRuby, which use their own internal implementations of FFI kept in general parity with the source gem.  As such, it is strange that this behavior *only* occurs in CRuby.  Likewise, the original form of this methodology, reproduced below, fails only in JRuby but not in TruffleRuby:

```rb
module Dependency
  refine FFI::AutoPointer do
    attr :_deps
    
    # Overrides default behaviors to automatically clean up all dependencies, then free this pointer.
    def initialize( ref )
      super( ref, proc {|ptr|  # pass real pointer, then setup releaser
        notify()               # notify holder of this dependency
        yield ptr              # yield to call actual release code
      })
    end

# ...
end
```

**Source Code:**

Below is the refinement used in its current form:

```rb
require 'ffi'

# Describes an owner or progenitor of certain resources, or dependents, which
# must be cleaned up *before* this object.  Dependents register a callback with
# this object, which is invoked at deallocation-time.  Once all dependents are
# deallocated, this object will then clean up.
module Dependency
  module ReleaseMixin
    # Override functionality; paramenters are ignored.
    def free( ... )
      puts "[!] DEBUG: free( #{self} )"
      self.class.release( self )
    end
  end

  refine FFI::AutoPointer do
    import_methods ReleaseMixin

    # Overrides initializer.  Only works in CRuby and Truffle.
    def initialize( ref )
      super( ref, method( :free ))
      puts "[!] DEBUG: malloc( #{self } )",
           "           at: #{caller_locations[-2]}"
    end
  
    # Marks a dependency.
    private def depends( other )
      other.instance_variable_get( :@_deps ).then {|it|
        it = other.instance_variable_set( :@_deps, [] ) if it.nil?
        it.append( self )
      }
    end
    
    # Manually release a dependency.
    def release( target )
      puts "[!] DEBUG: called release() on #{self} with: #{target}",
           "           from #{caller_locations[-2]}"
      return unless instance_variable_defined? :@_deps
      puts "[!] DEBUG: removing #{target} (#{@_deps.include? target})"
      @_deps.delete( target )
    end
    
    # Notify all dependents of immediate termination.
    private def notify()
      return unless instance_variable_defined? :@_deps
      @_deps.reverse.each do |d| 
        d.free
      rescue Exception => err
        warn sprintf('Failed to release memory at %#x', d.address ),
             err.full_message
      end
      @_deps.clear
    end
  end
end

# Used by anything which needs to release dependencies with +free()+.
module Releaser
  refine FFI::AutoPointer do
    import_methods Dependency::ReleaseMixin
  end
end
```

And the release methods for both subclasses.

```rb
class Vulkan::VkCommandPool < FFI::AutoPointer
  using Dependency

  # ...

  # Release method.
  def self.release( ptr )
    ptr.send :notify
    ptr.device.release ptr
    Vulkan.vkDestroyCommandPool( ptr.device, ptr, nil )
  end

  # ...
end
```

```rb
class Vulkan::VkCommandBuffer < FFI::AutoPointer
  using Dependency

  # ...

  # Release method.
  def self.release( ptr )
    ptr.pool.release ptr
    Vulkan.vkFreeCommandBuffers( ptr.device, ptr.pool, 1, [ptr].to_ptr( :pointer ))
  end

  # ...
end
```

**Comment by larskanis** [comment]
Thanks for raising this issue with such a detailed bug report! It will take me a bit of time to verify this and find a solution.

Personally I always found the `FFI::AutoPointer` overly complicated, so that I prefer most of the time to use `define_finalizer` directly like so:

```ruby
  class Device
    def initialize(pDev)
      def pDev.unref_device(id)
        Call.libusb_unref_device(self)
      end
      Call.libusb_ref_device(pDev)
      ObjectSpace.define_finalizer(self, pDev.method(:unref_device))
      @pDev = pDev # for use by other device related methods
    end
  end

  Device.new(kind of FFI::Pointer or FFI:Struct)
```

The trick is to bind the releasing method to the FFI::Pointer that you get from C, by using its singleton class. That way it is called when the wrapping object is GC'ed by the ruby VM and it can do the releasing C call with `self` which is the `FFI::Pointer` to be released.

**Comment by itspomf** [comment]
I managed to circumvent this after finding the source code for `FFI::AutoPointer`.  As it turns out, the `::Releaser` created is what's used by `ObjectSpace` to run the finalizers at termination time, which is why the pointers were being cleaned up again.

Using the following code, I was able to both bypass the undesired behavior and ensure that the Releaser's state was properly modified.

```rb
module Dependency
  module ReleaserMixin
    # Bypass.
    def free( ... )
      @releaser.tap {|it|
        it.instance_variable_get( :@proc ).call( self )
        it.instance_variable_set( :@autorelease, false )
        it.instance_variable_set( :@ptr, nil )
        it.instance_variable_set( :@proc, nil )
      }
    end
  end
  # ...
end
```
