### ISSUE TITLE
Yosemite build failed

### ISSUE THREAD

**Issue by eripa** [ffi/ffi#347]
I know 10.10 is still a developer preview, so this is just FYI. 

`gem install ffi` cannot build native extensions on OS X 10.10.
### gem_make.out

```
/Users/eric/.rubies/ruby-2.1.2/bin/ruby extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
  --with-opt-dir
  --without-opt-dir
  --with-opt-include
  --without-opt-include=${opt-dir}/include
  --with-opt-lib
  --without-opt-lib=${opt-dir}/lib
  --with-make-prog
  --without-make-prog
  --srcdir=.
  --curdir
  --ruby=/Users/eric/.rubies/ruby-2.1.2/bin/ruby
  --with-ffi_c-dir
  --without-ffi_c-dir
  --with-ffi_c-include
  --without-ffi_c-include=${ffi_c-dir}/include
  --with-ffi_c-lib
  --without-ffi_c-lib=${ffi_c-dir}/lib
  --with-libffi-config
  --without-libffi-config
  --with-pkg-config
  --without-pkg-config
/Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:587:in `try_cpp'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:1067:in `block in have_header'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:918:in `block in checking_for'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:351:in `block (2 levels) in postpone'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:321:in `open'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:351:in `block in postpone'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:321:in `open'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:347:in `postpone'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:917:in `checking_for'
  from /Users/eric/.rubies/ruby-2.1.2/lib/ruby/2.1.0/mkmf.rb:1066:in `have_header'
  from extconf.rb:16:in `<main>'

extconf failed, exit code 1
```
### mkmf.log:

```
package configuration for libffi is not found
    "gcc-4.2 -o conftest -I/Users/eric/.rubies/ruby-2.1.2/include/ruby-2.1.0/x86_64-darwin13.0 -I/Users/eric/.rubies/ruby-2.1.2/include/ruby-2.1.0/ruby/backward -I/Users/eric/.rubies/ruby-2.1.2/include/ruby-2.1.0 -I. -I/Users/eric/.rubies/ruby-2.1.2/include  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/Users/eric/.rubies/ruby-2.1.2/lib -L. -L/Users/eric/.rubies/ruby-2.1.2/lib  -fstack-protector -L/usr/local/lib     -lruby-static -framework CoreFoundation  -lpthread -lgmp -ldl -lobjc "
    couldn't understand kern.osversion `14.0.0'
    In file included from /usr/include/stdio.h:65,
                     from /Users/eric/.rubies/ruby-2.1.2/include/ruby-2.1.0/ruby/defines.h:26,
                     from /Users/eric/.rubies/ruby-2.1.2/include/ruby-2.1.0/ruby/ruby.h:29,
                     from /Users/eric/.rubies/ruby-2.1.2/include/ruby-2.1.0/ruby.h:33,
                     from conftest.c:1:
    /usr/include/Availability.h:174:44: error: missing binary operator before token "("
    /usr/include/Availability.h:184:44: error: missing binary operator before token "("
    checked program was:
    /* begin */
    1: #include "ruby.h"
    2: 
    3: int main(int argc, char **argv)
    4: {
    5:   return 0;
    6: }
    /* end */
```

**Comment by nhodges** [comment]
1.9.6 does not build on Yosemite for me.

**Comment by shakerlxxv** [comment]
1.9.8 does not build on Yosemite for me after upgrading to Xcode 6.3

**Comment by tduehr** [comment]
it builds fine for me. please open another ticket and provide a link to the errors.
