### ISSUE TITLE
unable to resolve type 'uintptr_t' (TypeError)

### ISSUE THREAD

**Issue by icalvete** [ffi/ffi#386]
I'm ussing cygwin 64 in Windows 7

$ ruby.exe -v
ruby 2.0.0p594 (2014-10-27) [x86_64-cygwin]

After install this gem I get...

```
$ puppet
/home/icalvete/.gem/ruby/gems/ffi-1.9.6/lib/ffi/types.rb:70:in `find_type': unable to resolve type 'uintptr_t' (TypeError)
        from /home/icalvete/.gem/ruby/gems/ffi-1.9.6/lib/ffi/library.rb:427:in `typedef'
        from /home/icalvete/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir/functions.rb:21:in `<module:Functions>'
        from /home/icalvete/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir/functions.rb:9:in `<top (required)>'
        from /home/icalvete/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir.rb:2:in `require_relative'
        from /home/icalvete/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/icalvete/.gem/ruby/gems/facter-2.3.0/lib/facter/util/config.rb:56:in `<module:Config>'
        from /home/icalvete/.gem/ruby/gems/facter-2.3.0/lib/facter/util/config.rb:5:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/icalvete/.gem/ruby/gems/facter-2.3.0/lib/facter/util/resolution.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/icalvete/.gem/ruby/gems/facter-2.3.0/lib/facter/util/fact.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/icalvete/.gem/ruby/gems/facter-2.3.0/lib/facter.rb:35:in `<module:Facter>'
        from /home/icalvete/.gem/ruby/gems/facter-2.3.0/lib/facter.rb:30:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/icalvete/.gem/ruby/gems/puppet-3.7.3/lib/puppet.rb:6:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/icalvete/.gem/ruby/gems/puppet-3.7.3/lib/puppet/util/command_line.rb:12:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /usr/bin/puppet:7:in `<main>'
```

Thanks.

**Comment by tobiashochguertel** [comment]
Same issue here:

```
0 hochguertelto@workstation-win:/
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-cygwin]
```

```
0 hochguertelto@workstation-win:/
$ puppet
/cygdrive/c/Users/hochguertelto/.gem/ruby/gems/ffi-1.9.10/lib/ffi/types.rb:70:in `find_type': unable to resolve type 'uintptr_t' (TypeError)
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/ffi-1.9.10/lib/ffi/library.rb:432:in `typedef'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir/functions.rb:21:in `<module:Functions>'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir/functions.rb:9:in `<top (required)>'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir.rb:2:in `require_relative'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/win32-dir-0.5.0/lib/win32/dir.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/facter-2.4.4/lib/facter/util/config.rb:63:in `<module:Config>'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/facter-2.4.4/lib/facter/util/config.rb:5:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/facter-2.4.4/lib/facter/util/resolution.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/facter-2.4.4/lib/facter/util/fact.rb:2:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/facter-2.4.4/lib/facter.rb:35:in `<module:Facter>'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/facter-2.4.4/lib/facter.rb:30:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/puppet-4.2.2/lib/puppet.rb:10:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /cygdrive/c/Users/hochguertelto/.gem/ruby/gems/puppet-4.2.2/lib/puppet/util/command_line.rb:12:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/hochguertelto/.gem/ruby/gems/puppet-4.2.2/bin/puppet:4:in `<main>'
```

**Comment by tobiashochguertel** [comment]
Solution for me is the following: 

I added an type-mapping entry for `uintptr_t` to "types.conf" for my platform `x86_64-cygwin`:

`rbx.platform.typedef.uintptr_t = uint64`



**Before:**
**File: `C:\Users\hochguertelto\.gem\ruby\gems\ffi-1.9.10\lib\ffi\platform\x86_64-cygwin\types.conf`**
```
rbx.platform.typedef.size_t = uint64
rbx.platform.typedef.ptrdiff_t = int64
rbx.platform.typedef.ssize_t = int64
```

**After:**
**File: `C:\Users\hochguertelto\.gem\ruby\gems\ffi-1.9.10\lib\ffi\platform\x86_64-cygwin\types.conf`**
```
rbx.platform.typedef.size_t = uint64
rbx.platform.typedef.ptrdiff_t = int64
rbx.platform.typedef.ssize_t = int64
rbx.platform.typedef.uintptr_t = uint64
```

But now I get an new Error Message, which looks like an missing libray which I can't find...

*Log:*
```
$ puppet
no implicit conversion of Symbol into String.
Could not open library 'cygshell32.dll': No such file or directory
```

**Comment by tduehr** [comment]
Not that this isn't likely a bug... Why are you installing puppet under cygwin rather than the native agent?

http://docs.puppetlabs.com/puppet/latest/reference/install_windows.html

**Comment by tobiashochguertel** [comment]
Yes, because I want augeas support on windows. I've got augeas already and ruby-augeas already build and running with cygwin. I have the native Puppet agent running, this works, but I can't get augeas as nativ windows application. To get augeas successfully building with cygwin I used the [yacp/augeas cygwin port and patches](https://github.com/fd00/yacp/tree/master/augeas).

**Comment by cowofevil** [comment]
@tduehr @tobiashochguertel I have also ran into this bug. I'm simply trying to run the rake tasks for the [puppetlabs-powershell](https://github.com/puppetlabs/puppetlabs-powershell) module on Cygwin. For people running Windows and working with Puppet it is pretty common to use Cygwin. Solving this bug would make development easier for Windows users on Puppet related projects.

**Comment by tobiashochguertel** [comment]
@cowofevil I'm not sure if I had an solution found in September 2015, I had this error in relation to https://github.com/djberg96/win32-security/issues/7#issuecomment-193254856 . I have to analyse what I had tried in September 2015 .

It's interresting to hear that you also run cygwin and try to use puppet from cygwin. :+1:

**Comment by timotei** [comment]
@tduehr Btw, this issue *also* happens if you want to use `invoker` (http://invoker.codemancers.com/`:

```
$ invoker start
/home/user/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.14/lib/ffi/types.rb:69:in `find_type': unable to resolve type 'uintptr_t' (TypeError)
        from /home/user/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.14/lib/ffi/library.rb:446:in `typedef'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/win32-dir-0.5.1/lib/win32/dir/functions.rb:21:in `<module:Functions>'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/win32-dir-0.5.1/lib/win32/dir/functions.rb:9:in `<top (required)>'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/win32-dir-0.5.1/lib/win32/dir.rb:2:in `require_relative'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/win32-dir-0.5.1/lib/win32/dir.rb:2:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/facter-2.4.6/lib/facter/util/config.rb:63:in `<module:Config>'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/facter-2.4.6/lib/facter/util/config.rb:5:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/facter-2.4.6/lib/facter/util/resolution.rb:2:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/facter-2.4.6/lib/facter/util/fact.rb:2:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/facter-2.4.6/lib/facter.rb:35:in `<module:Facter>'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/facter-2.4.6/lib/facter.rb:30:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/invoker-1.5.1/lib/invoker/power/setup/linux_setup.rb:2:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/invoker-1.5.1/lib/invoker.rb:22:in `<top (required)>'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/user/.rvm/gems/ruby-2.3.1/gems/invoker-1.5.1/bin/invoker:5:in `<top (required)>'
        from /home/user/.rvm/gems/ruby-2.3.1/bin/invoker:23:in `load'
        from /home/user/.rvm/gems/ruby-2.3.1/bin/invoker:23:in `<main>'

```

**Comment by tduehr** [comment]
Somehow the cygwin config doesn't include `uintptr_t`. Please run `rake types_conf` and send a PR with the result.

**Comment by cardil** [comment]
Working solution. If someone is interested:

1) As @tobiashochguertel proposed, add `uintptr_t = uint64` to ffi cygwin platform.

`cat ~/.rvm/gems/ruby-2.5.5/gems/ffi-1.11.1/lib/ffi/platform/x86_64-cygwin/types.conf` contents should be:

```
rbx.platform.typedef.size_t = uint64
rbx.platform.typedef.ptrdiff_t = int64
rbx.platform.typedef.ssize_t = int64
rbx.platform.typedef.uintptr_t = uint64
```
2) Link couple Win32 libraries as Cygwin ones:

```bash
ln -s /cygdrive/c/Windows/System32/kernel32.dll /usr/bin/cygkernel32.dll
ln -s /cygdrive/c/Windows/System32/advapi32.dll /usr/bin/cygadvapi32.dll
ln -s /cygdrive/c/Windows/System32/ntdll.dll /usr/bin/cygntdll.dll
ln -s /cygdrive/c/Windows/System32/user32.dll /usr/bin/cyguser32.dll
ln -s /cygdrive/c/Windows/System32/shell32.dll /usr/bin/cygshell32.dll
```
3) Modify Puppet POSIX feature resolution here: `~/.rvm/gems/ruby-2.5.5/gems/puppet-6.9.0/lib/puppet/feature/base.rb` to be:

```ruby
# We can use POSIX user functions
Puppet.features.add(:posix) do
  require 'etc'
  require 'rbconfig'
  Puppet.features.syslog? && (RbConfig::CONFIG['host_os'] =~ /cygwin/ || !Etc.getpwuid(0).nil?)
end
```

4) Profit:

```bash
$ puppet --version
6.9.0
```
