### ISSUE TITLE
ffi 1.9.8 BuildError

### ISSUE THREAD

**Issue by marutosi** [ffi/ffi#418]
http://www.redmine.org/builds/logs/build_trunk_sqlite3_ruby-2.1_2415.html
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /var/lib/jenkins/ruby/ruby-2.1.5/bin/ruby extconf.rb 
checking for ffi_call() in -lffi... yes
checking for ffi_prep_closure()... yes
checking for ffi_raw_call()... yes
checking for ffi_prep_raw_closure()... yes
checking for rb_thread_blocking_region()... yes
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
checking for ffi_prep_cif_var()... yes
creating extconf.h
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling Types.c
compiling StructByReference.c
compiling Function.c
compiling StructLayout.c
compiling Call.c
compiling Buffer.c
compiling FunctionInfo.c
compiling MappedType.c
compiling MethodHandle.c
compiling Variadic.c
compiling ffi.c
compiling StructByValue.c
compiling Type.c
compiling DataConverter.c
compiling ArrayType.c
compiling Thread.c
compiling Platform.c
compiling ClosurePool.c
compiling Struct.c
compiling MemoryPointer.c
compiling Pointer.c
compiling DynamicLibrary.c
compiling LongDouble.c
compiling AbstractMemory.c
Assembler messages:
Fatal error: can't create AbstractMemory.o: No such file or directory
make: *** [AbstractMemory.o] Error 1

make failed, exit code 2

Gem files will remain installed in /var/lib/jenkins/ruby/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/ffi-1.9.8 for inspection.
Results logged to /var/lib/jenkins/ruby/ruby-2.1.5/lib/ruby/gems/2.1.0/extensions/x86-linux/2.1.0-static/ffi-1.9.8/gem_make.out
An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.
```

**Comment by marutosi** [comment]
Other environment passes.
http://www.redmine.org/builds/logs/build_trunk_mysql_ruby-2.2_2415.html

**Comment by marutosi** [comment]
Error:
http://www.redmine.org/builds/logs/build_trunk_mysql_ruby-1.9.3-p194_2415.html

**Comment by marutosi** [comment]
I cannot install **anytime** on Ruby 2.1 32bits on my CentOS6 64bits.

```
$ rvm install 2.1 --32
$ ruby --version
ruby 2.1.5p273 (2014-11-13 revision 48405) [i686-linux]
```

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /home/xxxx/.rvm/rubies/ruby-2.1.5/bin/ruby -r ./siteconf20150316-25753-13wfukr.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/xxxx/.rvm/rubies/ruby-2.1.5/bin/ruby
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/home/xxxx/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /home/xxxx/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:541:in `try_link0'
        from /home/xxxx/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:556:in `try_link'
        from /home/xxxx/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:642:in `block in try_ldflags'
        from /home/xxxx/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:635:in `with_ldflags'
        from /home/xxxx/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:641:in `try_ldflags'
        from /home/xxxx/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/mkmf.rb:1762:in `pkg_config'
        from extconf.rb:15:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/xxxx/.rvm/gems/ruby-2.1.5/gems/ffi-1.9.8 for inspection.
Results logged to /home/xxxx/.rvm/gems/ruby-2.1.5/extensions/x86-linux/2.1.0/ffi-1.9.8/gem_make.out
An error occurred while installing ffi (1.9.8), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.8'` succeeds before bundling.
```

**Comment by tduehr** [comment]
I can't reproduce this. Can you provide more context?

**Comment by marutosi** [comment]
I don't have **real** 32bit environment.
It seems timing problem.
http://www.redmine.org/builds/index.html

**Comment by marutosi** [comment]
I cannot reproduce on my real 32bit machine.
* ruby 2.0.0p598 (2014-11-13 revision 48408) [i686-linux]
* ruby 1.9.3p551 (2014-11-13 revision 48407) [i686-linux]

It seems Redmine CI server timing problem.

**Comment by davidimoore** [comment]
This was fixed for me when I used ruby 2.2.0.

The problem occurred on my machine when using ruby 2.2.1

**Comment by tduehr** [comment]
32bit linux? what distro?

**Comment by davidimoore** [comment]
3.16.0-33-generic #44~14.04.1-Ubuntu 
SMP  x86_64 x86_64 x86_64 GNU/Linux
