### ISSUE TITLE
Bad version match in ffi.rb

### ISSUE THREAD

**Issue by jamesrf999** [ffi/ffi#419]
Just a quick heads up that /2\.1/ matches ruby 2.2.1... Change to /^2\.1/

Thanks for ffi :)

**Comment by abargnesi** [comment]
Also worth noting that the pattern `2.1` is intended to match as a literal.

Escaping the period (`/^2\.1/`) or using `Regexp.escape` would be more accurate.

**Comment by abargnesi** [comment]
This leads to a load error when executing `require 'ffi'` on windows with Ruby 2.2.1.

```
C:\Ruby22>bin\irb
irb(main):001:0> require 'ffi'
126: The specified module could not be found.   - C:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x86-mingw32/lib/2.1/ffi_c.so
LoadError: cannot load such file -- ffi_c
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi.rb:19:in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi.rb:3:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby22/bin/irb:11:in `<main>'
irb(main):002:0> RUBY_VERSION
=> "2.2.1"
```

**Comment by abargnesi** [comment]
I fixed the patterns and rebuilt for x64-mingw32.

Output:

```text
C:\Users\abargnesi\Downloads>C:\Ruby22-x64\bin\gem install ffi-1.9.8-x64-mingw32.gem
Successfully installed ffi-1.9.8-x64-mingw32
Parsing documentation for ffi-1.9.8-x64-mingw32
Installing ri documentation for ffi-1.9.8-x64-mingw32
Done installing documentation for ffi after 1 seconds
1 gem installed

C:\Users\abargnesi\Downloads>C:\Ruby22-x64\bin\irb
irb(main):001:0> require 'ffi'
=> true
irb(main):002:0> FFI::Library
=> FFI::Library
```

**Comment by tduehr** [comment]
This stuff could probably work better... For now, merged the regex change.
