### ISSUE TITLE
Spec failures in ffi 1.9.8 (and 1.9.6)

### ISSUE THREAD

**Issue by graaff** [ffi/ffi#427]
I'm seeing the following spec failures with the released versions of ffi 1.9.6 and 1.9.8.

```
  1) Managed Struct should release memory properly
     Failure/Error: expect(PleaseReleaseMe).to receive(:release).at_least(loop_count-wiggle_room).times
       (<PleaseReleaseMe (class)>).release(*(any args))
           expected: at least 25 times with any arguments
           received: 0 times with any arguments
     # ./spec/ffi/managed_struct_spec.rb:61:in `block (2 levels) in <top (required)>'

  2) AutoPointer cleanup via default release method
     Failure/Error: expect(AutoPointerSubclass).to receive(:release).at_least(loop_count-wiggle_room).times
       (<AutoPointerSubclass (class)>).release(*(any args))
           expected: at least 25 times with any arguments
           received: 0 times with any arguments
     # ./spec/ffi/pointer_spec.rb:174:in `block (2 levels) in <top (required)>'

  3) AutoPointer cleanup when passed a proc
     Failure/Error: expect(AutoPointerTestHelper).to receive(:release).at_least(loop_count-wiggle_room).times
       (<AutoPointerTestHelper (class)>).release(*(any args))
           expected: at least 25 times with any arguments
           received: 0 times with any arguments
     # ./spec/ffi/pointer_spec.rb:194:in `block (2 levels) in <top (required)>'

  4) AutoPointer cleanup when passed a method
     Failure/Error: expect(AutoPointerTestHelper).to receive(:release).at_least(loop_count-wiggle_room).times
       (<AutoPointerTestHelper (class)>).release(*(any args))
           expected: at least 25 times with any arguments
           received: 0 times with any arguments
     # ./spec/ffi/pointer_spec.rb:204:in `block (2 levels) in <top (required)>
```

I guess these are all related to the same behavior of the AutoPointerTestHelper class.

I've tested with ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-linux] and ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

I noticed Travis passes all specs, so this may be related to something in our Gentoo Linux environment. For reference here is our downstream bug report: https://bugs.gentoo.org/show_bug.cgi?id=543842

**Comment by tduehr** [comment]
Those errors look like the result of an overloaded test system or the spec is failing for a similar environment problem/race condition. I'll look into it.

**Comment by zeha** [comment]
FTR, we're seeing these on Debian as well (otherwise idle test VM), our ruby is: ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]

**Comment by tduehr** [comment]
These are likely bad specs. Updating rspec to ~>3.0 causes consistent local failures.

**Comment by tduehr** [comment]
GC tests aren't likely to work predictably. These tests are bad. However, I'm not sure if they can be fixed meaningfully. @postmodern @enebo ideas?

**Comment by paddor** [comment]
Any updates on this?

**Comment by tduehr** [comment]
Nope, without a reliable way to get the garbage collector to run, there's no way to properly test the functionality.
