### ISSUE TITLE
LoadError on ruby installer 2.2.1 on windows + solution

### ISSUE THREAD

**Issue by graf0** [ffi/ffi#428]
I cannot load any libraray using ffi on ruby 2.2.1 on windows. I get following stacktrace:

```ruby
LoadError: cannot load such file -- ffi_c
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi.rb:19:in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi.rb:3:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.2/lib/win32/windows/structs.rb:1:in `<top (required)>
'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.2/lib/win32/eventlog.rb:2:in `require_relative'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/win32-eventlog-0.6.2/lib/win32/eventlog.rb:2:in `<top (required)>'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from (irb):2
        from C:/Ruby22/bin/irb:11:in `<main>'
```

Problem is in file ffi.rb in line 10 - you use there regexp /2\.1/ to match ruby version - and it matches, because ruby version is 2.2.1 :) So ffi tries to load .so file for 2.1 version of ruby, gets exception, tries to load ffi_c via plain require, without directory - and fails miserably!

Solution: just change all regexp to something like /^2\.1/ - then it works.

**Comment by tduehr** [comment]
This has been fixed on master.
