### ISSUE TITLE
Unable to build native extensions on Cygwin64

### ISSUE THREAD

**Issue by jawshooah** [ffi/ffi#433]
I'm having trouble installing this gem with Cygwin64. Below is the console output:

```
$ ruby --version
ruby 2.0.0p598 (2014-11-13) [x86_64-cygwin]

$ gem --version
2.3.0

$ rake --version
rake, version 10.4.2

$ rake install
which: no gmake in (/usr/local/bin:/usr/bin:/cygdrive/c/tools/ruby215/bin:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/OpenSSH/bin:/cygdrive/c/opscode/chef/bin:/cygdrive/c/ProgramData/chocolatey/bin:/cygdrive/c/Program Files (x86)/Git/cmd:/cygdrive/c/Program Files (x86)/vim/vim74:/cygdrive/c/tools/sysinternals:/:/cygdrive/c/GnuWin/bin)
[warn] YARD unavailable
>>> Installing ffi-1.9.8.gem ...
Building native extensions.  This could take a while...
ERROR:  Error installing pkg/ffi-1.9.8.gem:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby.exe extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/ruby
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/share/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/share/ruby/2.0.0/mkmf.rb:519:in `try_link0'
        from /usr/share/ruby/2.0.0/mkmf.rb:534:in `try_link'
        from /usr/share/ruby/2.0.0/mkmf.rb:620:in `block in try_ldflags'
        from /usr/share/ruby/2.0.0/mkmf.rb:613:in `with_ldflags'
        from /usr/share/ruby/2.0.0/mkmf.rb:619:in `try_ldflags'
        from /usr/share/ruby/2.0.0/mkmf.rb:1725:in `pkg_config'
        from extconf.rb:15:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/vagrant/.gem/ruby/gems/ffi-1.9.8 for inspection.
Results logged to /home/vagrant/.gem/ruby/extensions/x86_64-cygwin/ffi-1.9.8/gem_make.out
!!! Command failed: gem install -q pkg/ffi-1.9.8.gem
```

And here is `mkmf.log`

```
"gcc -o conftest.exe -I/usr/include/ruby-2.0.0 -I/usr/include/ruby-2.0.0/ruby/backward -I/usr/include/ruby-2.0.0 -I.    -ggdb -O2 -pipe -Wimplicit-function-declaration   conftest.c  -L. -L/usr/lib -lffi     -lruby200  -lpthread -lrt -ldl -lcrypt  "
/usr/lib/gcc/x86_64-pc-cygwin/4.9.2/../../../../x86_64-pc-cygwin/bin/ld: cannot find -lcrypt
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by tduehr** [comment]
`ld: cannot find -lcrypt`

You have libcrypt installed in cygwin?

**Comment by jawshooah** [comment]
Yup:

```
$ apt-cyg install crypt
Package crypt is already installed, skipping
```

**Comment by jawshooah** [comment]
I appear to be an idiot. `libcrypt-devel` was what I needed. Builds fine now, thanks!
