### ISSUE TITLE
ffi-1.9.9 segfaults on windows

### ISSUE THREAD

**Issue by joshcooper** [ffi/ffi#440]
Windows 2008R2, happens with 32 and 64-bit ruby:

```
C:\work\ffitest>type Gemfile
source 'https://rubygems.org'
gem 'ffi', '~> 1.9.6'

C:\work\ffitest>bundle install --path .bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing ffi 1.9.9
Using bundler 1.9.9
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into ./.bundle.

C:\work\ffitest>ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]

C:\work\ffitest>type ffitest.rb
require 'ffi'

module FFITest
  extend FFI::Library
  typedef :uintptr_t, :handle
  ffi_lib :kernel32
  ffi_convention :stdcall
  attach_function :GetCurrentProcess, [], :handle
end

C:\work\ffitest>bundle exec ruby ffitest.rb
C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/library.rb:263: [BUG] Segmentation fault
ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0005 p:---- s:0030 e:000029 CFUNC  :attach
c:0004 p:0267 s:0025 e:000024 METHOD C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/library.rb:26
3
c:0003 p:0054 s:0006 e:000005 CLASS  ffitest.rb:8
c:0002 p:0017 s:0004 E:0003c8 EVAL   ffitest.rb:3 [FINISH]
c:0001 p:0000 s:0002 E:000818 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
ffitest.rb:3:in `<main>'
ffitest.rb:8:in `<module:FFITest>'
C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/library.rb:263:in `attach_function'
C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/library.rb:263:in `attach'

-- C level backtrace information -------------------------------------------
C:\Windows\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0xa) [0x000000007795135A]
C:\Windows\system32\KERNELBASE.dll(WaitForSingleObjectEx+0x9c) [0x000007FEFDA410DC]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_bugreport+0xa4) [0x000000006B4177C4]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_name_err_mesg_new+0x841) [0x000000006B2C97F1]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_bug+0x45) [0x000000006B2CA535]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_check_safe_str+0x381) [0x000000006B398FE1]
 [0x0000000000401A85]
C:\Windows\SYSTEM32\ntdll.dll(_C_specific_handler+0x9c) [0x00000000779185A8]
C:\Windows\SYSTEM32\ntdll.dll(RtlDecodePointer+0xbd) [0x0000000077929D0D]
C:\Windows\SYSTEM32\ntdll.dll(RtlUnwindEx+0xbbf) [0x00000000779191AF]
C:\Windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x0000000077951278]
C:\work\ffitest\.bundle\ruby\2.1.0\gems\ffi-1.9.9-x64-mingw32\lib\2.1\ffi_c.so(Init_ffi_c+0x9ad1) [0x00000000657D3B41]
C:\work\ffitest\.bundle\ruby\2.1.0\gems\ffi-1.9.9-x64-mingw32\lib\2.1\ffi_c.so(Init_ffi_c+0x9f78) [0x00000000657D3FE8]
C:\work\ffitest\.bundle\ruby\2.1.0\gems\ffi-1.9.9-x64-mingw32\lib\2.1\ffi_c.so(Init_ffi_c+0x2a32) [0x00000000657CCAA2]
 [0x00000000657C95C4]
C:\work\ffitest\.bundle\ruby\2.1.0\gems\ffi-1.9.9-x64-mingw32\lib\2.1\ffi_c.so(Init_ffi_c+0x2a81) [0x00000000657CCAF1]
C:\work\ffitest\.bundle\ruby\2.1.0\gems\ffi-1.9.9-x64-mingw32\lib\2.1\ffi_c.so(Init_ffi_c+0x2dd) [0x00000000657CA34D]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_error_arity+0x1c6) [0x000000006B402476]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_f_send+0x5c1) [0x000000006B40F4D1]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_localjump_error+0x1618) [0x000000006B406F48]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_vm_localjump_error+0x5a9d) [0x000000006B40B3CD]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_iseq_eval_main+0x1d0) [0x000000006B4142A0]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(rb_check_copyable+0x304a) [0x000000006B2CF30A]
c:\ruby21-x64\bin\x64-msvcrt-ruby210.dll(ruby_run_node+0x51) [0x000000006B2D2221]
 [0x0000000000402D14]
 [0x00000000004013D7]
 [0x00000000004014F8]
C:\Windows\system32\kernel32.dll(BaseThreadInitThunk+0xd) [0x00000000776F652D]

-- Other runtime information -----------------------------------------------

* Loaded script: ffitest.rb

* Loaded features:

    0 enumerator.so
    1 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/enc/encdb.so
    2 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/enc/iso_8859_1.so
    3 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/enc/trans/transdb.so
    4 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/rbconfig.rb
    5 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/compatibility.rb
    6 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/defaults.rb
    7 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/deprecate.rb
    8 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/errors.rb
    9 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/version.rb
   10 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/requirement.rb
   11 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/platform.rb
   12 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/basic_specification.rb
   13 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/stub_specification.rb
   14 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/util/stringio.rb
   15 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/specification.rb
   16 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/exceptions.rb
   17 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/defaults/operating_system.rb
   18 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_gem.rb
   19 thread.rb
   20 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/thread.so
   21 c:/ruby21-x64/lib/ruby/2.1.0/monitor.rb
   22 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb
   23 c:/ruby21-x64/lib/ruby/2.1.0/rubygems.rb
   24 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/pathname.so
   25 c:/ruby21-x64/lib/ruby/2.1.0/pathname.rb
   26 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/constants.rb
   27 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/dependency.rb
   28 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/path_support.rb
   29 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/io/console.so
   30 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/user_interaction.rb
   31 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/etc.so
   32 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/config_file.rb
   33 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/ext/build_error.rb
   34 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/ext/builder.rb
   35 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/ext/configure_builder.rb
   36 c:/ruby21-x64/lib/ruby/2.1.0/fileutils.rb
   37 c:/ruby21-x64/lib/ruby/2.1.0/delegate.rb
   38 c:/ruby21-x64/lib/ruby/2.1.0/tmpdir.rb
   39 c:/ruby21-x64/lib/ruby/2.1.0/tempfile.rb
   40 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/ext/ext_conf_builder.rb
   41 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/ext/rake_builder.rb
   42 c:/ruby21-x64/lib/ruby/2.1.0/optparse.rb
   43 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/command.rb
   44 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/ext/cmake_builder.rb
   45 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/ext.rb
   46 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/rubygems_integration.rb
   47 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/current_ruby.rb
   48 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb
   49 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/gem_path_manipulation.rb
   50 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/gem_helpers.rb
   51 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/match_platform.rb
   52 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/rubygems_ext.rb
   53 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/version.rb
   54 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler.rb
   55 c:/ruby21-x64/lib/ruby/2.1.0/uri/common.rb
   56 c:/ruby21-x64/lib/ruby/2.1.0/uri/generic.rb
   57 c:/ruby21-x64/lib/ruby/2.1.0/uri/ftp.rb
   58 c:/ruby21-x64/lib/ruby/2.1.0/uri/http.rb
   59 c:/ruby21-x64/lib/ruby/2.1.0/uri/https.rb
   60 c:/ruby21-x64/lib/ruby/2.1.0/uri/ldap.rb
   61 c:/ruby21-x64/lib/ruby/2.1.0/uri/ldaps.rb
   62 c:/ruby21-x64/lib/ruby/2.1.0/uri/mailto.rb
   63 c:/ruby21-x64/lib/ruby/2.1.0/uri.rb
   64 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/settings.rb
   65 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/digest.so
   66 c:/ruby21-x64/lib/ruby/2.1.0/digest.rb
   67 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/digest/sha1.so
   68 c:/ruby21-x64/lib/ruby/2.1.0/set.rb
   69 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/definition.rb
   70 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/dependency.rb
   71 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/ruby_dsl.rb
   72 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/dsl.rb
   73 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/source_list.rb
   74 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/source.rb
   75 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/socket.so
   76 c:/ruby21-x64/lib/ruby/2.1.0/socket.rb
   77 c:/ruby21-x64/lib/ruby/2.1.0/timeout.rb
   78 c:/ruby21-x64/lib/ruby/2.1.0/net/protocol.rb
   79 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/zlib.so
   80 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/stringio.so
   81 c:/ruby21-x64/lib/ruby/2.1.0/net/http/exceptions.rb
   82 c:/ruby21-x64/lib/ruby/2.1.0/net/http/header.rb
   83 c:/ruby21-x64/lib/ruby/2.1.0/net/http/generic_request.rb
   84 c:/ruby21-x64/lib/ruby/2.1.0/net/http/request.rb
   85 c:/ruby21-x64/lib/ruby/2.1.0/net/http/requests.rb
   86 c:/ruby21-x64/lib/ruby/2.1.0/net/http/response.rb
   87 c:/ruby21-x64/lib/ruby/2.1.0/net/http/responses.rb
   88 c:/ruby21-x64/lib/ruby/2.1.0/net/http/proxy_delta.rb
   89 c:/ruby21-x64/lib/ruby/2.1.0/net/http/backward.rb
   90 c:/ruby21-x64/lib/ruby/2.1.0/net/http.rb
   91 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/date_core.so
   92 c:/ruby21-x64/lib/ruby/2.1.0/date/format.rb
   93 c:/ruby21-x64/lib/ruby/2.1.0/date.rb
   94 c:/ruby21-x64/lib/ruby/2.1.0/time.rb
   95 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/request.rb
   96 c:/ruby21-x64/lib/ruby/2.1.0/cgi/core.rb
   97 c:/ruby21-x64/lib/ruby/2.1.0/cgi/util.rb
   98 c:/ruby21-x64/lib/ruby/2.1.0/cgi/cookie.rb
   99 c:/ruby21-x64/lib/ruby/2.1.0/cgi.rb
  100 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/uri_formatter.rb
  101 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/fcntl.so
  102 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/openssl.so
  103 c:/ruby21-x64/lib/ruby/2.1.0/openssl/bn.rb
  104 c:/ruby21-x64/lib/ruby/2.1.0/openssl/cipher.rb
  105 c:/ruby21-x64/lib/ruby/2.1.0/openssl/config.rb
  106 c:/ruby21-x64/lib/ruby/2.1.0/openssl/digest.rb
  107 c:/ruby21-x64/lib/ruby/2.1.0/openssl/x509.rb
  108 c:/ruby21-x64/lib/ruby/2.1.0/openssl/buffering.rb
  109 c:/ruby21-x64/lib/ruby/2.1.0/openssl/ssl.rb
  110 c:/ruby21-x64/lib/ruby/2.1.0/openssl.rb
  111 c:/ruby21-x64/lib/ruby/2.1.0/securerandom.rb
  112 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/fiddle.so
  113 c:/ruby21-x64/lib/ruby/2.1.0/fiddle/function.rb
  114 c:/ruby21-x64/lib/ruby/2.1.0/fiddle/closure.rb
  115 c:/ruby21-x64/lib/ruby/2.1.0/fiddle.rb
  116 c:/ruby21-x64/lib/ruby/2.1.0/fiddle/value.rb
  117 c:/ruby21-x64/lib/ruby/2.1.0/fiddle/pack.rb
  118 c:/ruby21-x64/lib/ruby/2.1.0/fiddle/struct.rb
  119 c:/ruby21-x64/lib/ruby/2.1.0/fiddle/cparser.rb
  120 c:/ruby21-x64/lib/ruby/2.1.0/fiddle/import.rb
  121 c:/ruby21-x64/lib/ruby/2.1.0/win32/importer.rb
  122 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/enc/utf_16le.so
  123 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/enc/trans/utf_16_32.so
  124 c:/ruby21-x64/lib/ruby/2.1.0/win32/registry.rb
  125 c:/ruby21-x64/lib/ruby/2.1.0/win32/resolv.rb
  126 c:/ruby21-x64/lib/ruby/2.1.0/resolv.rb
  127 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/remote_fetcher.rb
  128 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/text.rb
  129 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/name_tuple.rb
  130 c:/ruby21-x64/lib/ruby/2.1.0/rubygems/spec_fetcher.rb
  131 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/source/rubygems.rb
  132 c:/ruby21-x64/lib/ruby/2.1.0/x64-mingw32/strscan.so
  133 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/source/path.rb
  134 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/source/git.rb
  135 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/lockfile_parser.rb
  136 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/lazy_specification.rb
  137 c:/ruby21-x64/lib/ruby/2.1.0/tsort.rb
  138 c:/ruby21-x64/lib/ruby/2.1.0/forwardable.rb
  139 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/spec_set.rb
  140 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/environment.rb
  141 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/runtime.rb
  142 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/dep_proxy.rb
  143 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/index.rb
  144 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/remote_specification.rb
  145 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/endpoint_specification.rb
  146 c:/ruby21-x64/lib/ruby/gems/2.1.0/gems/bundler-1.9.9/lib/bundler/setup.rb
  147 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/2.1/ffi_c.so
  148 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/platform.rb
  149 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/types.rb
  150 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/library.rb
  151 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/errno.rb
  152 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/pointer.rb
  153 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/memorypointer.rb
  154 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/struct_layout_builder.rb
  155 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/struct.rb
  156 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/union.rb
  157 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/managedstruct.rb
  158 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/callback.rb
  159 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/io.rb
  160 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/autopointer.rb
  161 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/variadic.rb
  162 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/enum.rb
  163 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi/ffi.rb
  164 C:/work/ffitest/.bundle/ruby/2.1.0/gems/ffi-1.9.9-x64-mingw32/lib/ffi.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

If I pin to 1.9.8, it does not happen:

```
C:\work\ffitest>bundle update
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing ffi 1.9.8 (was 1.9.9)
Using bundler 1.9.9
Bundle updated!

C:\work\ffitest>bundle exec ruby ffitest.rb
```

**Comment by jaym** [comment]
reverting https://github.com/ffi/ffi/commit/30808b769e4f0656092b7b3185c2f4149211d6eb fixes the problem

**Comment by ksubrama** [comment]
@jaym narrowed it down.

https://github.com/ffi/ffi/blob/83c53aa8d51a24f6f7e2f866eeb1649484f57a22/ext/ffi_c/libffi/src/prep_cif.c#L105

ffi_prep_cif holds onto methodHandleParamTypes in mh_cif->arg_types and since mh_cif has static scope, we're accessing stale memory..

**Comment by BinaryTweedDeej** [comment]
+1, getting the same problem

Thanks for looking into it

**Comment by Xetoris** [comment]
+1, Ran into this today as well.

**Comment by joshcooper** [comment]
@tduehr would it possible to yank the gem from rubygems.org (unless it's faster to merge this PR and publish 1.9.10?)

**Comment by TheHatz** [comment]
I am experiencing this exact same issues on the same platform (Windows Server 2012 R2). I was able to back the version to 1.9.8 and got my tests running again. Only experiencing this on windows.

**Comment by bmaynard1991** [comment]
Same as above. 1.9.8 works 1.9.9 does not. Windows 7

**Comment by Iristyle** [comment]
+1 to yanking `1.9.9` gem if possible

**Comment by zl4bv** [comment]
Same as above. Experienced on both Windows Server 2008 R2 and Windows Server 2012.

ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]

Another stacktrace here: https://gist.github.com/zl4bv/328a1d06cd92fe061180#file-stacktrace

**Comment by davengeo** [comment]
Same problem with a fresh ruby 2.2.2 and windows7, after installing watir-webdriver

irb>require 'watir-webdriver'

triggers the segmentation fault

gem uninstall ffi v1.9.9
 and then
gem install ffi v1.9.8 solves the problem

**Comment by stakach** [comment]
Also seeing this problem

**Comment by joshcooper** [comment]
Thanks @tduehr! Could you also push platform-specific gems for `x64-mingw32`, `x86-mingw32`, and `java` like was done for 1.9.9?
