### ISSUE TITLE
Error with version 1.9.12 with Ruby 2.2.4 on Windows-x64

### ISSUE THREAD

**Issue by karensg** [ffi/ffi#510]
Since 1.9.11 update I get an error with Rest-client gem. 1.9.10 works fine. Any ideas what is going wrong?

```
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in requir
e': There was an error while trying to load the gem 'rest-client'. (Bundler::GemRequireError)
Gem Load Error is: no implicit conversion of Symbol into String
Backtrace for gem load error is:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:128:in `+'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:128:in `block (3 levels) in ffi_lib'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:127:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:127:in `find'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:127:in `rescue in block (2 levels) in f
fi_lib'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:111:in `block (2 levels) in ffi_lib'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:110:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:110:in `block in ffi_lib'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:100:in `map'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ffi-1.9.12-x64-mingw32/lib/ffi/library.rb:100:in `ffi_lib'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0-x64-mingw32/lib/restclient/windows/root_certs.rb:85:in `<class:
RootCerts>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0-x64-mingw32/lib/restclient/windows/root_certs.rb:12:in `<top (r
equired)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0-x64-mingw32/lib/restclient/windows.rb:7:in `require_relative'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0-x64-mingw32/lib/restclient/windows.rb:7:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0-x64-mingw32/lib/restclient.rb:16:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rest-client-1.8.0-x64-mingw32/lib/rest-client.rb:2:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
C:/Users/Karens/Documents/GitHub/project-backend/config/application.rb:7:in `<top (required)>'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in server'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:85:in `block (2 levels) in req
uire'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:81:in `block in require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
        from C:/Users/Karens/Documents/GitHub/project-backend/config/application.rb:7:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:78:in `block in
server'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_comma
nd!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by richpeck** [comment]
+1

**Comment by jroger2908** [comment]
+1

**Comment by mwrock** [comment]
this is fixed by #508 so this should clear up once that is released

**Comment by jeremydyoung** [comment]
Thanks @tduehr , I tested this with the 1.9.13 release and all looks good.

**Comment by karensg** [comment]
Same here. Thanks
