### ISSUE TITLE
Unable to register mcollective service which uses ffi gem

### ISSUE THREAD

**Issue by rakare2015** [ffi/ffi#561]
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.9.10-x86-mingw32/lib/1.9/ffi_c.so: [BUG] Segmentation fault
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0018 p:-11423312 s:0069 b:0069 l:000068 d:000068 TOP
c:0017 p:---- s:0067 b:0067 l:000066 d:000066 CFUNC  :require
c:0016 p:0036 s:0063 b:0063 l:000062 d:000062 METHOD C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36
c:0015 p:0119 s:0056 b:0056 l:000055 d:000055 TOP    C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.9.10-x86-mingw32/lib/ffi.
rb:4
c:0014 p:---- s:0054 b:0054 l:000053 d:000053 FINISH
c:0013 p:---- s:0052 b:0052 l:000051 d:000051 CFUNC  :require
c:0012 p:0036 s:0048 b:0048 l:000047 d:000047 METHOD C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36
c:0011 p:0011 s:0041 b:0041 l:000040 d:000040 TOP    C:/Ruby193/lib/ruby/gems/1.9.1/gems/win32-service-0.8.7/lib/win32/w
indows/helper.rb:1
c:0010 p:---- s:0039 b:0039 l:000038 d:000038 FINISH
c:0009 p:---- s:0037 b:0037 l:000036 d:000036 CFUNC  :require_relative
c:0008 p:0011 s:0033 b:0033 l:000032 d:000032 TOP    C:/Ruby193/lib/ruby/gems/1.9.1/gems/win32-service-0.8.7/lib/win32/s
ervice.rb:1
c:0007 p:---- s:0031 b:0031 l:000030 d:000030 FINISH
c:0006 p:---- s:0029 b:0029 l:000028 d:000028 CFUNC  :require
c:0005 p:0089 s:0025 b:0025 l:000021 d:000024 BLOCK  C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60
c:0004 p:0158 s:0022 b:0022 l:000021 d:000021 METHOD C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35
c:0003 p:0462 s:0015 b:0015 l:0008ec d:000108 EVAL   C:/mcollective/bin/service_manager.rb:60
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0008ec d:0008ec TOP

-- Ruby level backtrace information ----------------------------------------
C:/mcollective/bin/service_manager.rb:60:in `<main>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/win32-service-0.8.7/lib/win32/service.rb:1:in `<top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/win32-service-0.8.7/lib/win32/service.rb:1:in `require_relative'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/win32-service-0.8.7/lib/win32/windows/helper.rb:1:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/ffi-1.9.10-x86-mingw32/lib/ffi.rb:4:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'

-- C level backtrace information -------------------------------------------
===========================================================================================

Following gems are installed:

*** LOCAL GEMS ***

bigdecimal (1.1.0)
facter (2.4.6 x86-mingw32)
ffi (1.9.10 x64-mingw32 x86-mingw32)
ffi-win32-extensions (1.0.2)
io-console (0.3)
json (1.5.5)
minitest (2.5.1)
rake (0.9.2.2)
rdoc (3.9.5)
stomp (1.4.0)
sys-admin (1.6.4)
win32-api (1.5.1 universal-mingw32)
win32-dir (0.4.9)
win32-process (0.5.5)
win32-security (0.2.5)
win32-service (0.8.7)
win32console (1.3.2 x86-mingw32)
windows-api (0.4.2)
windows-pr (1.2.3)

Also I tried to remove the gem ffi-x86-mingw32 since the server is 64bit but that also didn't help and it gives below error,

=========================
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find ffi (>= 0) amongst [bigdeci
mal-1.1.0, facter-2.4.6-x86-mingw32, ffi-1.9.10-x64-mingw32, ffi-win32-extensions-1.0.2, io-console-0.3, json-1.5.5, min
itest-2.5.1, rake-0.9.2.2, rdoc-3.9.5, stomp-1.4.0, sys-admin-1.6.4, win32-api-1.5.1-universal-mingw32, win32-dir-0.4.9,
 win32-process-0.5.5, win32-security-0.2.5, win32-service-0.8.7, win32console-1.3.2-x86-mingw32, windows-api-0.4.2, wind
ows-pr-1.2.3] (Gem::LoadError)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:778:in `block in activate_dependencies'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:767:in `each'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:767:in `activate_dependencies'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:751:in `activate'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:212:in `rescue in try_activate'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:209:in `try_activate'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:59:in `rescue in require'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from C:/mcollective/bin/service_manager.rb:60:in `<main>'
==============================

**Comment by tduehr** [comment]
Has this been resolved in a newer version of FFI? Can you provide code to duplicate this?

**Comment by rakare2015** [comment]
Am unable to test with the newer version since the its requires ruby version 2.0 and higher but I have ruby version 1.9.3 installed. Can you please patch the fix on the version 1.9.10 and I will test the same.

**Comment by tduehr** [comment]
Support for 1.9.3 has not yet been dropped by us. You should be able to install the latest version of FFI.

**Comment by rakare2015** [comment]
Nope. Looks like 1.9.3 has been dropped and am getting below error message while installing latest gem.

PS C:\> gem install --local C:\temp\ffi-1.9.18-x86-mingw32.gem
ERROR:  Error installing C:\temp\ffi-1.9.18-x86-mingw32.gem:
        ffi requires Ruby version < 2.5, >= 2.0.
PS C:\>
PS C:\> ruby --version
ruby 1.9.3p551 (2014-11-13) [i386-mingw32]
PS C:\>

**Comment by tduehr** [comment]
Try a slightly older one

**Comment by rakare2015** [comment]
I was able to install 1.9.14 only and all later versions required ruby version < 2.5, >= 2.0. When I install 1.9.14 getting the same error which mentioned initially

**Comment by tduehr** [comment]
I just noticed this... you're using a 32bit ruby on a 64bit system. Is the library you're trying to load also 32bit?

**Comment by rakare2015** [comment]
My library supports both 32 and 64bit. I uninstalled and installed 64bit and getting below error now,

C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find facter (>= 0) amongst [bigd
ecimal-1.1.0, facter-2.4.6-x64-mingw32, ffi-1.9.14-x64-mingw32, io-console-0.3, json-1.5.5, minitest-2.5.1, rake-0.9.2.2
, rdoc-3.9.5, stomp-1.4.0, sys-admin-1.6.4, win32-api-1.5.1-universal-mingw32, win32-dir-0.4.9, win32-process-0.5.5, win
32-security-0.2.5, win32-service-0.8.7, win32console-1.3.2-x86-mingw32, windows-api-0.4.2, windows-pr-1.2.3] (Gem::LoadE
rror)
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems.rb:1231:in `gem'
        from C:/Ruby193/bin/facter:22:in `<main>'
PS C:\>


I have installed this 32bit only on around 5000 servers and everywhere it went fine except 40+ servers which are giving such error.

**Comment by tduehr** [comment]
Library, ruby and gem must match in word size. In general, 64bit would probably work better.
