### ISSUE TITLE
Starting Rails development server not working on Alpine 3.5

### ISSUE THREAD

**Issue by agentS** [ffi/ffi#578]
Hi,

I successfully set up my rails development environment on Alpine Linux 3.5.2. I installed `libffi-dev` in order to install the `ffi` gem. However, on starting the development with the command `bin/rails server` I get the following error: 

    /usr/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:277:in `attach': `t��z (RuntimeError)
        from /usr/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/lib/ffi/library.rb:277:in `attach_function'

I extended the instructions in this [Dockerfile](https://github.com/rheinwein/alpine-rails/blob/master/Dockerfile). The tofu changes when executing the command again. The same applies when starting the Jekyll development server, although I think they both use Puma.

Thanks for your help!

**Comment by tduehr** [comment]
Can you supply the full stack trace?

What are you adding to that Dockerfile that depends on FFI?

**Comment by PichetGoulu** [comment]
Hi,

I have the same error on Alpine 3.6.2 using the 'virthardened' kernel (`4.9.32-0-virthardened`).
But it works fine with the 'vanilla' kernel (`4.9.33`)

I'm using Ruby 2.4 (`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux-musl]`) and libffi 1.9.18

The stack trace is the same as @agentS 
```
Exiting
/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:277:in `attach': �_^Ic (RuntimeError)
	from /usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:277:in `attach_function'
	from /usr/lib/ruby/gems/2.4.0/gems/rb-inotify-0.9.7/lib/rb-inotify/native.rb:24:in `<module:Native>'
	from /usr/lib/ruby/gems/2.4.0/gems/rb-inotify-0.9.7/lib/rb-inotify/native.rb:9:in `<module:INotify>'
	from /usr/lib/ruby/gems/2.4.0/gems/rb-inotify-0.9.7/lib/rb-inotify/native.rb:3:in `<top (required)>'
[...]
```

Using strace, i can see a mprotect() error
```
lstat("/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/enum.rb", {st_mode=S_IFREG|0644, st_size=5103, ...}) = 0
madvise(0x6de0fe32000, 192512, MADV_DONTNEED) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x6702e39ca000
mprotect(0x6702e39ca000, 4096, PROT_READ|PROT_EXEC) = -1 EACCES (Permission denied)
munmap(0x6702e39ca000, 4096)            = 0
madvise(0x6de0fe36000, 356352, MADV_DONTNEED) = 0
write(1, "Exiting", 7)                  = 7
write(1, "\n", 1)                       = 1
writev(2, [{iov_base="", iov_len=0}, {iov_base="/usr/lib/ruby/gems/2.4.0/gems/ff"..., iov_len=75}], 2/usr/lib/ruby/gems/2.4.0/gems/ffi-1.9.18/lib/ffi/library.rb:277:in `attach') = 75
```

**Comment by berney** [comment]
This still happens in Alpine 3.6, as you can see in the strace above it maps the memory as RW and then tries to update the permissions to RX, this call fails and ruby dies.

A quick workaround is to using `paxctl` to disable the mprotect protection by doing

```
apk add paxctl
paxctl -cm $(command -v ruby)
paxctl -v $(command -v ruby)
```

You should see ruby with the flags: -

```
PaX control v0.9
Copyright 2004,2005,2006,2007,2009,2010,2011,2012,2014 PaX Team <pageexec@freemail.hu>

- PaX flags: -----m-x-e-- [/usr/bin/ruby]
        MPROTECT is disabled
        RANDEXEC is disabled
        EMUTRAMP is disabled
```

After this weakening of security, `ruby` / `libffi` should run without `mprotect()` failing.
