### ISSUE TITLE
runtime: out of memory: cannot allocate 93839024062464-byte block (1048576 in use) fatal error: out of memory

### ISSUE THREAD

**Issue by joshkestenberg** [ffi/ffi#585]
Is it possible that any operation I'm trying to achieve requires this much RAM? 

I'm trying to call a go function from ruby that opens a text file, creates and opens a json file, renders and opens a modified text file from the initial text file, processes the modified text file and renders go structs from it, converts those go structs to json, and writes the json to the created json file.

When I try to call that function from ruby via FFI, I get: 

`runtime: out of memory: cannot allocate 93839024062464-byte block (1048576 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x7f7f3703f667, 0xd)
	/usr/lib/go-1.8/src/runtime/panic.go:596 +0x97
runtime.largeAlloc(0x555899b1e007, 0x7f7f37317500, 0xc420016140)
	/usr/lib/go-1.8/src/runtime/malloc.go:797 +0x111
runtime.mallocgc.func1()
	/usr/lib/go-1.8/src/runtime/malloc.go:690 +0x40
runtime.systemstack(0x7ffc1ecc2d78)
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:327 +0x72
runtime.mstart()
	/usr/lib/go-1.8/src/runtime/proc.go:1132

goroutine 17 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:281 fp=0xc4200448f8 sp=0xc4200448f0
runtime.mallocgc(0x555899b1e007, 0x0, 0x7f7f372ff200, 0x7f7f38bbd000)
	/usr/lib/go-1.8/src/runtime/malloc.go:691 +0x942 fp=0xc420044998 sp=0xc4200448f8
runtime.rawstring(0x555899b1e007, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/runtime/string.go:237 +0x87 fp=0xc4200449c8 sp=0xc420044998
runtime.rawstringtmp(0x0, 0x555899b1e007, 0x7f7f3725a598, 0x7f7f3725a100, 0x7f7f37270560, 0x7f7f372592e7, 0x7f7f372748a0)
	/usr/lib/go-1.8/src/runtime/string.go:107 +0x7a fp=0xc420044a08 sp=0xc4200449c8
runtime.concatstrings(0x0, 0xc420044ae8, 0x5, 0x5, 0xc420016140, 0xc420022000)
	/usr/lib/go-1.8/src/runtime/string.go:46 +0xfd fp=0xc420044aa0 sp=0xc420044a08
runtime.concatstring5(0x0, 0x7f7f3703e3c0, 0x4, 0x7f7f3703e160, 0x1, 0x555899b1e068, 0x555899b1dff0, 0x7f7f3703e19c, 0x2, 0x7f7f3703fcd0, ...)
	/usr/lib/go-1.8/src/runtime/string.go:67 +0x49 fp=0xc420044ae0 sp=0xc420044aa0
os.(*PathError).Error(0xc4200143c0, 0x7f7f3728e180, 0xc4200a6000)
	/usr/lib/go-1.8/src/os/error.go:27 +0xad fp=0xc420044b58 sp=0xc420044ae0
fmt.(*pp).handleMethods(0xc4200a6000, 0xc400000076, 0x7f7f38c19001)
	/usr/lib/go-1.8/src/fmt/print.go:590 +0x192 fp=0xc420044be8 sp=0xc420044b58
fmt.(*pp).printArg(0xc4200a6000, 0x7f7f37272580, 0xc4200143c0, 0x7f7f00000076)
	/usr/lib/go-1.8/src/fmt/print.go:679 +0x1a2 fp=0xc420044c70 sp=0xc420044be8
fmt.(*pp).doPrint(0xc4200a6000, 0xc420044e30, 0x1, 0x1)
	/usr/lib/go-1.8/src/fmt/print.go:1126 +0xf6 fp=0xc420044d00 sp=0xc420044c70
fmt.Sprint(0xc420044e30, 0x1, 0x1, 0x0, 0x7f7f372ee400)
	/usr/lib/go-1.8/src/fmt/print.go:232 +0x58 fp=0xc420044d58 sp=0xc420044d00
log.Fatal(0xc420044e30, 0x1, 0x1)
	/usr/lib/go-1.8/src/log/log.go:302 +0x41 fp=0xc420044d98 sp=0xc420044d58
main.reader(0x555899b1e068, 0x555899b1dff0, 0x0, 0x0, 0xc420096048, 0xc4200007e0)
	/home/josh/gocode/src/github.com/joshkestenberg/t-logs/reader.go:208 +0xb9 fp=0xc420044e50 sp=0xc420044d98
main._cgoexpwrap_498a7866c118_reader(0x555899b1e068, 0x555899b1dff0, 0x0, 0x0, 0x0, 0x0)
	command-line-arguments/_obj/_cgo_gotypes.go:48 +0x90 fp=0xc420044e90 sp=0xc420044e50
runtime.call64(0x0, 0x7ffc1ecc2dc8, 0x7ffc1ecc2e70, 0x30)
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:515 +0x4a fp=0xc420044ee0 sp=0xc420044e90
runtime.cgocallbackg1(0x0)
	/usr/lib/go-1.8/src/runtime/cgocall.go:301 +0x1a1 fp=0xc420044f58 sp=0xc420044ee0
runtime.cgocallbackg(0x0)
	/usr/lib/go-1.8/src/runtime/cgocall.go:184 +0x86 fp=0xc420044fc0 sp=0xc420044f58
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:767 +0x71 fp=0xc420044fe0 sp=0xc420044fc0
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420044fe8 sp=0xc420044fe0

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1
Aborted (core dumped)`

My ruby code looks like this: 

`require 'ffi'

module Reader
  extend FFI::Library
  ffi_lib './reader.so'

  attach_function :reader, [:string, :string], :string

end

print Reader.reader("tendermint.log", "tendermint.json")`

**Comment by joshkestenberg** [comment]
My various go functions return go data types, such as *os.File, struct, []struct, so I'm attempting to keep all those return values within the 'reader' function, processing them as inputs to the appropriate functions called in the necessary order, and only returning a string in the event that the entire function executes.

The go function looks like this: 

```
func reader(logPath string, jsonName string) string {
	file, err := OpenLog(logPath) //returns a pointer to a file
	if err != nil {
		log.Fatal(err)
	}

	jsonLog, err := InitJSON(jsonName) //returns a pointer to a file
	if err != nil {
		log.Fatal(err)
	}

	renderFile, err := RenderDoc(file) //returns a pointer to a file

	entries, err := UnmarshalLines(1, 60000, renderFile) //returns an array of go structs
	if err != nil {
		log.Fatal(err)
	}

	err = MarshalJSON(entries, jsonLog) //marshals go structs to json and writes to json file
	if err != nil {
		log.Fatal(err)
	}

	return "No errors"
}
```

**Comment by tduehr** [comment]
Most likely that's a bug in your go code. As I doubt you have anything in memory at that point either. Can you provide a link to the rest of your code?

**Comment by wade-welles** [comment]
I have this same issue, it works with no parameters being passed, it works with `int` parameter type, but it fails when trying to pass `string` type. So the issue is specifically related to passing `string` data type to the CGo function.

**Comment by wade-welles** [comment]
This is because you can not work with Go strings directly, they are an abstraction. You need to pass in strings as `*C.Char` type, I wrote a very simple example to help understand:

```
//export hello
func hello(cstr *C.char) {
	fmt.Printf("hello %v\n", C.GoString(cstr))
}
```
You covert using the GoString function and use the CString function in the return statement if you want a string as a return argument.

**Comment by wade-welles** [comment]
I discovered one other way to do this that makes it even easier, because it does let you receive Go `string` in the parameter. 

```
module Go
  extend FFI::Library
  ffi_lib './go.so'

  # define class GoString to map:
  # C type struct { const char *p; GoInt n; }
  class GoString < FFI::Struct
    layout :p,     :pointer,
           :len,   :long_long
    def initialize(str) 
      self[:p] = FFI::MemoryPointer.from_string(str) 
      self[:len] = str.size
      return self
    end
  end

  attach_function :greeter, [GoString.by_value], :void
end

Go.greeter(Go::GoString.new("test"))

```

**Comment by larskanis** [comment]
@wade-welles I think it should be
```ruby
self[:len] = str.bytesize
```
since `len` in golang means the number of bytes while `size` in ruby means the number of code points.

**Comment by wade-welles** [comment]
Thanks, I will correct the example. 

Why I have your attention do you have a solution for string of Arrays? I'm trying to write a simple shim library to greatly simplify interacting with the `ffi` gem from Go and I found that extending FFI classes for this purpose seems to provide much more intuitive interaction with the `ffi` API. 

This method checking the type and building the appropriate datatype works well for int, but when I try the expectedly more difficult `string` type I have more difficulty, I'm sure when I have more time to hack at it I can find a solution but if you provide any assistance or suggestions I would be quite grateful:

```

> require 'ffi'
> #require 'benchmark'
> 
> module Go
>   extend FFI::Library
>   ffi_lib './go.so'
> 
>   #module Functions
>   #  extend FFI::Library
>   #  ffi_lib './go.so'
>   #end
> 
>   class Slice < FFI::Struct
>     layout :data,  :pointer,
>            :len,   :long_long,
>            :cap,   :long_long 
> 
>     def self.value 
>       return self.val
>     end
> 
>     #write_array_of_int
>     #write_array_of_uint
>     #write_array_of_int8
>     #write_array_of_long
>     #write_array_of_short
>     #write_array_of_int64
>     #write_array_of_int32
>     #write_array_of_int16
>     #write_array_of_uint8
>     #write_array_of_pointer
>     #write_array_of_ulong
>     #write_array_of_ushort
>     #write_array_of_uint64
>     #write_array_of_uint32
>     #write_array_of_uint16
>     #write_array_of_char
>     #write_array_of_type
>     #write_array_of_float
>     #write_array_of_uchar
>     #write_array_of_double
> 
>     def initialize(slice)
>       p "slice[0].class: #{slice[0].class}"
>       if slice[0].is_a?(Integer)
>         p "'int' type detected, constructing an object for handing over to Go"
>         self[:data] = FFI::MemoryPointer.new(:long_long, slice.size)
>         self[:data].write_array_of_long_long(slice)
>       elsif slice[0].class.to_s == "String" # No idea why this works but without the to_s it does not
>         p "'string' type detected, constructing an object for handing over to Go"
>         # Not working
>         #self[:data] = FFI::MemoryPointer.new(:pointer, slice.size)
>         #strings = Array.new 
>         #slice.size.times do |index|
>         #  strings << FFI::MemoryPointer.from_string(slice[index])
>         ##  strings << Go::String.new(slice[index]) 
>         #end
>         #self[:data].write_array_of_pointer(strings)
>       end
>       self[:len] = slice.bytesize
>       self[:cap] = slice.bytesize 
>       return self
>     end
>   end
> 
>   # define class GoString to map:
>   # C type struct { const char *p; GoInt n; }
>   class String < FFI::Struct
>     layout :p,     :pointer,
>            :len,   :long_long
> 
>     def self.value 
>       return self.val 
>     end
> 
>     def initialize(str) 
>       self[:p] = FFI::MemoryPointer.from_string(str) 
>       self[:len] = str.size
>       return self
>     end
>   end
> 
>   attach_function :greeter, [String.value], :void
>   attach_function :int_slice_size, [Slice.value], :int
>   attach_function :str_slice_size, [Slice.value], :int
> end
> 
> Go.greeter(Go::String.new("test"))
> 
> p "size: #{Go.int_slice_size(Go::Slice.new([5, 3, 2]))}"
> p "size: #{Go.str_slice_size(Go::Slice.new(["one", "two"]))}"
>
