### ISSUE TITLE
Issue with win32-service

### ISSUE THREAD

**Issue by pmichel** [ffi/ffi#618]
Hello, i've problem with my ruby-installation and the win32-service or ffi gem.
Can someone help me? Or what can i do?

ruby-version:
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mswin64_110] - it is self-compiled with vs2012

gem-version:
ffi v1.9.10 or ffi1.9.14

the simple script:
require 'win32/service'

Win32::Service.services do |service|
  p service
end

and the result:

ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mswin64_110]
--
 
-- Control frame information -----------------------------------------------
c:0007 p:---- s:0029 e:000028 CFUNC  :initialize
c:0006 p:---- s:0027 e:000026 CFUNC  :new
c:0005 p:0139 s:0023 e:000022 METHOD F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/service.rb:993
c:0004 p:0024 s:0010 e:000009 TOP    C:/Users/pmichel/RubymineProjects/untitled1/main.rb:5 [FINISH]
c:0003 p:---- s:0008 e:000007 CFUNC  :load
c:0002 p:0035 s:0004 E:001ce0 EVAL   -e:1 [FINISH]
c:0001 p:0000 s:0002 E:000110 (none) [FINISH]
 
-- Ruby level backtrace information ----------------------------------------
-e:1:in `<main>'
-e:1:in `load'
C:/Users/pmichel/RubymineProjects/untitled1/main.rb:5:in `<top (required)>'
F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/service.rb:993:in `services'
F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/service.rb:993:in `new'
F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/service.rb:993:in `initialize'
 
-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0x14) [0x00007FFB4937FF04]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x9f) [0x00007FFB45963B7F]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_print_backtrace+0x34) [0x00007FFB1CCE7D08]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_vm_bugreport+0x6f) [0x00007FFB1CCE7D7F]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_bug_context+0x60) [0x00007FFB1CC28B18]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_signal_name+0x5da) [0x00007FFB1CC8EBA2]
C:\WINDOWS\SYSTEM32\MSVCR110.dll(XcptFilter+0x1a9) [0x00007FFB39B5F5C5]
[0x00007FF7735216D6]
C:\WINDOWS\SYSTEM32\MSVCR110.dll(_C_specific_handler+0x93) [0x00007FFB39B5E98B]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x11d) [0x00007FFB49384C7D]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlWalkFrameChain+0x1518) [0x00007FFB492FD1D8]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007FFB49383BAE]
C:\WINDOWS\SYSTEM32\MSVCR110.dll(memset+0x79) [0x00007FFB39B2C8F9]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\lib\ruby\gems\2.3.0\gems\ffi-1.9.14\lib\ffi_c.so(memptr_malloc+0x7d) [0x00007FFB28F7B185] f:\entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\lib\ruby\gems\2.3.0\gems\ffi-1.9.14\ext\ffi_c\memorypointer.c:123
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\lib\ruby\gems\2.3.0\gems\ffi-1.9.14\lib\ffi_c.so(memptr_initialize+0x99) [0x00007FFB28F7B0D1] f:\entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\lib\ruby\gems\2.3.0\gems\ffi-1.9.14\ext\ffi_c\memorypointer.c:89
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x1744) [0x00007FFB1CC1E10C]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x15b5) [0x00007FFB1CC1DF7D]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x121a) [0x00007FFB1CC1DBE2]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_block_call+0xd2) [0x00007FFB1CC1839E]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_funcallv+0x25) [0x00007FFB1CC196E1]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_class_new_instance+0x2c) [0x00007FFB1CC38C0C]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x1ae4) [0x00007FFB1CC1E4AC]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x24f7) [0x00007FFB1CC1EEBF]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x2116) [0x00007FFB1CC1EADE]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x4a72) [0x00007FFB1CC2143A]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x38b9) [0x00007FFB1CC20281]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_load+0x20e) [0x00007FFB1CBE0326]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(rb_load+0x77) [0x00007FFB1CBE018F]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_thread_stack_overflow+0x21e2) [0x00007FFB1CBDF896]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x1ae4) [0x00007FFB1CC1E4AC]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x24f7) [0x00007FFB1CC1EEBF]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x2116) [0x00007FFB1CC1EADE]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x4a72) [0x00007FFB1CC2143A]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_vm_sysstack_error_copy+0x38b9) [0x00007FFB1CC20281]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_error_print+0xc9) [0x00007FFB1CBD7079]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_exec_node+0x1d) [0x00007FFB1CBD70D1]
F:\Entwicklung\dev_b6\az_ruby_2.3.x\ruby-2.3.3_build\bin\x64-msvcr110-ruby230.dll(ruby_run_node+0x30) [0x00007FFB1CBD7368]
[0x00007FF773521040]
[0x00007FF7735212A7]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007FFB48261FE4]
 
-- Other runtime information -----------------------------------------------
 
* Loaded script: C:/Users/pmichel/RubymineProjects/untitled1/main.rb
 
* Loaded features:
 
0 enumerator.so
1 thread.rb
2 rational.so
3 complex.so
4 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/x64-mswin64_110/enc/encdb.so
5 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/x64-mswin64_110/enc/trans/transdb.so
6 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/x64-mswin64_110/enc/windows_1252.so
7 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/unicode_normalize.rb
8 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/x64-mswin64_110/rbconfig.rb
9 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/compatibility.rb
10 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/defaults.rb
11 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/deprecate.rb
12 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/errors.rb
13 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/version.rb
14 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/requirement.rb
15 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/platform.rb
16 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb
17 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/stub_specification.rb
18 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/util/list.rb
19 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/x64-mswin64_110/stringio.so
20 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb
21 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/exceptions.rb
22 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb
23 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb
24 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/monitor.rb
25 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb
26 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems.rb
27 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb
28 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/version.rb
29 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/core_ext/name_error.rb
30 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/levenshtein.rb
31 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/jaro_winkler.rb
32 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkable.rb
33 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/2.3.0/delegate.rb
34 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
35 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
36 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
37 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
38 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/spell_checkers/null_checker.rb
39 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean/formatter.rb
40 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib/did_you_mean.rb
41 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi_c.so
42 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/platform.rb
43 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/types.rb
44 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/library.rb
45 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/errno.rb
46 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/pointer.rb
47 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/memorypointer.rb
48 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct_layout_builder.rb
49 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/struct.rb
50 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/union.rb
51 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/managedstruct.rb
52 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/callback.rb
53 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/io.rb
54 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/autopointer.rb
55 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/variadic.rb
56 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/enum.rb
57 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi/ffi.rb
58 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/ffi-1.9.14/lib/ffi.rb
59 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/windows/helper.rb
60 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/windows/constants.rb
61 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/windows/structs.rb
62 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/windows/functions.rb
63 F:/Entwicklung/dev_b6/az_ruby_2.3.x/ruby-2.3.3_build/lib/ruby/gems/2.3.0/gems/win32-service-0.8.7/lib/win32/service.rb
 
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

**Comment by larskanis** [comment]
> Can someone help me? Or what can i do?

This is difficult - almost no one uses mswin based ruby. You'll avoid a lot of trouble and get a much better ecosystem with RubyInstaller. It is equally native as mswin ruby. I recommend RubyInstaller-2.4.3.

**Comment by pmichel** [comment]
Hello, thank you.

Yes, you are right. But my problem is, I have several self-written C ++ extensions. And porting them to the mingw version would be a huge job.

Do not you have any idea for me how to get the ffi gem under windows running?

**Comment by larskanis** [comment]
MINGW and MSVC are API and ABI compatible to some extent. Not sure if it is enough to mix them both. Anyhow I don't use nor support MSVC.

**Comment by pmichel** [comment]
OK, thank you...
