### ISSUE TITLE
Use ldconfig cache to get the real `.so` path

### ISSUE THREAD

**Issue by renchap** [ffi/ffi#625]
On Debian, shared libraries packages are not installed by the main package but by the `-dev` package.
This means that if you try to load a shared lib without having the `-dev` package it will fail with an error like this (using `ruby-vips` as an example):
```
irb(main):001:0> require 'vips'
LoadError: Could not open library 'glib-2.0': /usr/lib/x86_64-linux-gnu/glib-2.0: cannot read file data: Is a directory.
Could not open library 'libglib-2.0.so': libglib-2.0.so: cannot open shared object file: No such file or directory
	from /var/lib/gems/2.3.0/gems/ffi-1.9.23/lib/ffi/library.rb:147:in `block in ffi_lib'
	from /var/lib/gems/2.3.0/gems/ffi-1.9.23/lib/ffi/library.rb:100:in `map'
	from /var/lib/gems/2.3.0/gems/ffi-1.9.23/lib/ffi/library.rb:100:in `ffi_lib'
	from /var/lib/gems/2.3.0/gems/ruby-vips-2.0.10/lib/vips.rb:28:in `<module:GLib>'
	from /var/lib/gems/2.3.0/gems/ruby-vips-2.0.10/lib/vips.rb:13:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'
```

When the `-dev` packages are installed, we have this symlink: `/usr/lib/x86_64-linux-gnu/libglib-2.0.so -> /lib/x86_64-linux-gnu/libglib-2.0.so.0` and everything works.

This seems to be caused by the very simple lib lookup fallback here: https://github.com/ffi/ffi/blob/master/lib/ffi/library.rb#L131

On most systems `ldconfig` is used to provide a cache to resolve the short names (`libglib-2.0.so`) to the real library path. For example, on this system: 
```
$ sudo ldconfig -p | grep libglib-2.0
	libglib-2.0.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libglib-2.0.so.0
```

Would it be possible to leverage `ldconfig`, either by using `ld.so` (if i understood the [manpage](https://manpages.debian.org/testing/manpages/ld.so.8.en.html) correctly) or by reading the cache file (`/etc/ld.so.cache` but I am unsure this is a good idea) to get the correct `.so` path?

This seems to be a recurrent issue and not having to install uneeded `-dev` packages would really benefit to Debian (and other distros?) users.

**Comment by renchap** [comment]
Sorry, somebody just pointed me that the cache contains `libglib-2.0.so.0`, not `libglib-2.0.so`, so this wont solve the issue. I guess `ffi` can not do anything about it, unfortunately.
