### ISSUE TITLE
Uncaught Error: error: 1114 when requiring ffi

### ISSUE THREAD

**Issue by bmalex88** [ffi/ffi#642]
I am trying to use ffi in my electron application but as soon as I `require("ffi")`, when I start the application I get the following fatal error in console:

```
Uncaught Error: error: 1114\\?\F:\Projects\myproject\app\node_modules\ref\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (F:\Projects\myproject\app\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (F:\Projects\myproject\app\node_modules\ref\lib\ref.js:5:47)
```

I use **node 8.11.13** on **Window 8.1 x64**. The _ffi_bindings.node_, _ffi_bindings.lib_ and _libffi.lib_ files have been built with VS17 (target x64). I just require the module and the error pops up, as if something were missing

**Comment by larskanis** [comment]
This is the project for FFI on Ruby, so sorry we can not help for Node specific issues.
