### ISSUE TITLE
Unresolved uint64_t on ubuntu 16.04

### ISSUE THREAD

**Issue by klobuczek** [ffi/ffi#686]
`uint64_t` is not defined on ubuntu 16.04. From past issues I've seen that it is a matter of regenerating `types.conf` however, it is not clear to me how to do it.

 ```
root@ubuntu-xenial:/home/vagrant/neo4j-ruby-driver# uname -a
Linux ubuntu-xenial 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@ubuntu-xenial:/home/vagrant/neo4j-ruby-driver# gem list ffi

*** LOCAL GEMS ***

ffi (1.10.0 java)
root@ubuntu-xenial:/home/vagrant/neo4j-ruby-driver# irb
jruby-9.2.6.0 :001 > require 'ffi'
 => true
jruby-9.2.6.0 :002 > module Abc; extend FFI::Library; typedef :uint64_t, :bolt_request; end
Traceback (most recent call last):
        9: from /usr/share/rvm/rubies/jruby-9.2.6.0/bin/irb:13:in `<main>'
        8: from org/jruby/RubyKernel.java:1179:in `catch'
        7: from org/jruby/RubyKernel.java:1179:in `catch'
        6: from org/jruby/RubyKernel.java:1411:in `loop'
        5: from org/jruby/RubyKernel.java:1047:in `eval'
        4: from (irb):2:in `evaluate'
        3: from (irb):2:in `<module:Abc>'
        2: from /usr/share/rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/ffi/library.rb:407:in `typedef'
        1: from /usr/share/rvm/rubies/jruby-9.2.6.0/lib/ruby/stdlib/ffi/types.rb:55:in `find_type'
TypeError (unable to resolve type 'uint64_t')
jruby-9.2.6.0 :003 >
```
vs
```
heinrich@berlin:~/mck$ uname -a
Darwin berlin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
heinrich@berlin:~/mck$ gem list ffi

*** LOCAL GEMS ***

ffi (1.10.0 java)
heinrich@berlin:~/mck$ irb
jruby-9.2.6.0 :001 > require 'ffi'
 => true
jruby-9.2.6.0 :002 > module Abc; extend FFI::Library; typedef :uint64_t, :bolt_request; end
 => #<FFI::Type::Builtin:0x4b168fa9>
jruby-9.2.6.0 :003 >
```

**Comment by klobuczek** [comment]
Closing issue due to wrong type name used. Type `:uint64` works as expected.
