### ISSUE TITLE
macOS Mojave latest version that can be build is 1.9.17

### ISSUE THREAD

**Issue by rogodani** [ffi/ffi#706]
I have issues installing latest version of ffi on macOS Mojave. build was failing for all versions between 1.9.17 and 1.11.1
`Building native extensions.  This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.24/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20190616-73361-119ugz.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... no
checking for shlwapi.h... no
checking for ruby/thread.h... yes
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/ffi-1.9.24/mkmf.log

current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.24/ext/ffi_c
make "DESTDIR=" clean

current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.24/ext/ffi_c
make "DESTDIR="
Configuring libffi
configure: error: in `/Library/Ruby/Gems/2.3.0/gems/ffi-1.9.24/ext/ffi_c/libffi-universal-darwin18':
configure: error: C++ preprocessor "/lib/cpp" fails sanity check
See `config.log' for more details
make: *** ["/Library/Ruby/Gems/2.3.0/gems/ffi-1.9.24/ext/ffi_c/libffi-universal-darwin18"/.libs/libffi_convenience.a] Error 1

make failed, exit code 2

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/ffi-1.9.24 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/ffi-1.9.24/gem_make.out`

**Comment by jacquescrocker** [comment]
I'm seeing this as well. Had to downgrade `ffi` versions to get it working again

**Comment by larskanis** [comment]
@rogodani Could you please post the file `config.log` as mentioned in the log output?

**Comment by rogodani** [comment]
@larskanis please find attached the config.log 
[config.log](https://github.com/ffi/ffi/files/3317508/config.log)

**Comment by ehsong** [comment]
Hi, is there a solution do this? I can't build jekyll nor install jekyll, ffi dependency is failing. How can I downgrade?

**Comment by rogodani** [comment]
Hi @ehsong you should set in the Gemfile
gem 'ffi', '1.9.17'
this is the first version for which the installation worked.

**Comment by rogodani** [comment]
@larskanis did you had time to take a look on this issue?

**Comment by felipeerias** [comment]
Hi, I might be having the same issue. Downgrading the ffi gem doesn't seem to help.

These are the steps that I took:

- install libffi via Homebrew (libffi-3.2.1.mojave)

    `brew install libffi`

- update environment

    `export LDFLAGS="-L/usr/local/opt/libffi/lib"`
    `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"`

- install the downgraded ffi gem (version 1.9.17)

    `sudo gem install ffi -v '1.9.17'`

- install bundler-2.0.2 and jekyll-4.0.0

    `sudo gem install bundler jekyll`

- try to run jekyll

```
$ jekyll new --blank

Traceback (most recent call last):
	21: from /usr/local/bin/jekyll:23:in `<main>'
	20: from /usr/local/bin/jekyll:23:in `load'
	19: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
	18: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `<top (required)>'
	15: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-sass-converter-2.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	12: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-sass-converter-2.0.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	 9: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `<top (required)>'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `require_relative'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.1.0/lib/sassc/native.rb:3:in `<top (required)>'
	 4: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi.rb:4:in `<top (required)>'
	 1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
	22: from /usr/local/bin/jekyll:23:in `<main>'
	21: from /usr/local/bin/jekyll:23:in `load'
	20: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/exe/jekyll:8:in `<top (required)>'
	19: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	18: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-4.0.0/lib/jekyll.rb:206:in `<top (required)>'
	16: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	15: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-sass-converter-2.0.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'
	13: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	12: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/jekyll-sass-converter-2.0.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'
	10: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 9: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `<top (required)>'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.1.0/lib/sassc.rb:31:in `require_relative'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/sassc-2.1.0/lib/sassc/native.rb:3:in `<top (required)>'
	 5: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 4: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi.rb:3:in `<top (required)>'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi.rb:6:in `rescue in <top (required)>'
	 1: from /usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/Cellar/ruby/2.6.3/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle, 9): Symbol not found: _ffi_type_double (LoadError)
  Referenced from: /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle
  Expected in: flat namespace
 in /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle - /usr/local/lib/ruby/gems/2.6.0/gems/ffi-1.9.17/lib/ffi_c.bundle
```

**Comment by alvations** [comment]
Managed to do this to install `ffi` when bundling github pages with jekyll.

Install `ffi-1.9.17`:

```
$ sudo gem install ffi -v '1.9.17' --source 'https://rubygems.org/'
```

Gemfile:

```
source 'https://rubygems.org'
gem "ffi", "~>1.9.17"
gem 'github-pages', group: :jekyll_plugins
```

Then

```
bundle install
```

**Comment by larskanis** [comment]
Installation on macOS will be further improved in ffi-1.13.0.
