### ISSUE TITLE
error`attach': unhandled on Dreamhost

### ISSUE THREAD

**Issue by muescha** [ffi/ffi#718]
i get this error on startup while `require 'typhoeus'`:

```bash
/.../vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach': unhandled exception
        from /.../vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach_function'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:16:in `<module:Libc>'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:6:in `<module:Ethon>'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon/libc.rb:1:in `<top (required)>'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:14:in `require'
        from /.../vendor/bundle/ruby/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:14:in `<top (required)>'
        from /.../vendor/bundle/ruby/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `require'
        from /.../vendor/bundle/ruby/2.6.0/gems/typhoeus-1.3.1/lib/typhoeus.rb:2:in `<top (required)>'
        from /.../app/main.rb:4:in `require'
        from /.../app/main.rb:4:in `<top (required)>'
        from config.ru:61:in `require'
        from config.ru:61:in `block in <main>'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `eval'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:49:in `new_from_string'
        from /.../vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:40:in `parse_file'
        from ./dispatch_fcgi.rb:21:in `<main>'
```

(replaced my folder with `...`)

check installed version:

```
dpkg -l | grep libcurl 
ii libcurl3-gnutls:amd64 7.58.0-2ubuntu3.8 amd64 easy-to-use client-side URL transfer library (GnuTLS flavour) 
ii libcurl4:amd64 7.58.0-2ubuntu3.8 amd64 easy-to-use client-side URL transfer library (OpenSSL flavour) 
ii libcurl4-gnutls-dev:amd64 7.58.0-2ubuntu3.8 amd64 development files and documentation for libcurl (GnuTLS flavour) 
ii libwww-curl-perl 4.17-4build1 amd64 Perl bindings to libcurl 
ii python-pycurl 7.43.0.1-0.2 amd64 Python bindings to libcurl 
ii ruby-curb 0.9.4-1build2 amd64 Ruby libcurl bindings 
```

**Comment by muescha** [comment]
(done suggestion from https://github.com/typhoeus/typhoeus/issues/627 )


i get this error on remote machine

```ruby

$ cat testfile.rb                                                                                                                                                                                                                                    
require 'ffi'                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                     
module MyLib                                                                                                                                                                                                                                                                                         
  extend FFI::Library                                                                                                                                                                                                                                                                                
  ffi_lib 'c'                                                                                                                                                                                                                                                                                        
  attach_function :getdtablesize, [], :int                                                                                                                                                                                                                                                           
end                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                     
MyLib.getdtablesize      


$ bundle exec ruby testfile.rb                                                                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                                                                                                                                                   
        3: from testfile.rb:3:in `<main>'                                                                                                                                                                                                                                                            
        2: from testfile.rb:6:in `<module:MyLib>'                                                                                                                                                                                                                                                    
        1: from /..../vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach_function'                                                                                                                                           
/..../vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach': unhandled exception                                                                                                                                               
```

(replaced some path to `....`)

**Comment by PericlesTheo** [comment]
Author of the comment in the Typhoeus linked above.

Just a bit of context why the code above. Based on the stacktrace, the first line that calls FFI is the one for `getdtablesize`. Since the `MyLib` example is erroring, I think there might be something weird with the `libcurl` versions installed or the system.

@muescha can you try running the following?

```c
#include <stdio.h>
#include <unistd.h>

int main() {
  int size = getdtablesize();
  printf("The file descriptor table size is %d\n", size);
  return 0;
}
``` 
Save the file above in a `test.c`, and then
```bash
$ gcc test.c
$ ./a.out
```

For example on my machine it returns
> The file descriptor table size is 256

**Comment by muescha** [comment]
i get this:

```bash
$ gcc test.c                                                                                           
$ ./a.out                                                                                              
The file descriptor table size is 1024 
```

**Comment by muescha** [comment]
@PericlesTheo any idea whats wrong or how to fix it?

**Comment by muescha** [comment]
i get this:

```bash
$ gcc -v                                                                                                                                     
Using built-in specs.                                                                
COLLECT_GCC=gcc                                                                      
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper                      
OFFLOAD_TARGET_NAMES=nvptx-none                                                      
OFFLOAD_TARGET_DEFAULT=1                                                             
Target: x86_64-linux-gnu                                                             
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1
' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,
go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-
suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id
 --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/us
r/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --e
nable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object 
--disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-s
ystem-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disab
le-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enab
le-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-dr
iver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --tar
get=x86_64-linux-gnu                                                                 
Thread model: posix                                                                  
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
```

**Comment by PericlesTheo** [comment]
@muescha just to isolate some cases, can ffi work with a simple build in C function?

```ruby
require 'ffi'

module MyLib
  extend FFI::Library
  ffi_lib 'c'
  attach_function :isdigit, [:int], :bool
end

MyLib.isdigit "5".ord
```
Should return `true` but it doesn't matter as long as it runs.

**Comment by muescha** [comment]
```bash
$ cat xtext2.rb                                                                                                                                         
require 'ffi'                                                                                                                                                                                           
                                                                                                                                                                                                        
module MyLib                                                                                                                                                                                            
  extend FFI::Library                                                                                                                                                                                   
  ffi_lib 'c'                                                                                                                                                                                           
  attach_function :isdigit, [:int], :bool                                                                                                                                                               
end                                                                                                                                                                                                     
MyLib.isdigit "5".ord                            

$ bundle exec ruby xtext2.rb                                                                                                                            
Traceback (most recent call last):                                                                                                                                                                      
        3: from xtext2.rb:3:in `<main>'                                                                                                                                                                 
        2: from xtext2.rb:6:in `<module:MyLib>'                                                                                                                                                         
        1: from /home/muescha/test.gayreal.de/releases/20131102014038/vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach_function'                                              
/home/muescha/test.gayreal.de/releases/20131102014038/vendor/bundle/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi/library.rb:275:in `attach': unhandled exception  
```

```bash
$ bundle exec gem list                                                                                                                                  
                                                                                                                                                                                                        
*** LOCAL GEMS ***                                                                                                                                                                                      
                                                                                                                                                                                                        
bundler (2.0.2)                                     
[...]
ffi (1.11.1)
[...]
```


ffi is installed via bunlder...

```bash
$ ruby xtext2.rb                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                      
        2: from xtext2.rb:1:in `<main>'                                                                                                                                                                 
        1: from /home/muescha/.rbenv/versions/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'                                                                        
/home/muescha/.rbenv/versions/2.6.4/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffi (LoadError) 
```

**Comment by muescha** [comment]
thx for reply - i am on a server at dreamhost - that's the problem :)
it worked fine before, but after an upgrade on dreamhost side not working

i will ask the support there

**Comment by PericlesTheo** [comment]
cool, in that case I will close the issue on Typhoeus

**Comment by muescha** [comment]
dreamhost support was not helpful, only information: if i need admin permissions then i have to move to dreamcompute :(

i uninstalled ffi and reinstalled but get no error message:

```bash
$ bundle exec gem uninstall ffi                                                                                                                         
                                                                                                                                                                                                        
You have requested to uninstall the gem:                                                                                                                                                                
        ffi-1.11.1                                                                                                                                                                                      
                                                                                                                                                                                                        
ethon-0.12.0 depends on ffi (>= 1.3.0)                                                                                                                                                                  
If you remove this gem, these dependencies will not be met.                                                                                                                                             
Continue with Uninstall? [yN]  y                                       
Successfully uninstalled ffi-1.11.1 
```

```bash
$ bundle install                                                                                                                                        
Fetching gem metadata from https://rubygems.org/.......                                                                                                                                                 
Using bundler 2.0.2                                                                                                                                                                                     
Using concurrent-ruby 1.1.5                                                                                                                                                                             
Using connection_pool 2.2.2                                                                                                                                                                             
Using unf_ext 0.0.7.6                                                                                                                                                                                   
Using unf 0.1.4                                                                                                                                                                                         
Using domain_name 0.5.20190701                                                                                                                                                                          
Using dry-core 0.4.9                                                                                                                                                                                    
Using dry-configurable 0.8.3                                                                                                                                                                            
Using dry-container 0.7.2                                                                                                                                                                               
Using dry-equalizer 0.2.2                                                                                                                                                                               
Using dry-inflector 0.1.2                                                                                                                                                                               
Using dry-initializer 3.0.1                                                                                                                                                                             
Using dry-logic 1.0.3                                                                                                                                                                                   
Using dry-types 1.1.1                                                                                                                                                                                   
Using ice_nine 0.11.2                                                                                                                                                                                   
Using dry-struct 1.0.0                                                                                                                                                                                  
Fetching ffi 1.11.1                                                                                                                                                                                     
Installing ffi 1.11.1 with native extensions                                                                                                                                                            
Using ethon 0.12.0                                                                                                                                                                                      
Using fcgi 0.9.2.1                                                                                                                                                                                      
Using temple 0.8.2                                                                                                                                                                                      
Using tilt 2.0.10                                                                                                                                                                                       
Using haml 5.1.2                                                                                                                                                                                        
Using http-cookie 1.0.3                                                                                                                                                                                 
Using json 2.2.0                                                                                                                                                                                        
Using mini_mime 1.0.2                                                                                                                                                                                   
Using mail 2.7.1                                                                                                                                                                                        
Using mime-types-data 3.2019.0904                                                                                                                                                                       
Using mime-types 3.3                                                                                                                                                                                    
Using net-http-digest_auth 1.4.1                                                                                                                                                                        
Using net-http-persistent 3.1.0                                                                                                                                                                         
Using mini_portile2 2.4.0                                                                                                                                                                               
Using nokogiri 1.10.4                                                                                                                                                                                   
Using ntlm-http 0.1.1                                                                                                                                                                                   
Using webrobots 0.1.2                                                                                                                                                                                   
Using mechanize 2.7.6                                                                                                                                                                                   
Using mustache 1.1.0                                                                                                                                                                                    
Using mustermann 1.0.3                                                                                                                                                                                  
Using newrelic_rpm 6.6.0.358                                                                                                                                                                            
Using pony 1.13.1                                                                                                                                                                                       
Using rack 2.0.7                                                                                                                                                                                        
Using rack-protection 2.0.7                                                                                                                                                                             
Using transproc 1.1.0                                                                                                                                                                                   
Using rom-core 5.1.2                                                                                                                                                                                    
Using rom-changeset 5.1.2                                                                                                                                                                               
Using rom-repository 5.1.2                                                                                                                                                                              
Using rom 5.1.2                                                                                                                                                                                         
Using sequel 5.25.0                                                                                                                                                                                     
Using rom-sql 3.0.1                                                                                                                                                                                     
Using sinatra 2.0.7                                                                                                                                                                                     
Using sqlite3 1.4.1                                                                                                                                                                                     
Using typhoeus 1.3.1                                                                                                                                                                                    
Bundle complete! 18 Gemfile dependencies, 51 gems now installed.                                                                                                                                        
Gems in the groups development and test were not installed.                                                                                                                                             
Bundled gems are installed into `./vendor/bundle`             
```

is there an other way to check the libffi installation?

**Comment by ernstki** [comment]
Ran into this same problem with Jekyll on DreamHost. After hours of unsuccessful experimentation (including building libffi from source, (re)installing ffi with `gem install ffi -- --disable-system-libffi`, and installing my own Ruby with rbenv), I eventually downgraded to an older Jekyll.

Wish I had better news for you. `:/`

**Comment by coneybeare** [comment]
I'm on dreamhost as well, but have a dedicated server and root access. I have tried just about every permutation of solutions I could find over the past few days, and still cannot get past this error. Any insight would be much appreciated
