### ISSUE TITLE
Error building ffi-1.11.1 in Alpine 3.10

### ISSUE THREAD

**Issue by noraj** [ffi/ffi#719]
```dockerfile
# Author: noraj

# Official verified image
FROM ruby:2.6.3-alpine3.10

# hardening
RUN chmod 773 /tmp

# date
RUN ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime

# copy files
COPY ./website/ /usr/src/app/

WORKDIR /usr/src/app

## INSTALL ##
# Print out ruby version for debugging
RUN ruby -v
# Bundler is not installed with the image
RUN gem install bundler --no-document
# install nproc (coreutils) for bundle -j
# install git for building the gemspec
# install make, gcc for building gem native extension (commonmarker)
# libc-dev for musl-dev dependency (stdlib.h) needed by gcc
# install g++ and libstdc++ for building eventmachine
RUN apk --no-cache add coreutils git build-base libstdc++ libffi-dev
RUN bundle install -j $(nproc) --path vendor # Install dependencies into ./vendor/ruby
# Install node LTS and npm
RUN apk --no-cache add nodejs npm
# Print out node version for debugging
RUN node --version
# Print out npm version for debugging
RUN npm --version
# Install gulp
RUN npm install -g gulp-cli
# Install dependencies
RUN npm install

## BUILD ##
RUN gulp build
RUN bundle exec middleman build
RUN mv build/* public/

# drop privileges
RUN groupadd -g 1337 appuser && \
    useradd -r -u 1337 -g appuser appuser
USER appuser


EXPOSE 4567

CMD bundle exec middleman server 4567
```

```
Step 16/21 : RUN bundle exec middleman build
 ---> Running in f56ce493f31a
bundler: failed to load command: middleman (/usr/src/app/vendor/ruby/2.6.0/bin/middleman)
LoadError: Error relocating /usr/src/app/vendor/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi_c.so: __sprintf_chk: symbol not found - /usr/src/app/vendor/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi_c.so
  /usr/src/app/vendor/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi.rb:6:in `require'
  /usr/src/app/vendor/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi.rb:6:in `rescue in <top (required)>'
  /usr/src/app/vendor/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi.rb:3:in `<top (required)>'
  /usr/src/app/vendor/ruby/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/native.rb:1:in `require'
  /usr/src/app/vendor/ruby/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify/native.rb:1:in `<top (required)>'
  /usr/src/app/vendor/ruby/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify.rb:2:in `require'
  /usr/src/app/vendor/ruby/2.6.0/gems/rb-inotify-0.10.0/lib/rb-inotify.rb:2:in `<top (required)>'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/adapter/linux.rb:30:in `require'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/adapter/linux.rb:30:in `_configure'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:45:in `block in configure'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `each'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `configure'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:63:in `start'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/backend.rb:28:in `start'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/listener.rb:67:in `block in <class:Listener>'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `instance_eval'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `call'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/fsm.rb:57:in `transition'
  /usr/src/app/vendor/ruby/2.6.0/gems/listen-3.0.8/lib/listen/listener.rb:90:in `start'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/sources/source_watcher.rb:182:in `listen!'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/sources.rb:249:in `each'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/sources.rb:249:in `start!'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/core_extensions/file_watcher.rb:66:in `after_configuration'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/extension.rb:405:in `block in bind_after_configuration'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:57:in `block in execute'
  /usr/src/app/vendor/ruby/2.6.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
  /usr/src/app/vendor/ruby/2.6.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
  /usr/src/app/vendor/ruby/2.6.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:57:in `execute'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
  /usr/src/app/vendor/ruby/2.6.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-core-4.3.5/lib/middleman-core/application.rb:306:in `initialize'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-cli-4.3.5/bin/middleman:49:in `new'
  /usr/src/app/vendor/ruby/2.6.0/gems/middleman-cli-4.3.5/bin/middleman:49:in `<top (required)>'
  /usr/src/app/vendor/ruby/2.6.0/bin/middleman:23:in `load'
  /usr/src/app/vendor/ruby/2.6.0/bin/middleman:23:in `<top (required)>'
ERROR: Service 'cracking1' failed to build: The command '/bin/sh -c bundle exec middleman build' returned a non-zero code: 1
```

**Comment by noraj** [comment]
```diff
+ FROM ruby:2.5.7-alpine3.10
- FROM ruby:2.6.3-alpine3.10
```

Works with 2.5.7

**Comment by larskanis** [comment]
You're using glibc binaries in a musl based container. You have to install ffi within the container instead of copying into it.

**Comment by noraj** [comment]
As you can see I installed `libffi-dev` which has `libffi` as a dependency, so I installed ffi in the container.

```
RUN apk --no-cache add coreutils git build-base libstdc++ libffi-dev
```

**Comment by larskanis** [comment]
The error appears while loading `/usr/src/app/vendor/ruby/2.6.0/gems/ffi-1.11.1/lib/ffi_c.so` and this is copied into the container. You have to install the ffi gem within the container - not just libffi.

**Comment by noraj** [comment]
`ffi` is a sub-dependency, the chain is: middleman -> middleman-core -> listen -> rb-inotify -> ffi

As I have `middleman` in my gemfile, ffi is installed after `bundle install -j $(nproc) --path vendor`. So it rightfully should be in `/usr/src/app/vendor/ruby/2.6.0/gems/ffi-1.11.1/`. So the ffi gem is installed directly inside the container and not copied intro. Else I don't understand what you mean.

**Comment by noraj** [comment]
My guess is that ffi builds correctly with ruby 2.4 and 2.5 but does not build under ruby 2.6 and so the `ffi_c.so` is never built.

That why I created a PR https://github.com/ffi/ffi/pull/720/files so this project can be tested under 2.6 too.
