### ISSUE TITLE
ffi 1.12.2 is not supporting libffi 3.3

### ISSUE THREAD

**Issue by noraj** [ffi/ffi#769]
On ArchLinux

```
$ pacman -Qi libffi
Name            : libffi
Version         : 3.3-3
Description     : Portable foreign function interface library
Architecture    : x86_64
URL             : https://sourceware.org/libffi/
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : glibc
Optional Deps   : None
Required By     : ghc-libs  glib2  guile  libp11-kit  llvm-libs  python  python2  ruby  wayland
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 73,83 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : jeu. 09 avril 2020 06:09:20
Install Date    : lun. 13 avril 2020 14:42:51
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

ffi gem

```
$ gem info ffi               

*** LOCAL GEMS ***

ffi (1.12.2)
    Author: Wayne Meissner
    Homepage: https://github.com/ffi/ffi/wiki
    License: BSD-3-Clause
    Installed at: /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0

    Ruby FFI
```

When loading ffi:

```
$ irb
irb(main):001:0> require 'ffi'
Traceback (most recent call last):
       11: from /home/noraj/.rbenv/versions/2.7.0/bin/irb:23:in `<main>'
       10: from /home/noraj/.rbenv/versions/2.7.0/bin/irb:23:in `load'
        9: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        8: from (irb):1
        7: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        6: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        5: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        4: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:3:in `<top (required)>'
        3: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi.rb:6:in `rescue in <top (required)>'
        2: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        1: from /home/noraj/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
LoadError (libffi.so.6: cannot open shared object file: No such file or directory - /home/noraj/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/ffi-1.12.2/lib/ffi_c.so)
```

log history of libffi on arch: https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/libffi

seems like ffi 1.12.2 is not supporting libffi 3.3 but was working with 3.2.1. libffi-3.3 was released on November 23, 2019 (see https://sourceware.org/libffi/).

**Comment by larskanis** [comment]
ffi-1.12.2 is compatible to libffi-3.3, but Arch Linux is a rolling release distribution - meaning that they introduce incompatible changes whenever a new upstream library is released. So in this case you must recompile the gem to switch from libffi-3.2 to the binary incompatible library version 3.3.
```sh
gem pristine ffi
```
should do the trick.

**Comment by noraj** [comment]
@larskanis I was looking for a `--rebuild` option for `gem update` or `gem install` and didn't found one, I wasn't aware of pristine :) Thanks you very much, recompiling native extensions with the new system libraries works.
