### ISSUE TITLE
RuntimeError in FFI::Library#attach_function 

### ISSUE THREAD

**Issue by coneybeare** [ffi/ffi#808]
I've been struggling with this one for a day or so but I think there is some compatibility issue with the FFI gem and my system, and hours of googling has led to no help.Hopefully somebody here can point me to the right direction. I'll start with the sample `ffi_test.rb` file I am running as a test:

````ruby
$ cat ffi_test.rb
require 'ffi'

module Hello
  extend FFI::Library
  ffi_lib FFI::Library::LIBC
  attach_function 'puts', [ :string ], :int
end

Hello.puts("Hello, World")
````

Server: 
````
$ cat /etc/issue
Ubuntu 18.04.4 LTS
````

Attempt 1 (no extra install options):
````
$ gem install ffi -v '1.13.1'
Building native extensions. This could take a while...
Successfully installed ffi-1.13.1
Parsing documentation for ffi-1.13.1
Done installing documentation for ffi after 2 seconds
1 gem installed
$
$ ruby ffi_test.rb
Traceback (most recent call last):
	3: from ffi_test.rb:3:in `<main>'
	2: from ffi_test.rb:6:in `<module:Hello>'
	1: from /home/REDACTED/.rvm/gems/ruby-2.7.1@REDACTED/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach_function'
/home/REDACTED/.rvm/gems/ruby-2.7.1@ REDACTED/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach': �\x1D+N\x04\x1E (RuntimeError)
````

Attempt 2 (force system libffi):
````
$ gem uninstall ffi
Successfully uninstalled ffi-1.13.1
$
$ gem install ffi -v '1.13.1' -- --enable-system-libffi
Fetching ffi-1.13.1.gem
Building native extensions with: '--enable-system-libffi'
This could take a while...
Successfully installed ffi-1.13.1
Parsing documentation for ffi-1.13.1
Installing ri documentation for ffi-1.13.1
Done installing documentation for ffi after 7 seconds
1 gem installed
$
$ ruby ffi_test.rb
Traceback (most recent call last):
	3: from ffi_test.rb:3:in `<main>'
	2: from ffi_test.rb:6:in `<module:Hello>'
	1: from /home/REDACTED/.rvm/gems/ruby-2.7.1@ REDACTED/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach_function'
/home/REDACTED/.rvm/gems/ruby-2.7.1@ REDACTED/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach': h��\x15�\x15 (RuntimeError)
````

Attempt 3 (force build-in libffi):
````
$ gem uninstall ffi
Successfully uninstalled ffi-1.13.1
$
$ gem install ffi -v '1.13.1' -- --disable-system-libffi
Fetching ffi-1.13.1.gem
Building native extensions with: '--disable-system-libffi'
This could take a while...
This could take a while...
Successfully installed ffi-1.13.1
Parsing documentation for ffi-1.13.1
Installing ri documentation for ffi-1.13.1
Done installing documentation for ffi after 7 seconds
1 gem installed
$
$ ruby ffi_test.rb
Traceback (most recent call last):
	3: from ffi_test.rb:3:in `<main>'
	2: from ffi_test.rb:6:in `<module:Hello>'
	1: from /home/REDACTED/.rvm/gems/ruby-2.7.1@ REDACTED/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach_function'
/home/REDACTED/.rvm/gems/ruby-2.7.1@ REDACTED/gems/ffi-1.13.1/lib/ffi/library.rb:275:in `attach': ج�\x0F�\x15 (RuntimeError)
````

I have an up-to-date rvm installed ruby, which btw is:
````
$ which ruby
/home/REDACTED/.rvm/rubies/ruby-2.7.1/bin/ruby
````

And I have made sure the server has the `libffi-dev` package installed:
````
root@REDACTED:~# apt-get install libffi-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libffi-dev is already the newest version (3.2.1-8).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
````

Is there some sort of compatibility issue with Ubuntu 18.0.4, ruby 2.7.1, and ffi v 1.13.1 that I cannot see? What can I do to debug this issue?

**Comment by coneybeare** [comment]
And of course, after hours with this issue, I stumbled across a fix, which was not obvious. On the readme of this repo, there is a section about `paxctl` but it is not clear when to apply it. I tried doing it once a few hours ago, but gave up on error. When revisiting just now, I read it a bit more carefully and converted the headers before running it.

````
$ paxctl -m `which ruby`
file /home/viewing/.rvm/rubies/ruby-2.7.1/bin/ruby does not have a PT_PAX_FLAGS program header, try conversion
$ paxctl -c `which ruby`
file /home/REDACTED/.rvm/rubies/ruby-2.7.1/bin/ruby had a PT_GNU_STACK program header, converted
$ paxctl -m `which ruby`
$ ruby ffi_test.rb
Hello, World using libc!
$
````

Hopefully this helps some future googler
