### ISSUE TITLE
Error building ffi-1.31.1 into ubuntu 18.04.4 with ruby 2.7.1

### ISSUE THREAD

**Issue by icalvete** [ffi/ffi#817]
Hi, 

With 2.5.1p57 (Version in the system) works fine. 

(So. I have all dependencies. Rigth?)

With ruby 2.7.1 in the into same machine (Compiled with rbenv-build) ...

```bash
ubuntu@fdevcore:~$ gem install ffi
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/ext/ffi_c
/usr/local/rbenv/versions/2.7.1/bin/ruby -I /usr/local/rbenv/versions/2.7.1/lib/ruby/2.7.0 -r ./siteconf20200810-17653-v9cksh.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/rbenv/versions/2.7.1/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/local/rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/local/rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:564:in `try_link0'
	from /usr/local/rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:582:in `try_link'
	from /usr/local/rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:684:in `try_ldflags'
	from /usr/local/rbenv/versions/2.7.1/lib/ruby/2.7.0/mkmf.rb:1851:in `pkg_config'
	from extconf.rb:9:in `system_libffi_usable?'
	from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.13.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ffi-1.13.1 for inspection.
Results logged to /usr/local/rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ffi-1.13.1/gem_make.out
```

I have tried with these verions too (into other machine) with success

 * 2.3.1p112 into a ubuntu 16.04 (Version in the system)
 * 2.5.1p57 into a ubuntu 16.04 (Compiled with rbenv-build)

**Comment by larskanis** [comment]
Did you check the `mkmf.log` as recommended by the log output? It should show you details to the compiler error.

**Comment by richman1000000** [comment]
install `gcc `and `make `prior to execute `gem install ffi`
