### ISSUE TITLE
TypeError: unable to resolve type 'size_t'

### ISSUE THREAD

**Issue by nilleb** [ffi/ffi#847]
Happening on Apple M1

version: ffi-1.13.1

on `ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]`

might be related to #137 

full stack
```
rails aborted!
TypeError: unable to resolve type 'size_t'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/lib/ffi/types.rb:69:in `find_type'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/lib/ffi/library.rb:589:in `find_type'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/lib/ffi/struct.rb:277:in `find_type'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/lib/ffi/struct.rb:271:in `find_field_type'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/lib/ffi/struct.rb:311:in `array_layout'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/ffi-1.13.1/lib/ffi/struct.rb:217:in `layout'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native/sass_value.rb:53:in `<class:SassList>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native/sass_value.rb:52:in `<module:Native>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native/sass_value.rb:4:in `<module:SassC>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native/sass_value.rb:3:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:16:in `<module:Native>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:6:in `<module:SassC>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc/native.rb:5:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sassc-rails-2.1.2/lib/sassc/rails.rb:5:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/sass-rails-6.0.0/lib/sass-rails.rb:1:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:23:in `require'
/Users/nilleb/dev/livestorm-app/packages/backend/config/application.rb:7:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
/Users/nilleb/dev/livestorm-app/packages/backend/Rakefile:4:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:55:in `load'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:285:in `block in load'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:285:in `load'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/railties-5.2.4/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/railties-5.2.4/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/railties-5.2.4/lib/rails/command.rb:48:in `invoke'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/railties-5.2.4/lib/rails/commands.rb:18:in `<main>'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `block in require'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4/lib/active_support/dependencies.rb:291:in `require'
bin/rails:4:in `<main>'
```

**Comment by hcatlin** [comment]
Hey @nilleb ! Thanks for the bug report... I also had this issue. It's been resolved on the main branch, but isn't in a release yet because even after fixing this one there remains additional work needed to support the M1/ARM64 processor.

The team here is working hard on figuring them all out!

You can see more in #841 and was solved with #801
