### ISSUE TITLE
Function 'getmntinfo64' not found in [libc.dylib] (FFI::NotFoundError)

### ISSUE THREAD

**Issue by rgaufman** [ffi/ffi#850]
Another Apple Silicon issue:

```
Romans-MacBook-Air.local ➜  TestApp git:(master) ✗ bundle exec rails c
/opt/homebrew/lib/ruby/gems/2.7.0/bundler/gems/ffi-2b44904f8323/lib/ffi/library.rb:273:in `attach_function': Function 'getmntinfo64' not found in [libc.dylib] (FFI::NotFoundError)
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:44:in `rescue in <module:Functions>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:29:in `<module:Functions>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:5:in `<class:Filesystem>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:4:in `<module:Sys>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem/functions.rb:3:in `<main>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/unix/sys/filesystem.rb:3:in `<main>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys/filesystem.rb:13:in `<main>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/sys-filesystem-1.4.0/lib/sys-filesystem.rb:1:in `<main>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/bundler.rb:174:in `require'
	from /Users/hackeron/Development/Tether/TestApp/config/application.rb:7:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /opt/homebrew/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from /opt/homebrew/Cellar/ruby/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	from -e:1:in `<main>'
```

**Comment by djberg96** [comment]
Possible clue from https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes:

New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

**Comment by lenlo** [comment]
> Another Apple Silicon issue:

For the record, I'm seeing this on my Intel-based MacBook Pro running 11.1 as well, so it's not just Apple Silicon.

**Comment by olikristen** [comment]
You can solve this problem by updating gem 'sys-filesystem' to 1.4.1

**Comment by rannyeribaptist** [comment]
same thing here

I have this issue when I install ruby using homebrew, or even with rbenv installed.
- ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [arm64-darwin21];
- Homebrew 3.4.0;

libffi is installed, and gem sys-filesystem in version 1.4.3.

**Comment by djberg96** [comment]
@rannyeribaptist Hm, that's odd. What's the output of `RbConfig::CONFIG['host_os']` on your system?

**Comment by rannyeribaptist** [comment]
@djberg96 The issue for me was something else, I'll post the solution here in case someone face the same thing I did.

My homebrew was installed on arm64 architecture, under `/opt/homebrew`. This was the cause of the issue. The solution in this case was to uninstall rbenv and everything else from arch64 architecture and go to x86_64 architecture instead.

I followed **court3nay**'s solution, which can be found here: ([https://stackoverflow.com/a/65398385/6279209](https://stackoverflow.com/a/65398385/6279209))

The idea is to have homebrew installed in 2 different places, and it will behave differently in these 2 locations, being one (`/opt/homebrew`) for arm64 and (`/usr/local/homebrew`) for x86_64.

I'm considering you use zsh in your terminal.

First I uninstall your ruby manager (rbenv for example) and make sure your environment is clean. Wipe out any mentions of your ruby manager in `.zshrc` and `.bash_profile` files in your home directory.

After that, Open your terminal and type:

```
cd /usr/local && mkdir homebrew
curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
```

This is going to install homebrew for non arm architecture environment. Make sure you also have homebrew installed in `/opt/homebrew` directory, for arm64 architecture environment. You can do that by just following the installation tutorial on homebrew's home page, or just type this command on your terminal: 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

Now that you have homebrew for both architectures, you can use each one of them as you need to install ruby on the architecture you wish. You can test them by typing:

```
/opt/homebrew/bin/brew doctor
arch -x86_64 /usr/local/homebrew/bin/brew doctor
```

If you have any warnings from homebrew or the message "you're ready to brew" is displayed, it means they are working.

To make it easier to use them, create aliases on your `.zshrc` like that:

```
alias brew86="arch -x86_64 /usr/local/homebrew/bin/brew"
alias brew="/opt/homebrew/bin/brew"
```

save and reload with `source ~/.zshrc`

Now, if you type `brew86` you will be using brew from `/usr/local/homebrew` (x86_64) and if you just type `brew` as you normally would, you will be using brew for arm64 from `/opt/homebrew`. You can test them with by typing `brew86 doctor` and `brew doctor` as well.

After that, let's load our terminal as x86_64 architecture to install rbenv and ruby:

`arch -x86_64 zsh`

To make sure it worked, type `uname -m` in your terminal, and you should expect it to return `x86_64`.

Now just follow as you should from here:

```
brew86 install rbenv
rbenv install 3.0.0 # (or any other version you whish)
rbenv global 3.0.0
rbenv rehash
ruby -v
```

And you should expect ruby to be in the version you just installed, now just run `gem install bundler`, go to your project's root directory and run bundle install.

To switch back your terminal to arm64 (native apple silicon architecture), just type `arch -arm64 zsh`, and by typing `uname -m` it should return `arm64`.

To make it easier to switch between them, just create these two aliases:

```
alias load_x86="arch -x86_64 zsh"
alias load_arm64="arch -arm64 zsh"
```

Now you can use `load_x86` every time you need to install new ruby versions or do anything you need in x86_64 architecture and `load_arm64` to go back to native apple silicon's ARM architecture.

With that, you should be good to go :)

**Comment by Fryguy** [comment]
@djberg96 Can we say this is fixed by https://github.com/djberg96/sys-filesystem/issues/48 and the release of `sys-filesystem` 1.4.1

**Comment by djberg96** [comment]
@Fryguy I would say so, yes.
