### ISSUE TITLE
1.14.0 - Missing compatible architecture on MacOS 11.1/Apple Silicon

### ISSUE THREAD

**Issue by awhitema6937121** [ffi/ffi#860]
I am still seeing the arch missing error with 1.14.0, despite issue 838 being closed.

Installed with `gem install ffi --user-install`

```
[iris:~]% gem list ffi

*** LOCAL GEMS ***

ffi (1.14.0)

[iris:~]% cat test.rb 
#!/usr/bin/ruby

require 'ffi'

module Hello
  extend FFI::Library
  ffi_lib FFI::Library::LIBC
  attach_function :puts, [ :string ], :int
end

Hello.puts("Hello, World")

[iris:~]% ruby test.rb 
Traceback (most recent call last):
	2: from test.rb:3:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffi (LoadError)
	6: from test.rb:3:in `<main>'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	2: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi.rb:4:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
	7: from test.rb:3:in `<main>'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	3: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi.rb:3:in `<top (required)>'
	2: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi.rb:6:in `rescue in <top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle, 0x0009): missing compatible arch in /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle - /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle (LoadError)
zsh: exit 1     ruby test.rb

[iris:~]% lipo /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle -info 
Architectures in the fat file: /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.0/lib/ffi_c.bundle are: x86_64 arm64e 
```

_Originally posted by @awhitema6937121 in https://github.com/ffi/ffi/issues/838#issuecomment-748503655_

**Comment by awhitema6937121** [comment]
This may be related to https://developer.apple.com/forums/thread/652340

I realize the solution may well be "compile your own ruby", but I really don't want to do that if not necessary.

**Comment by larskanis** [comment]
Could you post the output of the following commands with the system ruby?
```sh
$ ruby -v
$ ruby -e 'require "rbconfig"; pp RbConfig::CONFIG' | grep "arm"
```

**Comment by awhitema6937121** [comment]
```
[iris:~]% ruby -e 're "rbconfig"; pp RbConfig::CONFIG' | grep "arm"
[iris:~]% ruby -e 'require "rbconfig"; pp RbConfig::CONFIG' | grep "arm"
 "UNIVERSAL_ARCHNAMES"=>" x86_64=x86_64 arm64e=arm64e",
  " '--prefix=/usr' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--disable-dependency-tracking' '--prefix=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr' '--sysconfdir=/Library/Ruby/Site' '--with-sitedir=/Library/Ruby/Site' '--enable-shared' '--with-arch=x86_64,arm64e' '--with-openssl-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.Internal.sdk/usr/local/libressl' '--without-ext=tk' '--disable-silent-rules' 'ac_cv_func_getcontext=no' 'ac_cv_func_setcontext=no' 'ac_cv_func_utimensat=no' 'ac_cv_c_compiler_gnu=no' 'ac_cv_header_net_if_h=yes' 'av_cv_header_ifaddrs_h=yes' 'rb_cv_pri_prefix_long_long=ll' 'rb_cv_stack_grow_dir_arm64e=-1' 'ac_cv_sizeof_struct_stat_st_size=SIZEOF_OFF_T' 'ac_cv_sizeof_struct_stat_st_blocks=SIZEOF_INT64_T' 'ac_cv_sizeof_struct_stat_st_ino=SIZEOF_UINT64_T' 'CC=/Applications/Xcode.app/Contents/Developer/Toolchains/OSX11.1.xctoolchain/usr/bin/cc' 'CFLAGS=-arch x86_64 -arch arm64e -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS -DUSE_FFI_CLOSURE_ALLOC' 'LDFLAGS=-arch x86_64 -arch arm64e            ' 'CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/OSX11.1.xctoolchain/usr/bin/c++' 'CXXFLAGS=-arch x86_64 -arch arm64e -g -Os -pipe '",
  "-arch x86_64 -arch arm64e             -undefined dynamic_lookup -multiply_defined suppress",

```

I will try to enable arm64e_preview_abi later today (I normally prefer to leave SIP enabled, so I haven't gotten around to trying it), as described in replies to the developer.apple.com link I posted above and will update here as I learn more.

**Comment by awhitema6937121** [comment]
OK, so I did the following:

1. boot into recovery mode, disable SIP `csrutil disable`
2. reboot, enable the arm64 beta ABI `sudo nvram boot-args=-arm64e_preview_abi`
3. rebuild FFI (I noticed that 1.14.1 has been released)
4. rerun the test above.

I get the following output:
```
Traceback (most recent call last):
	2: from test.rb:3:in `<main>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ffi (LoadError)
	6: from test.rb:3:in `<main>'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	2: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.1/lib/ffi.rb:4:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/ffi_c (LoadError)
	7: from test.rb:3:in `<main>'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
	3: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.1/lib/ffi.rb:3:in `<top (required)>'
	2: from /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.1/lib/ffi.rb:6:in `rescue in <top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlsym(0x827da00, Init_ffi_c): symbol not found - /Users/awhitema/.gem/ruby/2.6.0/gems/ffi-1.14.1/lib/ffi_c.bundle (LoadError)
```

I CONSIDER THIS A SUCCESSFUL TEST.

The fact that I'm now getting a symbol error rather than "no arch found" means that dlopen() is working correctly once I enabled the ABI. I don't think there's a solution to this as long all of the following are true
1. system ruby does supports the arm64e and x86_64 but **not** arm64 ABI
2. user-compiled binaries targeting arm64e are disabled

Once Apple allows arm64e to everybody, I suspect there's going to be more work to do to support it, but for now this issue might be a "can't fix" situation.

**Comment by awhitema6937121** [comment]
FWIW, I've submitted to the black hole that is Apple developer feedback regarding this issue.

**Comment by IsaacDempsey** [comment]
@awhitema6937121 Is there any update on this from the apple side?

**Comment by awhitema6937121** [comment]
@IsaacDempsey , I'm not a registered developer so I wouldn't get updates from Apple, but a quick google seems to indicate it's still a problem. I will run a hello world test later tonight once I finish my day job and if it runs, I'll provide an update (if it doesn't run, there's no change).

arm64**e** also enables pointer authentication, so I suspect that once you are able to target the platform, there may be other challenges there. Sorry I'm not much help. I'm a sysadmin, not a programmer.

**Comment by BrandonTeixeiraStream** [comment]
Hi is there any update on this?
