### ISSUE TITLE
1.14.2 arm64 / m1 issue: ffi_c.bundle, 9: no suitable image found.

### ISSUE THREAD

**Issue by SimonHausdorf** [ffi/ffi#878]
I installed ffi with the following command: `arch -x86_64 gem install ffi`

now I am running `pod install`
```
LoadError - dlopen(/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
	/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle: mach-o, but wrong architecture
	/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle: mach-o, but wrong architecture - /Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi_c.bundle
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/sim/.rbenv/versions/3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Users/sim/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Users/sim/.rbenv/versions/3.0.0/bin/pod:23:in `load'
/Users/sim/.rbenv/versions/3.0.0/bin/pod:23:in `<main>'

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.
```

I tried to run Terminal with rosetta 2 but it did not help. I also tried to install cocoapods via `arch -x86_64 gem install cocoapods` but same issue.

**Comment by BrainBuzzer** [comment]
Has anybody found a fix or workaround for this?

**Comment by BrainBuzzer** [comment]
Found a temporary solution.
1. Get a new terminal with rosetta 2 turned on.
2. Install Homebrew (Even if you have it installed already. This one's binary file will be installed under `/usr/local` directory)
3. `/usr/local/Homebrew/bin/brew install cocoapods`
4. `/usr/local/Cellar/cocoapods/1.10.1/bin/pod install` (You may need to change the version depending on when you read this)

Enjoy 🥳

**Comment by xmarkclx** [comment]
On my end I got this solved by adding arch -x86_64 to everything
arch -x86_64 brew install cocoapods

**Comment by thearijain** [comment]
<img width="531" alt="Screen Shot 2021-09-25 at 6 40 55 PM" src="https://user-images.githubusercontent.com/52765009/134787633-a97f67aa-3a69-4fde-98fe-ec8e5184b40c.png">

Can you please explain how to avoid this error? I am on an M1 Macbook. I also can't download Rosetta 2..

**Comment by meerismail** [comment]
1. Just right click on your terminal then go to options then click on show in finder
2. Then right-click on the terminal and go to "Get Info"
3.  In info you will see the "Open using Rosetta" check that and then you can run that commands.

**Comment by meerismail** [comment]
> <img alt="Screen Shot 2021-09-25 at 6 40 55 PM" width="531" src="https://user-images.githubusercontent.com/52765009/134787633-a97f67aa-3a69-4fde-98fe-ec8e5184b40c.png">
> 
> Can you please explain how to avoid this error? I am on an M1 Macbook. I also can't download Rosetta 2..

1. Just right click on your terminal then go to options then click on show in finder
2. Then right-click on the terminal and go to "Get Info"
3.  In info you will see the "Open using Rosetta" check that and then you can run that commands.

**Comment by passportsystems** [comment]
<img width="1419" alt="Screen Shot 2021-10-03 at 12 03 25 am" src="https://user-images.githubusercontent.com/91771166/135719829-8d92976f-4169-4f02-acb7-669c8548067a.png">

Does anyone know what this error means?

**Comment by southwolf** [comment]
Or you can check my PR
https://github.com/ffi/ffi/pull/936

if you want to use native arm64 version
