### ISSUE TITLE
Ruby libffi.so.7: cannot open shared object file:

### ISSUE THREAD

**Issue by abhinavDhulipala** [ffi/ffi#881]
Hi, I'm trying to run a legacy rails app but I cannot run any of the legacy tests or the application itself because I keep running into this error
```
         ....
	 3: from ~/.rvm/gems/ruby-2.6.6/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require'
	 2: from ~/.rvm/gems/ruby-2.6.6/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	 1: from ~/.rvm/gems/ruby-2.6.6/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `block in require'
~/.rvm/gems/ruby-2.6.6/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:274:in `require': libffi.so.7: cannot open shared object file: No such file or directory - ~/.rvm/gems/ruby-2.6.6/gems/ffi-1.11.2/lib/ffi_c.so (LoadError)
```

I have checked the file seems to very much exist
```
$ ls ~/.rvm/gems/ruby-2.6.6/gems/ffi-1.11.2/lib/
ffi ffi_c.so ffi.rb
```

After doing some further investigation I found a couple of posts suggesting I didn't have to libffi-devel successfully installed. But after running:
```
$ rpm -qa | grep libffi
libffi-3.0.13-18.amzn2.0.2.x86_64
libffi-devel-3.0.13-18.amzn2.0.2.x86_64
```
I quickly ruled that out as the problem as the requisite packages are installed. As you could probably glean, I am running the latest version of Amazon Linux 2( A descendant of Centos 7/8 I believe). More precisely, 
```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Amazon
Description:    Amazon Linux release 2 (Karoo)
Release:        2
Codename:       Karoo
```
I've been digging around for a couple of hours and can't seem to find a solution that works? I tried uninstalling and reinstalling the gem manually, but as it is a dependency of a gem I use, I don't have direct control over whether I can use it or not. I also made yum was fully up to date.

Thanks for your patience and time,

Abhi

**Comment by johansenja** [comment]
I ran into the same problem in github actions, and it coincided with github updating `ubuntu-latest` from 18.04 to 20.04 (https://github.com/actions/virtual-environments/issues/1816). For anyone else encountering this, the workaround for us was just to update `ubuntu-latest` to `ubuntu-18.04` in the action's yml

**Comment by filipewl** [comment]
> I ran into the same problem in github actions, and it coincided with github updating `ubuntu-latest` from 18.04 to 20.04 ([actions/virtual-environments#1816](https://github.com/actions/virtual-environments/issues/1816)). For anyone else encountering this, the workaround for us was just to update `ubuntu-latest` to `ubuntu-18.04` in the action's yml

I ran into this same issue a few weeks ago and did exactly the same when I noticed GH Action builds started using a newer version of Ubuntu. That was the only change since we hadn't changed anything code-wise. Reverting it `ubuntu-18.04` did the trick! Waiting to retry `ubuntu-latest` (20.04) to see if it's been fixed there.

**Comment by bossm0n5t3r** [comment]
Thank you all, you guys! It works very well! 😄

**Comment by ab-ood44** [comment]
- [ ] LoadError****

**Comment by cooperka** [comment]
Instead of downgrading to Ubuntu 18, you can simply bust your cache as noted by Croaky [on the GitHub forum](https://github.community/t/libffi-so-6-error-on-ubuntu-latest/165571/2?u=cooperka):

```diff
          path: vendor/bundle
-         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
+         key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
-           ${{ runner.os }}-gems-
+           ${{ runner.os }}-gems-v2-
```

**Comment by viktorianer** [comment]
I'm also using `ffi (1.15.0)`, and after upgrading to `alpine 3.13` from `3.11` docker image for Rails 6 on Ruby 2.6.6. I install `libffi-dev` with `apk` as always, and got this error. 

```
99: from bin/rails:4:in `<main>'
98: from /usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
...
/usr/local/bundle/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': Error loading shared library libffi.so.6: No such file or directory (needed by /usr/local/bundle/gems/ffi-1.15.0/lib/ffi_c.so) - /usr/local/bundle/gems/ffi-1.15.0/lib/ffi_c.so (LoadError)
```

In this image is `/usr/lib/libffi.so.7` present, but not required `library libffi.so.6`.

```
/app # ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux-musl]
/app # ls -la /usr/lib/libffi.so*
lrwxrwxrwx    1 root     root            15 Apr  1 12:55 /usr/lib/libffi.so -> libffi.so.7.1.0
lrwxrwxrwx    1 root     root            15 Apr  1 12:55 /usr/lib/libffi.so.7 -> libffi.so.7.1.0
-rwxr-xr-x    1 root     root         38880 May  6  2020 /usr/lib/libffi.so.7.1.0
```

I had to downgrade to `alpine 3.11` Ruby image, and also to `nodejs 12.22` and `yarn 1.19`, to make it work again.

**Comment by dorianmariefr** [comment]
In my case adding `gem "ffi"` to my `Gemfile` fixed it, e.g. https://stackoverflow.com/q/65000467/12544391

**Comment by dranitski** [comment]
arch linux, updated and got same problem.

```
gem uninstall ffi
gem install ffi
bundle add ffi
bundle install
```
helped me

**Comment by 0xAsh** [comment]
> arch linux, updated and got same problem.
> 
> ```
> gem uninstall ffi
> gem install ffi
> bundle add ffi
> bundle install
> ```
> 
> helped me

Artix user checking in. This fixed the issue for me as well :) Thanks.

**Comment by kcorbfbt** [comment]
Still having a similar issue to this one with Ubuntu/Windows/rbenv/ruby 3.0.0.

Recently moved to rbenv from rvm and am getting the following error:

/home/xxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': /usr/lib/x86_64-linux-gnu/libffi.so.7: version `LIBFFI_CLOSURE_8.0' not found (required by /home/xxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi_c.so) - /home/xxx/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi_c.so (LoadError) 

my /usr/lib/x86_64-linux-gnu/libffi.so.7 does exist:

`ls /usr/lib/x86_64-linux-gnu/libffi.so*`
/usr/lib/x86_64-linux-gnu/libffi.so  /usr/lib/x86_64-linux-gnu/libffi.so.7  /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0  /usr/lib/x86_64-linux-gnu/libffi.so.8

I have tried reinstalling rbenv, ruby, ffi, and the libffi files on ubuntu. But I am not sure if the version 'LIBFFI_CLOSURE_8.0' is something that I am actually missing or if it just can't find it. Is that something I need to download?

**Comment by Andrii-RubyGarage** [comment]
> arch linux, updated and got same problem.
> 
> ```
> gem uninstall ffi
> gem install ffi
> bundle add ffi
> bundle install
> ```
> 
> helped me

Thanks!!!

**Comment by estebansa19** [comment]
> Artix user checking in. This fixed the issue for me as well :) Thanks.

Thanks!

**Comment by edsonlima** [comment]
In my case, updating FFi to 1.15.4 solved the issue.

**Comment by jlosito** [comment]
Ran a `bundle pristine ffi` on Fedora and it seemed to help.

**Comment by brodock** [comment]
FYI there is a bundler issue causing library loading issues, when using the global cache flag: https://github.com/rubygems/rubygems/issues/6616
