### ISSUE TITLE
 Could not open library 'c': dlopen image not found. (LoadError)

### ISSUE THREAD

**Issue by bentxt** [ffi/ffi#918]
Hi

I try to run the following simple ffi example on my macbook:

ProductName:	macOS
ProductVersion:	11.6

```
ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

gem -v
3.2.22

clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Volumes/sdapfs/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

ffi.rb
```
require 'ffi'
module MyLib
  extend FFI::Library
  ffi_lib 'c'
  attach_function :puts, [ :string ], :int
end
MyLib.puts 'Hello, World using libc!'
```

because ffi is not installed, the following error thrown:
$ ruby ffi.rb
```
<internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- ffi (LoadError)
	from <internal:/usr/local/Cellar/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from ffi.rb:1:in `<main>'
```

lets install the ffi module:
$ gem install ffi
```
Fetching ffi-1.15.4.gem
Building native extensions. This could take a while...
Successfully installed ffi-1.15.4
Parsing documentation for ffi-1.15.4
Installing ri documentation for ffi-1.15.4
Done installing documentation for ffi after 10 seconds
1 gem installed
```

And here is the error, despite the ffi module beeing succesfully installed:
$ ruby ffi.rb
```
/usr/local/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'c': dlopen(c, 5): image not found. (LoadError)
Could not open library 'libc.dylib': dlopen(libc.dylib, 5): image not found
	from /usr/local/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `map'
	from /usr/local/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `ffi_lib'
	from ffi.rb:5:in `<module:MyLib>'
	from ffi.rb:3:in `<main>'
```

**Comment by bluetechsky** [comment]
I got exact same problem. 
Have you solved that?

**Comment by bluetechsky** [comment]
@bentxt 
I fixed by changing line 80 in library.rb:
/usr/local/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/lib/ffi/library.rb

-    LIBC = FFI::Platform::LIBC
+    LIBC = '/usr/lib/libc.dylib'

It works! 
Please make sure "/usr/lib/libc.dylib" is existing in your Mac OS
(Got from here: https://github.com/ffi/ffi/issues/461#issuecomment-149253757)
