### ISSUE TITLE
`block in ffi_lib': Could not open library 'kernel32'`

### ISSUE THREAD

**Issue by ciscolive** [ffi/ffi#924]
```ruby
nel_require.rb:23:in `require'
        13: from /usr/local/rvm/gems/ruby-2.7.5/gems/win32-security-0.5.0/lib/win32/security.rb:4:in `<main>'
        12: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        11: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        10: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
         9: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         8: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         7: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
         6: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         5: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         4: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-win32-extensions-1.0.4/lib/ffi/win32/extensions.rb:65:in `<main>'
         3: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-win32-extensions-1.0.4/lib/ffi/win32/extensions.rb:68:in `<module:FFI>'
         2: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `ffi_lib'
         1: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `map'
/usr/local/rvm/gems/ruby-2.7.5/gems/ffi-1.15.4/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'kernel32': kernel32: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libkernel32.so': libkernel32.so: cannot open shared object file: No such file or directory
```

**Comment by ciscolive** [comment]
```ruby
full stack

Traceback (most recent call last):
        72: from bin/rails:4:in `<main>'
        71: from bin/rails:4:in `load'
        70: from /data/ruby/mojo/bin/spring:9:in `<top (required)>'
        69: from /data/ruby/mojo/bin/spring:9:in `tap'
        68: from /data/ruby/mojo/bin/spring:12:in `block in <top (required)>'
        67: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        66: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
        65: from /usr/local/rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/binstub.rb:11:in `<top (required)>'
        64: from /usr/local/rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/binstub.rb:11:in `load'
        63: from /usr/local/rvm/gems/ruby-2.7.5/gems/spring-3.0.0/bin/spring:49:in `<top (required)>'
        62: from /usr/local/rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client.rb:30:in `run'
        61: from /usr/local/rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client/command.rb:7:in `call'
        60: from /usr/local/rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client/rails.rb:28:in `call'
        59: from /usr/local/rvm/gems/ruby-2.7.5/gems/spring-3.0.0/lib/spring/client/rails.rb:28:in `load'
        58: from /data/ruby/mojo/bin/rails:7:in `<top (required)>'
        57: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        56: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        55: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        54: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        53: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        52: from /usr/local/rvm/gems/ruby-2.7.5/gems/railties-6.1.4.1/lib/rails/commands.rb:18:in `<main>'
        51: from /usr/local/rvm/gems/ruby-2.7.5/gems/railties-6.1.4.1/lib/rails/command.rb:48:in `invoke'
        50: from /usr/local/rvm/gems/ruby-2.7.5/gems/railties-6.1.4.1/lib/rails/command/base.rb:69:in `perform'
        49: from /usr/local/rvm/gems/ruby-2.7.5/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        48: from /usr/local/rvm/gems/ruby-2.7.5/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        47: from /usr/local/rvm/gems/ruby-2.7.5/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        46: from /usr/local/rvm/gems/ruby-2.7.5/gems/railties-6.1.4.1/lib/rails/commands/server/server_command.rb:135:in `perform'
        45: from /usr/local/rvm/gems/ruby-2.7.5/gems/railties-6.1.4.1/lib/rails/commands/server/server_command.rb:135:in `tap'
        44: from /usr/local/rvm/gems/ruby-2.7.5/gems/railties-6.1.4.1/lib/rails/commands/server/server_command.rb:138:in `block in perform'
        43: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        42: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        41: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        40: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        39: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        38: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        37: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        36: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        35: from /data/ruby/mojo/config/application.rb:22:in `<main>'
        34: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler.rb:174:in `require'
        33: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
        32: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
        31: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
        30: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
        29: from /usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
        28: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        27: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        26: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        25: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        24: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        23: from /usr/local/rvm/gems/ruby-2.7.5/gems/win32-security-0.5.0/lib/win32-security.rb:1:in `<main>'
        22: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `require_relative'
        21: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        20: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        19: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
        18: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        17: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        16: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
        15: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        14: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        13: from /usr/local/rvm/gems/ruby-2.7.5/gems/win32-security-0.5.0/lib/win32/security.rb:4:in `<main>'
        12: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `require'
        11: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:299:in `load_dependency'
        10: from /usr/local/rvm/gems/ruby-2.7.5/gems/activesupport-6.1.4.1/lib/active_support/dependencies.rb:332:in `block in require'
         9: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         8: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         7: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:100:in `register'
         6: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         5: from /usr/local/rvm/gems/ruby-2.7.5/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         4: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-win32-extensions-1.0.4/lib/ffi/win32/extensions.rb:65:in `<main>'
         3: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-win32-extensions-1.0.4/lib/ffi/win32/extensions.rb:68:in `<module:FFI>'
         2: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `ffi_lib'
         1: from /usr/local/rvm/gems/ruby-2.7.5/gems/ffi-1.15.4/lib/ffi/library.rb:99:in `map'
/usr/local/rvm/gems/ruby-2.7.5/gems/ffi-1.15.4/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'kernel32': kernel32: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libkernel32.so': libkernel32.so: cannot open shared object file: No such file or directory
```

**Comment by ciscolive** [comment]
solved
