### ISSUE TITLE
Windows 64-bit Ruby 3.0.3 [x64-mingw32] MemoryPointer Segmentation Fault with ffi (1.11.3)

### ISSUE THREAD

**Issue by tsujp** [ffi/ffi#928]
I am running on Windows 10 64-bit release `10.0.19041.1151` using `ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]` installed via RubyInstaller.

I'm using ffi (1.11.3) and the following program will cause a segmentation fault when I'd expect it to return the memory pointer. Using 32 bit Ruby from RubyInstaller works fine, but I'd like to be using 64-bit.

```ruby
# frozen_string_literal: true
require 'ffi'

this_will_fail = FFI::MemoryPointer.new(1024)
```

Trace

```
C:\Ruby30-x64\bin\ruby.exe C:/Users/tsujp/Desktop/ruby_experiments/main.rb
C:/Users/tsujp/Desktop/ruby_experiments/main.rb:4: [BUG] Segmentation fault
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0015 e:000014 CFUNC  :initialize
c:0003 p:---- s:0012 e:000011 CFUNC  :new
c:0002 p:0023 s:0007 E:000f38 EVAL   C:/Users/tsujp/Desktop/ruby_experiments/main.rb:4 [FINISH]
c:0001 p:0000 s:0003 E:001e80 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
C:/Users/tsujp/Desktop/ruby_experiments/main.rb:4:in `<main>'
C:/Users/tsujp/Desktop/ruby_experiments/main.rb:4:in `new'
C:/Users/tsujp/Desktop/ruby_experiments/main.rb:4:in `initialize'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(NtWaitForSingleObject+0x14) [0x00007ff801b8cdf4]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x8e) [0x00007fffff5f1a5e]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_vm_bugreport+0x5ab) [0x00007fff89e6bb2b]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_bug_for_fatal_signal+0x88) [0x00007fff89c6fd88]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_scheduler_io_write+0x2ee) [0x00007fff89dbe31e]
 [0x00007ff754321f42]
C:\WINDOWS\System32\msvcrt.dll(_C_specific_handler+0x98) [0x00007ff801447ff8]
C:\WINDOWS\SYSTEM32\ntdll.dll(_chkstk+0x11f) [0x00007ff801b920cf]
C:\WINDOWS\SYSTEM32\ntdll.dll(RtlRaiseException+0x434) [0x00007ff801b41454]
C:\WINDOWS\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x2e) [0x00007ff801b90bfe]
C:\WINDOWS\System32\msvcrt.dll(memset+0x78) [0x00007ff8014946f8]
 [0x00007fffd03e0cc5]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_vm_invoke_proc+0x230) [0x00007fff89e53fc0]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_check_funcall_with_hook+0x736) [0x00007fff89e579f6]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_funcallv_kw+0x62) [0x00007fff89e58522]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_obj_call_init_kw+0x66) [0x00007fff89c7b6d6]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_class_new_instance_pass_kw+0x65) [0x00007fff89d26295]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_error_arity+0x266) [0x00007fff89e42f66]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_vm_localjump_error+0x387) [0x00007fff89e4d627]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_add_method+0x15a) [0x00007fff89e59caa]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_vm_exec+0xaa2) [0x00007fff89e4eb42]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(rb_call_end_proc+0x34c4) [0x00007fff89c778d4]
C:\Ruby30-x64\bin\x64-msvcrt-ruby300.dll(ruby_run_node+0xa5) [0x00007fff89c79b25]
 [0x00007ff754322809]
 [0x00007ff7543213b1]
 [0x00007ff7543214e6]
C:\WINDOWS\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007ff800be7034]

-- Other runtime information -----------------------------------------------

* Loaded script: C:/Users/tsujp/Desktop/ruby_experiments/main.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 ruby2_keywords.rb
    5 C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/enc/encdb.so
    6 C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/enc/trans/transdb.so
    7 C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/rbconfig.rb
    8 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/compatibility.rb
    9 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/defaults.rb
   10 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/deprecate.rb
   11 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/errors.rb
   12 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/exceptions.rb
   13 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/basic_specification.rb
   14 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/stub_specification.rb
   15 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/text.rb
   16 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/user_interaction.rb
   17 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/specification_policy.rb
   18 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/util/list.rb
   19 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/platform.rb
   20 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/version.rb
   21 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/requirement.rb
   22 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/specification.rb
   23 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/util.rb
   24 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/dependency.rb
   25 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_gem.rb
   26 C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/monitor.so
   27 C:/Ruby30-x64/lib/ruby/3.0.0/monitor.rb
   28 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb
   29 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_warn.rb
   30 C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/singleton.rb
   31 C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime.rb
   32 C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/msys2_installation.rb
   33 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/path_support.rb
   34 C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/fiddle.so
   35 C:/Ruby30-x64/lib/ruby/3.0.0/fiddle/closure.rb
   36 C:/Ruby30-x64/lib/ruby/3.0.0/fiddle/function.rb
   37 C:/Ruby30-x64/lib/ruby/3.0.0/fiddle/version.rb
   38 C:/Ruby30-x64/lib/ruby/3.0.0/fiddle.rb
   39 C:/Ruby30-x64/lib/ruby/site_ruby/3.0.0/ruby_installer/runtime/dll_directory.rb
   40 C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/enc/utf_16le.so
   41 C:/Ruby30-x64/lib/ruby/3.0.0/x64-mingw32/enc/trans/utf_16_32.so
   42 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/defaults/operating_system.rb
   43 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems.rb
   44 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/version.rb
   45 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/core_ext/name_error.rb
   46 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/levenshtein.rb
   47 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/jaro_winkler.rb
   48 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checker.rb
   49 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   50 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   51 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checkers/name_error_checkers.rb
   52 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checkers/method_name_checker.rb
   53 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checkers/key_error_checker.rb
   54 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checkers/null_checker.rb
   55 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/tree_spell_checker.rb
   56 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/spell_checkers/require_path_checker.rb
   57 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean/formatters/plain_formatter.rb
   58 C:/Ruby30-x64/lib/ruby/3.0.0/did_you_mean.rb
   59 C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/bundler_version_finder.rb
   60 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi_c.so
   61 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/platform.rb
   62 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/data_converter.rb
   63 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/types.rb
   64 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/library.rb
   65 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/errno.rb
   66 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/pointer.rb
   67 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/memorypointer.rb
   68 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/struct_layout.rb
   69 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/struct_layout_builder.rb
   70 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/struct_by_reference.rb
   71 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/struct.rb
   72 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/union.rb
   73 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/managedstruct.rb
   74 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/callback.rb
   75 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/io.rb
   76 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/autopointer.rb
   77 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/variadic.rb
   78 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/enum.rb
   79 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi/ffi.rb
   80 C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/ffi-1.11.3/lib/ffi.rb


Process finished with exit code 3
```

**Comment by tsujp** [comment]
Argh I suck, I should've double checked I was on the latest FFI version... using 1.15.4 works. Sorry, I'll close this issue.
