### ISSUE TITLE
Building native extension failed because lack of necessary libraries and/or headers.

### ISSUE THREAD

**Issue by darkRaspberry** [ffi/ffi#930]
### What happened
During installing a gem `ffi` doesn't install and through error. Further it doesn't exactly tell what is the error and how to solve it. Just saying lacks necessary headers and libraries. I read the README.md and still didn't understand. 

```
 ~  ➜ gem install bundler jekyll
Successfully installed bundler-2.3.4
Parsing documentation for bundler-2.3.4
Done installing documentation for bundler after 0 seconds
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    current directory: /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/gems/ffi-1.15.4/ext/ffi_c
/home/linuxbrew/.linuxbrew/opt/ruby/bin/ruby -I /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0 -r ./siteconf20220104-16308-segoh8.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/mkmf.rb:471:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/mkmf.rb:564:in `try_link0'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/mkmf.rb:582:in `try_link'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/mkmf.rb:684:in `try_ldflags'
	from /home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib/ruby/3.0.0/mkmf.rb:1851:in `pkg_config'
	from extconf.rb:9:in `system_libffi_usable?'
	from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/gems/ffi-1.15.4 for inspection.
Results logged to /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4/gem_make.out
1 gem installed

```

mkmf.log file is 
```
 ~  ➜ cat /home/linuxbrew/.linuxbrew/lib/ruby/gems/3.0.0/extensions/x86_64-linux/3.0.0/ffi-1.15.4/mkmf.log
"pkg-config --exists libffi"
| pkg-config --libs libffi
=> "-lffi\n"
"gcc-5 -o conftest -I/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/include/ruby-3.0.0/x86_64-linux -I/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/include/ruby-3.0.0/ruby/backward -I/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/include/ruby-3.0.0 -I.  -I/home/linuxbrew/.linuxbrew/opt/libyaml/include -I/home/linuxbrew/.linuxbrew/opt/openssl@1.1/include -I/home/linuxbrew/.linuxbrew/opt/readline/include   -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wno-maybe-uninitialized  -fPIC conftest.c  -L. -L/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib -L/home/linuxbrew/.linuxbrew/opt/libyaml/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/libyaml/lib -L/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib -L/home/linuxbrew/.linuxbrew/opt/readline/lib -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/readline/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L/home/linuxbrew/.linuxbrew/opt/libyaml/lib  -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/libyaml/lib -L/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib  -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib -L/home/linuxbrew/.linuxbrew/opt/readline/lib  -Wl,-rpath,/home/linuxbrew/.linuxbrew/opt/readline/lib     -Wl,-rpath,/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib -L/home/linuxbrew/.linuxbrew/Cellar/ruby/3.0.3/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

```

### What do you expect
Building native extension doesn't fail. Further
`ffi` should be able to install or At Least tell what is missing and need to be fulfilled.

**Comment by darkRaspberry** [comment]
After searching a bunch of stackoverflow. I installed `ubuntu-dev-tools` A total of 192 libs.

```
The following NEW packages will be installed:
  arch-test brz brz-debian bzr bzr-builddeb debian-archive-keyring
  debian-keyring debootstrap devscripts diffstat docutils-common dput
  eatmydata genisoimage gettext intltool-debian libaliased-perl
  libapt-pkg-perl libarchive-zip-perl libarray-intspan-perl
  libb-hooks-endofscope-perl libb-hooks-op-check-perl libcapture-tiny-perl
  libclass-data-inheritable-perl libclass-method-modifiers-perl
  libclass-xsaccessor-perl libcommon-sense-perl libconfig-tiny-perl
  libconst-fast-perl libcontextual-return-perl libcpanel-json-xs-perl
  libdata-dpath-perl libdata-messagepack-perl libdata-optlist-perl
  libdata-validate-domain-perl libdevel-callchecker-perl libdevel-size-perl
  libdevel-stacktrace-perl libdistro-info-perl libdynaloader-functions-perl
  libeatmydata1 libemail-address-xs-perl libexception-class-perl
  libexporter-tiny-perl libfile-chdir-perl libfile-dirlist-perl
  libfile-find-rule-perl libfile-homedir-perl libfile-touch-perl
  libfile-which-perl libfont-ttf-perl libgetopt-long-descriptive-perl
  libgit-wrapper-perl libgitlab-api-v4-perl libhash-fieldhash-perl
  libhtml-html5-entities-perl libhttp-tiny-multipart-perl libimport-into-perl
  libio-prompter-perl libio-pty-perl libio-string-perl libipc-run-perl
  libipc-run3-perl libiterator-perl libiterator-util-perl libjson-maybexs-perl
  libjson-perl libjson-xs-perl liblist-compare-perl liblist-moreutils-perl
  liblist-moreutils-xs-perl liblist-someutils-perl liblist-someutils-xs-perl
  liblist-utilsby-perl liblog-any-adapter-screen-perl liblog-any-perl
  libmarkdown2 libmodule-implementation-perl libmodule-runtime-perl
  libmoo-perl libmoox-aliases-perl libmoox-struct-perl libmouse-perl
  libnamespace-autoclean-perl libnamespace-clean-perl libnet-domain-tld-perl
  libnumber-compare-perl libnumber-range-perl libobject-id-perl
  libpackage-stash-perl libpackage-stash-xs-perl libparams-classify-perl
  libparams-util-perl libparams-validate-perl libpath-iterator-rule-perl
  libpath-tiny-perl libperlio-gzip-perl libpod-constants-perl
  libpod-parser-perl libproc-processtable-perl libre-engine-re2-perl libre2-9
  libreadonly-perl libref-util-perl libref-util-xs-perl
  libregexp-pattern-license-perl libregexp-pattern-perl librole-tiny-perl
  libsereal-decoder-perl libsereal-encoder-perl libsort-key-perl
  libsort-versions-perl libstrictures-perl libstring-copyright-perl
  libstring-escape-perl libstring-shellquote-perl libsub-exporter-perl
  libsub-exporter-progressive-perl libsub-identify-perl libsub-install-perl
  libsub-name-perl libsub-quote-perl libsys-cpuaffinity-perl
  libterm-readkey-perl libtext-glob-perl libtext-levenshteinxs-perl
  libtext-markdown-discount-perl libtext-xslate-perl libtime-duration-perl
  libtime-moment-perl libtype-tiny-perl libtype-tiny-xs-perl
  libtypes-serialiser-perl libunicode-utf8-perl libvariable-magic-perl
  libwant-perl libxdelta2 libxml-libxml-perl libxml-namespacesupport-perl
  libxml-sax-base-perl libxml-sax-expat-perl libxml-sax-perl
  libyaml-libyaml-perl licensecheck lintian lzip lzop patchutils pbuilder
  pbzip2 pixz pristine-tar python3-breezy python3-bs4 python3-configobj
  python3-debianbts python3-debmutate python3-deprecated python3-dns
  python3-docutils python3-dulwich python3-fastimport python3-github
  python3-gitlab python3-gpg python3-html5lib python3-lxml python3-magic
  python3-markdown python3-merge3 python3-patiencediff python3-pycurl
  python3-pygments python3-pysimplesoap python3-reportbug python3-roman
  python3-soupsieve python3-toml python3-tomlkit python3-tr
  python3-ubuntutools python3-unidiff python3-upstream-ontologist
  python3-webencodings python3-wrapt quilt reportbug t1utils ubuntu-dev-tools
  wdiff xdelta xdelta3
```
But still I can't understand what is missing. Neither I can understand this error.

**Comment by darkRaspberry** [comment]
Further investigation suggest this is not totally related to `ffi` and some bit to ruby. 
If ruby is installed with homebrew(or linuxbrew) then this error happens no matter how you do.

If anyone go ahead and install `rbenv` and then try to install it. Then it will be successfully installed.

**Comment by larskanis** [comment]
The `mkmf.log` shows that a compiler named `gcc-5` is expected, but isn't available any longer. This was probably the compiler in use while installing ruby, but no longer when installing ffi.

**Comment by darkRaspberry** [comment]
I tried fresh install on docker container and google cloud images, I don't see how that was unavailable. Homebrew automatically install `gcc-5` when you install `brew install gcc`.

Anyway I moved to rbenv and it works flawless. Thanks so much you guys are awesome.
