### ISSUE TITLE
Error installing ffi: 	ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by andesappal** [ffi/ffi#937]
kevin@Kevins-MacBook-Air ~ % sudo arch -x86_64 gem install ffi
Building native extensions. This could take a while...
ERROR:  Error installing ffi:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220124-41484-17xcahw.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--enable-system-libffi
	--disable-system-libffi
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:534:in `with_werror'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
	from extconf.rb:10:in `system_libffi_usable?'
	from extconf.rb:42:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.15.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.15.5/gem_make.out
kevin@Kevins-MacBook-Air ~ %

**Comment by southwolf** [comment]
`You have to install development tools first.`

Could you check if you have XCode Command Line Tools installed?
by running `xcode-select --install`

**Comment by sryze** [comment]
Same error on Catalina. Development tools are already installed.

```
$ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by sryze** [comment]
It seems that the build script is using the wrong include directory - universal-darwin19 instead of universal-darwin20. Creating a link for that directory fixed the issue for me.

```
sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19
```

**Comment by ajith-acumen** [comment]
> ```
> kevin@Kevins-MacBook-Air ~ % sudo arch -x86_64 gem install ffi
> Building native extensions. This could take a while...
> ERROR:  Error installing ffi:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220124-41484-17xcahw.rb extconf.rb
> checking for ffi.h... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
> 	--with-opt-dir
> 	--without-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
> 	--with-ffi_c-dir
> 	--without-ffi_c-dir
> 	--with-ffi_c-include
> 	--without-ffi_c-include=${ffi_c-dir}/include
> 	--with-ffi_c-lib
> 	--without-ffi_c-lib=${ffi_c-dir}/lib
> 	--enable-system-libffi
> 	--disable-system-libffi
> 	--with-libffi-config
> 	--without-libffi-config
> 	--with-pkg-config
> 	--without-pkg-config
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:534:in `with_werror'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
> 	from extconf.rb:10:in `system_libffi_usable?'
> 	from extconf.rb:42:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.15.5/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5 for inspection.
> Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.15.5/gem_make.out
> kevin@Kevins-MacBook-Air ~ % 
> ```

**Comment by ajith-acumen** [comment]
i hot same error how to fix it

**Comment by jabiel** [comment]
Thanks! In my case it was creating a link universal-darwin21 which directs to universal-darwin22


> It seems that the build script is using the wrong include directory - universal-darwin19 instead of universal-darwin20. Creating a link for that directory fixed the issue for me.
> 
> ```
> sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19
> ```

**Comment by funky-monkey** [comment]
Having the same issue. Adding the symlink did not work. 
I was just reading [this issue](https://github.com/ffi/ffi/issues/950) and OP hinted at removing spaces in the build path. 

> `topdir` and `arch_hrdir` seem to escape or quote the path, but `includedir` doesn't, so I'm assuming that's where the issue lies.

Removing the space in the pathname solved my issue.

**Comment by hefler** [comment]
Solved by removing any whitespace character as  pointed out by @funky-monkey
> Removing the space in the pathname solved my issue.

PS: I'm on an Mac Intel, so I don't think it's related to different chip architectures

**Comment by mareFernando03** [comment]
> It seems that the build script is using the wrong include directory - universal-darwin19 instead of universal-darwin20. Creating a link for that directory fixed the issue for me.
> 
> ```
> sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin20 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19
> ```

How can I know wich directory i need include?

**Comment by DigitalSolomon** [comment]
Here's what I did, hopefully this helps:

1. Open up the `mkmf.log` file mentioned in the output from the failed `ffi` installation. For me, this was at `/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/ffi-1.15.5/mkmf.log`.
2. Look at the paths being referenced in the `xcrun clang` command, nearby the `-I` parameter. For me this is `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21`
3. Navigate in Finder to the directory that is the parent of the `universal-darwinXX` directory to see what files you have in there (or `cd`/`ls`). For me, I could see that I have a directory named `universal-darwin22` and none named `universal-darwin21` as mentioned in the `mkmf.log`.
4. Execute a command that creates a symbolic link named after the erroneous path used in the build script (e.g. `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21` in my case), and symlink it to the correct path (in my case `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin22`)
5. Install `ffi` again and it should work. For me, I used this command: `arch -x86_64 sudo gem install ffi`

I hope this can help some people.

**Comment by chozandrias76** [comment]
I have a user who ran into this issue today on his Mac M1 based computer. The only steps that were required to fix this were running xcode-select --install and bundle install again.

**Comment by KrisLau** [comment]
ok so i figured it out i had to do `gem install cocoapods` cause it wasn't detecting the brew installed one

**Comment by harisbaig100** [comment]
If you encounter the error "An error occurred while installing ffi (1.15.5), and Bundler cannot continue" while running the command npx react-native@latest init AwesomeProject, try initializing your project in a folder directory without spaces. For example, run npx react-native init on the "Desktop" directory, which usually doesn't have spaces in its path. This should resolve the issue.

**Comment by yusam123** [comment]
> Here's what I did, this might help you @mareFernando03 :
> 
> 1. Open up the `mkmf.log` file mentioned in the output from the failed `ffi` installation. For me, this was at `/Library/Ruby/Gems/2.6.0/extensions/universal-darwin-21/2.6.0/ffi-1.15.5/mkmf.log`.
> 2. Look at the paths being referenced in the `xcrun clang` command, nearby the `-I` parameter. For me this is `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21`
> 3. Navigate in Finder to the directory that is the parent of the `universal-darwinXX` directory to see what files you have in there (or `cd`/`ls`). For me, I could see that I have a directory named `universal-darwin22` and none named `universal-darwin21` as mentioned in the `mkmf.log`.
> 4. Execute a command that creates a symbolic link named after the erroneous path used in the build script (e.g. `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21` in my case), and symlink it to the correct path (in my case `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin22`)
> 5. Install `ffi` again and it should work. For me, I used this command: `arch -x86_64 sudo gem install ffi`
> 
> I hope this can help some people.

This work on my 2015 mac pro

**Comment by mrsantran** [comment]
Mac M! you need run this command:

`sudo arch -arm64 gem install ffi`

**Comment by AbeerAhmad** [comment]
check if there is any space in you root folder name or the folder its inside , remove that space and try again

**Comment by silaspedrosa** [comment]
> If you encounter the error "An error occurred while installing ffi (1.15.5), and Bundler cannot continue" while running the command npx react-native@latest init AwesomeProject, try initializing your project in a folder directory without spaces. For example, run npx react-native init on the "Desktop" directory, which usually doesn't have spaces in its path. This should resolve the issue.

In my case, the path didn't have any spaces, I just had to run `xcode-select --install`

However, if you encounter a problem a message like this 
```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
try checking if there aren't any available updates to it in the System Settings.

If you do install updates, please restart your computer.

**Comment by dhirajhimani** [comment]
https://github.com/ffi/ffi/issues/937#issuecomment-1368162894

This works, I got confused on last 4th point, so adding it 

`sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin23 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin22`

**Comment by dsanagar** [comment]
Thank you @yusam123 for valuable inputs. 

For step#4, I used following. Almost similar to @dhirajhimani mentioned. 
However, the symbolic link is created in universal-darwin22 and that too incorrectly, no matter how many times I tried. Because of that, I think the build is failing due to same reason as original post. 

dsangar-mbp-3:ruby-2.6.0 dsanagar$ sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin22/
Password:
dsangar-mbp-3:ruby-2.6.0 dsanagar$ ls -al universal-darwin22/
total 24
drwxr-xr-x  7 root  wheel  224 Sep 23 08:05 .
drwxr-xr-x  5 root  wheel  160 Dec 14  2022 ..
-rw-r--r--  1 root  wheel  205 Nov  4  2022 rb_mjit_min_header-2.6.10-arm64e.h
-rw-r--r--  1 root  wheel  205 Nov  4  2022 rb_mjit_min_header-2.6.10-x86_64.h
-rw-r--r--  1 root  wheel  192 Sep 30  2022 rb_mjit_min_header-2.6.10.h
drwxr-xr-x  3 root  wheel   96 Dec 14  2022 ruby
lrwxr-xr-x  1 root  wheel  194 Sep 23 08:05 universal-darwin21 -> /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21
dsangar-mbp-3:ruby-2.6.0 dsanagar$

**Comment by lanrehnics** [comment]
> [#937 (comment)](https://github.com/ffi/ffi/issues/937#issuecomment-1368162894)
> 
> This works, I got confused on last 4th point, so adding it
> 
> `sudo ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin23 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin22`


You might get Operation not permitted using this, it's best to use 

sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin23 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin22

**Comment by durga-nannamsetty** [comment]
@lanrehnics, you are right. I also got` Operation not permitted` error. Then I used your command and it executed without any error. After that I used `sudo gem install ffi` But I'm still getting the same ffi installation error.
 May I know what is the command you used after creating a symbolic link?

**Comment by lanrehnics** [comment]
> @lanrehnics, you are right. I also got` Operation not permitted` error. Then I used your command and it executed without any error. After that I used `sudo gem install ffi` But I'm still getting the same ffi installation error. May I know what is the command you used after creating a symbolic link?


Disclaimer !! You have to be careful with the next decisions

I was actually getting an error even after doing that, then I had to install another version of ruby using home brew.

`brew install ruby`

For M1, M2

`echo 'export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:$PATH"' >> ~/.zshrc`

For Intel

`echo 'export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.2.0/bin:$PATH"' >> ~/.zshrc`

The 3.2.0 in the command above assumes Homebrew installed a Ruby version that starts with 3.2. If it installed a different version, replace 3.2 with the first two digits of your Ruby version.

Then "refresh" your shell for these changes to take effect:

`source ~/.zshrc`

Or you can open a new terminal tab, or quit and restart Terminal.

Replace .zshrc with .bash_profile if you are using Bash. If you're not sure, read my guide to find out which shell you're using.

To check that you're now using the non-system version of Ruby, you can run the following commands:

`which ruby`

It should not be `/usr/bin/ruby`

`ruby -v`

It should be 3.1.3 or later.

Once you have this new version of Ruby installed, you can now install bundler (or any other gem):

I then install cocoa pod
`sudo gem install cocoapods`

and everything has been okay since then . 
 

[Source](https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma/54873916#54873916)

**Comment by JDMathew** [comment]
Ran into this error again today, updating X-Code Command Line Tools by running `xcode-select --install` fixed my issue

**Comment by oke-yomi** [comment]
> ```
> kevin@Kevins-MacBook-Air ~ % sudo arch -x86_64 gem install ffi
> Building native extensions. This could take a while...
> ERROR:  Error installing ffi:
> 	ERROR: Failed to build gem native extension.
> 
>     current directory: /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/ext/ffi_c
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0 -r ./siteconf20220124-41484-17xcahw.rb extconf.rb
> checking for ffi.h... *** extconf.rb failed ***
> Could not create Makefile due to some reason, probably lack of necessary
> libraries and/or headers.  Check the mkmf.log file for more details.  You may
> need configuration options.
> 
> Provided configuration options:
> 	--with-opt-dir
> 	--without-opt-dir
> 	--with-opt-include
> 	--without-opt-include=${opt-dir}/include
> 	--with-opt-lib
> 	--without-opt-lib=${opt-dir}/lib
> 	--with-make-prog
> 	--without-make-prog
> 	--srcdir=.
> 	--curdir
> 	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
> 	--with-ffi_c-dir
> 	--without-ffi_c-dir
> 	--with-ffi_c-include
> 	--without-ffi_c-include=${ffi_c-dir}/include
> 	--with-ffi_c-lib
> 	--without-ffi_c-lib=${ffi_c-dir}/lib
> 	--enable-system-libffi
> 	--disable-system-libffi
> 	--with-libffi-config
> 	--without-libffi-config
> 	--with-pkg-config
> 	--without-pkg-config
> /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
> You have to install development tools first.
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `block in try_compile'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:534:in `with_werror'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:585:in `try_compile'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1109:in `block in have_header'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:959:in `block in checking_for'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block (2 levels) in postpone'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:361:in `block in postpone'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:331:in `open'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:357:in `postpone'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:958:in `checking_for'
> 	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/mkmf.rb:1108:in `have_header'
> 	from extconf.rb:10:in `system_libffi_usable?'
> 	from extconf.rb:42:in `<main>'
> 
> To see why this extension failed to compile, please check the mkmf.log which can be found here:
> 
>   /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.15.5/mkmf.log
> 
> extconf failed, exit code 1
> 
> Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5 for inspection.
> Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-20/2.6.0/ffi-1.15.5/gem_make.out
> kevin@Kevins-MacBook-Air ~ % 
> ```

Ran into this problem. Here's how I fixed mine.

1.  In your `mkmf.log`, you would find the universal-darwinxx file you should have. In my case, it was `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin21`

2. Run this command `cd $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0` to confirm what files you currently have. I found that I had universal-darwin22

3. After you have confirmed that you have a different file, run this command `sudo ln -sf universal-darwin22 universal-darwin21`. This command creates a symbolic link named `universal-darwin21` that points to `universal-darwin22`.

This should fix the issue

**Comment by KatieHarris2397** [comment]
###                                                                                                                                                                                                                                                                                                                                                                                                 l]]

**Comment by staycreativedesign** [comment]
> Mac M1 you need run this command:
> 
> `sudo arch -arm64 gem install ffi`

this actually works, but my question is arent we supposed to be using brew for all this? instead of system?

**Comment by burhanwakhid** [comment]
> Mac M1 you need run this command:
> 
> `sudo arch -arm64 gem install ffi`

Thanks, this work fine for me

**Comment by Yandamuri** [comment]
`xcode-select --install` fixed issue. I am using `Macbook Pro M1 `and `Xcode 15.0.1`

**Comment by leoniralves** [comment]
> > @lanrehnics, you are right. I also got` Operation not permitted` error. Then I used your command and it executed without any error. After that I used `sudo gem install ffi` But I'm still getting the same ffi installation error. May I know what is the command you used after creating a symbolic link?
> 
> Disclaimer !! You have to be careful with the next decisions
> 
> I was actually getting an error even after doing that, then I had to install another version of ruby using home brew.
> 
> `brew install ruby`
> 
> For M1, M2
> 
> `echo 'export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/lib/ruby/gems/3.2.0/bin:$PATH"' >> ~/.zshrc`
> 
> For Intel
> 
> `echo 'export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.2.0/bin:$PATH"' >> ~/.zshrc`
> 
> The 3.2.0 in the command above assumes Homebrew installed a Ruby version that starts with 3.2. If it installed a different version, replace 3.2 with the first two digits of your Ruby version.
> 
> Then "refresh" your shell for these changes to take effect:
> 
> `source ~/.zshrc`
> 
> Or you can open a new terminal tab, or quit and restart Terminal.
> 
> Replace .zshrc with .bash_profile if you are using Bash. If you're not sure, read my guide to find out which shell you're using.
> 
> To check that you're now using the non-system version of Ruby, you can run the following commands:
> 
> `which ruby`
> 
> It should not be `/usr/bin/ruby`
> 
> `ruby -v`
> 
> It should be 3.2.+ or later.
> 
> Once you have this new version of Ruby installed, you can now install bundler (or any other gem):
> 
> I then install cocoa pod `sudo gem install cocoapods`
> 
> and everything has been okay since then .
> 
> [Source](https://stackoverflow.com/questions/51126403/you-dont-have-write-permissions-for-the-library-ruby-gems-2-3-0-directory-ma/54873916#54873916)

This worked for me.
The only difference was how I set the PATH in `zshrc`
`echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc`

**Comment by mediafinger** [comment]
I tried removing whitespaces manually, but to no avail. This tip of @chrisvasselli fixed the issue for me:

* https://github.com/ffi/ffi/issues/623#issuecomment-1550751609

```sh
brew uninstall --ignore-dependencies pkg-config
brew install pkg-config
```
