### ISSUE TITLE
Unable to attach functions ending in ? or !

### ISSUE THREAD

**Issue by eizengan** [ffi/ffi#971]
When attaching methods FFI is unable to attach method names ending in `?` or `!` - both of which are common Ruby-isms. The following illustrates the problem:

```ruby
require "ffi"
# => true
module Foo
  extend FFI::Library
  ffi_lib 'c'

  attach_function :malloc!, :malloc, [:size_t], :pointer
end
# Traceback (most recent call last):
#         ...
#         3: from (irb):6:in `<module:Foo>'
#         2: from /Users/nate.eizenga/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:275:in `attach_function'
#         1: from /Users/nate.eizenga/.asdf/installs/ruby/2.6.10/lib/ruby/gems/2.6.0/gems/ffi-1.15.5/lib/ffi/library.rb:275:in `attach'
# NameError (wrong class variable name @@malloc!)
```

**Comment by ParadoxV5** [comment]
How about using a Hash to store `attach_function`’s function objects (est. v2)?
The Hash can double as an API to reference the FFI function without relying on the generated method. (E.g., `@@functions[:calculate_something]` over `method(:calculate_something)`)
